### ISSUE TITLE
Package takeover: quickcheck-instances

### ISSUE THREAD

**Issue by phadej** [haskell-infra/hackage-trustees#100]
See https://mail.haskell.org/pipermail/haskell-cafe/2017-April/126726.html

The issue is related: https://github.com/nick8325/quickcheck/issues/158#issuecomment-296492840

**Comment by phadej** [comment]
I'll send an email to hackage admins to add me as maintainer in few days; if no-one objects.

**Comment by hvr** [comment]
@phadej  this reminds me of #97 :-)

**Comment by phadej** [comment]
oh, I forgot I made an issue
