### ISSUE TITLE
dependent-sum-template bounds bump

### ISSUE THREAD

**Issue by JonCoens** [haskell-infra/hackage-trustees#102]
The dependent-sum-template library does not have a set of bounds that work with stackage for GHC 8.0.2.

Upstream issue: https://github.com/mokus0/dependent-sum-template/issues/7

Since then, 4 different pull requests have been made to update the bounds of dependent-sum with no response from the maintainer. Looking at the repo, the last update was over a year ago.

Is it possible to get the latest Hackage release of dependent-sum-template to have the bumped bounds on dependent-sum?

This has left a handful of libraries manually working around the bounds issue. I know that this affects lambdabot, and I assume others since multiple pull requests have been made to bump the bounds on this repo.

**Comment by hvr** [comment]
I'm slightly hesitant to relax the upper bound, until somebody can reassure me that dependent-sump-template's API contract isn't broken by allowing a newer version of `dependent-sum`; I gave it a quick look, but since TH is involved, it's not easy to reason about the API :-/

**Comment by JonCoens** [comment]
I spoke with @ryantrinkle and he is taking over ownership of the `dependent-sum-template` package from @mokus0.

Thanks!
