### ISSUE TITLE
stream-fusion needs an upper bound

### ISSUE THREAD

**Issue by glguy** [haskell-infra/hackage-trustees#104]
This package is long since merged into base, but people appear to be able to find it. Could you trigger a matrix job for this package so we can see how far back to send the base upper bound?

**Comment by hvr** [comment]
Done & revised meta-data:

https://matrix.hackage.haskell.org/package/stream-fusion

On the bright side, we'll probably never going to have to touch the revised meta-data ever again as there's no missing upper bounds anymore.
