### ISSUE TITLE
Do not publish revisions for any packages I maintain or own

### ISSUE THREAD

**Issue by bitemyapp** [haskell-infra/hackage-trustees#106]
Anything listed here: http://hackage.haskell.org/user/bitemyapp

**Comment by bitemyapp** [comment]
If an upper bound needs bumped, file an issue or a PR.

**Comment by hvr** [comment]
Please refer to https://github.com/haskell-infra/hackage-trustees/blob/master/policy.md

**Comment by ndmitchell** [comment]
On [Reddit](https://www.reddit.com/r/haskell/comments/6iuy6n/we_should_stop_silently_fixing_other_peoples/djbg4uw/) @bitemyapp said:

> I've had silent modifications to my packages, with no notice, issue filed, or explanation.

If true, from what I can tell, that violates the policy linked to. @hvr, can you confirm the notification policy is being followed? @bitemyapp - can you say which package? @hvr - can you say what notification mechanism you are likely to have used?

**Comment by bitemyapp** [comment]
@ndmitchell https://github.com/bitemyapp/esqueleto/issues?utf8=%E2%9C%93&q=is%3Aissue

http://hackage.haskell.org/package/esqueleto-2.5.1

**Comment by bitemyapp** [comment]
@ndmitchell https://github.com/bitemyapp/esqueleto/pull/24

http://hackage.haskell.org/package/esqueleto-2.5.1

The revision was put up on Hackage before I merged, assented, or uploaded a fixed version.

**Comment by ndmitchell** [comment]
Thanks @bitemyapp. So, for the timeline:

* @hvr discovered the code is broken pre-GHC 7.8, which from the pull request seems to be accurate.
* @hvr opened a pull request, containing both the error message and a patch.
* 4 minutes later @hvr edited Hackage.

So it seems @hvr did tell you what was wrong, and raise a PR, but didn't mention it was also being modified on Hackage. I guess if the silent edit happened, you'd have been very happy with the interactions.

**Comment by bitemyapp** [comment]
>I guess if the silent edit happened, you'd have been very happy with the interactions.

What I want is a PR and to cut a release. No revisions. If people are going to continually ignore the wishes of people maintaining these libraries I'll figure something else out.

**Comment by MichaelXavier** [comment]
Apologies for barging in here and if this suggestion has already been made in another channel. What if the policy of both tightening and loosening constraints were amended to give the author a reasonable amount of time to respond on their own, kind of like how taking over package maintainership works. It seems like the maintainership policy was written to prioritize a package author's authority over their own projects when possible, and that seems like a good practice to carry over to constraints.

So for example, when a constraint issue is noticed, the trustee should open a PR or issue (or send an email) calling out the issue and give the author a few days to fix it with a release. In the mean time, affected cabal users should be able to work around the issue by checking out a patched revision into their sandbox, setting a temporary constraint in their own cabal file, etc. If the author does not respond, then the revision would happen. The process does not seem that much more of a time burden on the Trustee, they basically do the same steps they do now but in a different order.

What do you all think?

**Comment by phadej** [comment]
Sometimes the revision for **old** version is a **mandatory** thing. Releasing new one doesn't help.

Scenario: no revision is made (for `2.5.1`), but there is a new version (`2.5.2`). released with tighter bounds: from `>=4.5 && <5.0` to `>=4.8 && <5.0`. If the user has an old GHC: GHC-7.6 with `base-4.6`, and they try their luck, whether they can use newish `esqueleto == 2.5.*`, then the cabal solver *won't tell them, that cannot install new version (`2.5.2`)* **but** *will successfully pick old `2.5.1`*.

It's important to understand that tightening edits, *especially* for old versions are important, otherwise the whole state of Hackage will be poisoned, and cabal solver will have no chance to get valid = buildable install plan.

**Comment by phadej** [comment]
@MichaelXavier, it's also important that we act quickly, and correct obviously wrong bounds. Otherwise the Hackage will be poisoned until someone does something.

Hackage Trustees **only** tighten bounds, after the evidence that that particular version of package isn't buildable given specified constraints. And we pay extra care to do precise corrections. One could even say, that after seeing hundreds of building issues, we know quite well why they happen. E.g. we have cookbook.

**Comment by bitemyapp** [comment]
@phadej it's not mandatory at all, plenty of other package ecosystems do without and benefit thereby. I've seen people reach similar conclusions regarding immutable and mutable semantics in programming languages.

You can fork the older version, install it into a sandbox. If you're using Stack it's pretty easy to depend on a git repository. I don't know for sure, but I think Nix makes it pretty easy to do the right thing here.

Another option is to keep your package up to date and upgrade.

Every other ecosystem makes it clear that the right thing is to fix your package, not mutate package description files.

**Comment by MichaelXavier** [comment]
@phadej sounds like you're talking about backporting the dependency fix to older major versions. A few questions:
1. Does hackage support out-of-order releases, i.e. with `1.0.0` and `2.0.0` live, could I release a `1.0.1` release?
2. If today trustees do the backporting themselves with revisions, are they actually going through every single older version and tightening bounds, or is it more informed by what breaks for whoever files the issue?

**Comment by phadej** [comment]
1.  @MichaelXavier, yes one can release `1.0.1` after `2.0.0.` is live. But that won't help, as I told before. if `1.0.0` has too loose bounds, cabal solver may pick it.

2. Yes, we go thru **all** versions. For example: All `0.2.*` of `http-client-tls`  were broken, when `http-client-0.5` was released: I made revisions for all of them: https://matrix.hackage.haskell.org/package/http-client-tls

**Comment by phadej** [comment]
@bitemyapp please tell an example of such ecosystem, which has single-package version restriction, has deep and wide dependency graphs, and isn't over conservative with introducing breaking changes?

**Comment by bitemyapp** [comment]
@phadej Rust's Crates ecosystem (cargo is the command line application) has immutable packages, deep and wide dependency graphs, a comparable number of packages (about 10k), and they introduce breaking changes to libraries all the time. Hyper is a particularly good example of this as many things depend on it.

The point is that we don't need immutable packages. `cabal-install` users making use of packages should be setting package bounds that exclude bad versions. I certainly did when I used it.

**Comment by MichaelXavier** [comment]
@phadej ok, I see. So in your example, `2.5.1` incorrectly said it would allow a broader range of `base` than it really could, leading to those using older bases having a solvable dependency graph but compile-time errors with the package. So in that case `2.5.2` corrects this by expressing a tighter lower bound on `base`. But our goal for those on older base is to get their cabal-install to pick a *lower* version, say `2.4.0`. Your solution to that is to edit metadata, shooing off users of old-base from the basically invalid dependencies of `2.5.1`. If the dependency mistake was corrected in the released `2.5.2`, wouldn't we have the same effect if we just then marked 2.5.1 as deprecated, which should theoretically make cabal not pick it? It seems more a semantically appropriate choice anyways: that package was invalid and should be avoided. The user can even see that if they visit the package on hackage.

**Comment by phadej** [comment]
@bitemyapp that's were we disagree: your options is so

> every package user exclude invalid combinations: *O(n)*.

When my (and Trustees practice) is to

> fix invalid combination at the source of it. *O(1)*.

---

Rust Crates is different in a very important way,:they use **^1.2.3** -style versions bounds. Which is `>=0.1.2.3 && <0.2` in PVP (or `^>=0.1.2.3` as `Cabal-2.0` will support). On Hackage it's common practice to support wide range of major versions (`base` as an obvious example).

Please, go ahead and make your packages with `base == 4.9.*` (if you are using GHC-8.0), or `base-4.10.*`, and similarly for all other dependencies; then I can assure that you will hardly get any revisions by Hackage Trustee.

**Comment by phadej** [comment]
@MichaelXavier Deprecation marks a package version as less luckily to be picked up by the solver, it may still pick deprecated versions, especially if it's the only option. So
- yes, if user specifies `>=2.4` then *probably* some `2.4.*` version will be picked
- no, if user specifies `==2.5*`, the `2.5.1` will be picked as the only option.

Note: deprecation of a version is also a package metadata mutation!

Another note: your idea of deprecation is far more blunt, it means *"mark package unbuildable for all configurations"*, where the dependency bound revision is much more precise and less-intrusive action. The `2.5.1` isn't **broken**, only the metadata was slightly incorrect https://matrix.hackage.haskell.org/package/esqueleto (there are cases when e.g. a file is left out of the package tarball, then it's truly broken and cannot be fixed. In that case Hackage Trustees add `base <0` bound, which is a hacky way to make a package version unpickable by the solver)

**Comment by phadej** [comment]
And also to mention explicitly: go ahead and check whether `matrix.hackage.haskell.org` have build your packages, and how the matrix looks like. If there aren't build results, I'm happy to queue your packages as well.
