### ISSUE TITLE
Update bounds for ForestStructures and BiobaseNewick

### ISSUE THREAD

**Issue by GregorySchwartz** [haskell-infra/hackage-trustees#107]
See https://github.com/choener/ForestStructures/issues/1 and https://github.com/choener/BiobaseNewick/issues/1.

find-clumpiness is affected in Stackage.

**Comment by hvr** [comment]
This seems to have been handled upstream already

@GregorySchwartz  However, I can't help notice that `find-clumpiness` is omitting all bounds (see http://hackage.haskell.org/package/find-clumpiness-0.2.3.1/dependencies) which actively contributes to its build-plans being in a bad shape (see https://matrix.hackage.haskell.org/#/package/find-clumpiness)

**Comment by hvr** [comment]
@GregorySchwartz an easy way would be to add `pvp-bounds: both` to your `stack.yaml` file; when you `stack sdist` it will infer missing lower/upper bounds from the stackage snapshot and inject those into the `.cabal` file that's included in the source tarball.
