### ISSUE TITLE
`tasty-lens` and `smallcheck-lens` need version bumps for `base`

### ISSUE THREAD

**Issue by taktoa** [haskell-infra/hackage-trustees#108]
See jdnavarro/tasty-lens#1 and jdnavarro/smallcheck-lens#4.

**Comment by jdnavarro** [comment]
I'm the maintainer of those packages, sorry for the delay replying. @taktoa do the packages break when bumping `base` version?

**Comment by andreasabel** [comment]
Closing for lack of interest by reporter.
