### ISSUE TITLE
simple-sql-parser base upper-bound too tight

### ISSUE THREAD

**Issue by glguy** [haskell-infra/hackage-trustees#109]
https://github.com/JakeWheat/simple-sql-parser/issues/13

**Comment by bergmark** [comment]
I commented on that issue, so let's give it a few days and see if the maintainer notices?

**Comment by glguy** [comment]
OK. I don't see the value in leaving things in the current state in the meantime but if you want to check back in a couple of days that'd be great.

**Comment by bergmark** [comment]
Seems like it was resolved by the maintainer 👍
