### ISSUE TITLE
cgi < 3000.2

### ISSUE THREAD

**Issue by bergmark** [haskell-infra/hackage-trustees#11]
Trying out @hvr's awesome matrix builder :-)

`cgi < 3000.2` needs at least `base < 4.7` and `network < 2.6`

I only did a build with GHC 7.8.3:
http://164.138.31.15/matrix/cgi.html & http://164.138.31.15/matrix/cgi.log

**Comment by cartazio** [comment]
paging @cheecheeo, care to do teh honors as current maintainer, or would you like @bergmark to fire the missiles?

**Comment by cheecheeo** [comment]
cgi < 3001.2 won't build with >= GHC 7.8.3, this will change the .cabal files to inform cabal of that?

If so, go for it.

**Comment by hvr** [comment]
btw, here's some older (at time of writing it was generated on 28-Mar-2015) report ran against more GHC versions: https://ghc.haskell.org/~hvr/buildreports/cgi.html

**Comment by bergmark** [comment]
ah i forgot to check your archives!

**Comment by bergmark** [comment]
I changed the bounds i mentioned, running another build on more GHC versions now.

**Comment by bergmark** [comment]
This should be enough for me http://164.138.31.15/matrix/cgi.html so I'll close this.
