### ISSUE TITLE
newtype-generics

### ISSUE THREAD

**Issue by phadej** [haskell-infra/hackage-trustees#112]
There are various PRs

- https://github.com/jcristovao/newtype-generics/pull/12 by @sjakobi (Jan 24)
- https://github.com/jcristovao/newtype-generics/pull/14 by @niteria
- https://github.com/jcristovao/newtype-generics/pull/15 by @phadej
- https://github.com/jcristovao/newtype-generics/pull/16 by @conal

I'd go with my version, there's a travis build: https://travis-ci.org/phadej/newtype-generics/builds/257904081

**Comment by sjakobi** [comment]
@jcristovao has given me push access to the repo and Hackage, and I've uploaded a new version.

**Comment by phadej** [comment]
I triggered matrix build, I'll close the issue if it turns out full green

**Comment by phadej** [comment]
green: https://matrix.hackage.haskell.org/package/newtype-generics
