### ISSUE TITLE
NMU update for string-qq

### ISSUE THREAD

**Issue by jiaochangyang** [haskell-infra/hackage-trustees#113]
https://hackage.haskell.org/package/string-qq is totally bit rotten, in that it has a needless custom setup.hs that means it forces picking up installing an old cabal version (1.24) as a dep even when I'm using cabal 2.0, @cartazio  suggested I create a NMU request with hackage trustees because Audrey Tang is not active in Haskell land as of the past half decade, so an NMU to make it buildable with a new version might be useful.

**Comment by bergmark** [comment]
Hi @cj285, per [our policy](https://github.com/haskell-infra/hackage-trustees/blob/master/policy.md#policyprocedure-2) we'd like to see an pull request (or issue) filed to the repository first to give the maintainer a chance to respond.

**Comment by cartazio** [comment]
Adam: the GitHub repo doesn’t exist any more.

**Comment by bergmark** [comment]
? https://github.com/audreyt/string-qq

**Comment by cartazio** [comment]
Huh.  Maybe I was clicking on the wrong urls before

**Comment by bergmark** [comment]
I should also ask: Do we have an OK from hackage admins/@audreyt to just perform an NMU for her packages? Maybe we should keep a list of these users as I've heard of others that this applies to as well! I'll send an email to admins and ask.

**Comment by hesselink** [comment]
@audreyt looks active on github, and I don't have any emails saying it's ok to update all of her packages. There's an email address on her github, have you tried that one? If we could get an explicit ok for all packages in the future, that would make things easier.

**Comment by audreyt** [comment]
I'm fine with NMUs.

**Comment by gbaz** [comment]
looks like there's been a new upload since this ticket, so closing.
