### ISSUE TITLE
Old versions of graphviz have no constraint on fgl

### ISSUE THREAD

**Issue by ilovezfs** [haskell-infra/hackage-trustees#114]
Old versions of graphviz have no constraint on fgl. It looks like this affects everything `<=graphviz-2999.9.0.0`.

But even the latest version of graphviz (currently 2999.19.0.0) must constrain `fgl < 5.6`.

This can cause installs involving both graphviz and fgl to attempt to use one of the old graphviz versions to get around the fgl constraint if solver happens to choose `fgl >= 5.6`.

**Comment by ilovezfs** [comment]
@clinty This affects hopenpgp-tools 0.19.5. A workaround is to set a constraint `graphviz >= 2999.17.0.0` but that shouldn't really be needed.

**Comment by ilovezfs** [comment]
Also, CC @ivan-m

**Comment by gbaz** [comment]
c.f. the matrix which gets very red at the bottom :-) https://matrix.hackage.haskell.org/package/graphviz

**Comment by andreasabel** [comment]
The last 7 major versions of graphviz, 2999.14-20, starting 2012, are all green in the build matrix.  
The other versions have been deprecated.  Issue is fixed.
