### ISSUE TITLE
mighttpd2.cabal non-existent module

### ISSUE THREAD

**Issue by ilovezfs** [haskell-infra/hackage-trustees#116]
Currently the matrix is a sea of red for mighttpd2: https://matrix.hackage.haskell.org/package/mighttpd2

This is due to the Mighty module not existing. I've opened a PR upstream with a fix (courtesy of @hvr): https://github.com/kazu-yamamoto/mighttpd2/pull/16

However, there has been no response from the maintainer. Is this something that should be fixed downstream here until upstream does something?

**Comment by hvr** [comment]
There isn't much we can do other than maybe implement some hardcoded hack specifically for `mightttpd2`. Have you tried contacting the maintainer via email?

**Comment by ilovezfs** [comment]
https://github.com/kazu-yamamoto/mighttpd2/pull/16 has now been merged so it's a question of getting a new release.

**Comment by ilovezfs** [comment]
3.4.2 released!
