### ISSUE TITLE
Disable hscolour-1.24.3

### ISSUE THREAD

**Issue by ndmitchell** [haskell-infra/hackage-trustees#118]
Please disable hscolour-1.24.3. It doesn't compile, with the error:

```
Language\Haskell\HsColour\Classify.hs:50:23: error:
    Not in scope: `Char.isUpper'
```

It breaks everything that depends on it, including for new users, e.g. https://twitter.com/calaverainfo/status/936277501197914112

**Comment by ndmitchell** [comment]
CC @malcolmwallace

**Comment by bergmark** [comment]
Done. There is a newer release of hscolour out as well.
