### ISSUE TITLE
base-4.10.1.0 needlessly uses cabal-version: 2.0

### ISSUE THREAD

**Issue by tfausak** [haskell-infra/hackage-trustees#121]
https://hackage.haskell.org/package/base-4.10.1.0/revision/0.cabal

This is the same basic issue as #120. In fact, I mentioned it several times there. I'm opening a new issue because I can't re-open that one. 

Can `base-4.10.1.0` be revised to remove the `^>=` constraints?

**Comment by phadej** [comment]
I corrected the title of the issue.

**Comment by tfausak** [comment]
It's clear to me that this will never be fixed.
