### ISSUE TITLE
Packages missing upper bounds against either-5.0 

### ISSUE THREAD

**Issue by hvr** [haskell-infra/hackage-trustees#122]
- [x] https://matrix.hackage.haskell.org/package/postgresql-query
 - [x] https://matrix.hackage.haskell.org/package/validate-input
 - [x] https://matrix.hackage.haskell.org/package/ical
 - [x] https://matrix.hackage.haskell.org/package/thumbnail-plus

**Comment by phadej** [comment]
`postgresql-query` felt like a final boss. But not that level is cleared.
