### ISSUE TITLE
microlens-0.4.8.2 has garbage inside

### ISSUE THREAD

**Issue by dmwit** [haskell-infra/hackage-trustees#123]
It looks like the tarball for microlens-0.4.8.2 didn't get made quite right. In particular, the file src/Lens/Micro/Extra.hs inside has garbage and not Haskell code, causing the build to fail outright.

It would be nice to let cabal's solver know not to use this version if possible.

**Comment by dmwit** [comment]
Oh, and it looks like upstream has been notified here:

https://github.com/aelve/microlens/issues/99

**Comment by glguy** [comment]
After confirming that multiple .hs files were in fact binary data I've updated the constraint on this particular version to be unsatisfiable.

**Comment by phadej** [comment]
http://hdiff.luite.com/cgit/microlens/diff?id=0.4.8.2&id2=0.4.8.1

https://matrix.hackage.haskell.org/package/microlens Matrix is red atm

**Comment by hvr** [comment]
It looks like some random memory buffers from the machine producing the src-dist (containing something that looks like a bash history fragment) got written into the .tar... and judging from those shell fragments, this release could have been tarred up by Stack.

**Comment by dmwit** [comment]
Looks like other packages may be affected. microlens-th-0.4.1.2 just failed for me. I'm checking in on the rest of the microlens-* family now.

**Comment by dmwit** [comment]
microlens-th appears (to me) to be the only other package in the family to be affected.

**Comment by glguy** [comment]
microlens-th-0.4.1.2 was also affected

**Comment by neongreen** [comment]
The corrupted versions have been marked as unsatisfiable and I've uploaded new versions.

Thanks guys!
