### ISSUE TITLE
foundation 0.0.18

### ISSUE THREAD

**Issue by gwils** [haskell-infra/hackage-trustees#124]
Foundation 0.0.18 gives a bad install plan on GHC 7.8, as described here:
https://github.com/haskell-foundation/foundation/pull/460

The matrix builder confirms:
https://matrix.hackage.haskell.org/package/foundation#GHC-7.8/foundation-0.0.18

Please tighten the base bound to `base >=4.8 && <5`

**Comment by phadej** [comment]
Made a revision. Thanks for report! 

https://hackage.haskell.org/package/foundation-0.0.18/revisions/
