### ISSUE TITLE
Invalid bounds in bzlib-conduit

### ISSUE THREAD

**Issue by mrkkrp** [haskell-infra/hackage-trustees#129]
The package does not work with `conduit-1.3.0`, although it has `conduit >= 0.5`, which is incorrect. Also reported on the issue tracker of `bzlib-conduit`.

**Comment by hvr** [comment]
- [upstream issue](https://github.com/snoyberg/bzlib-conduit/issues/4)

Oh dear, after quickly assessing the situation I notice that quite a few of latest releases of packages pertaining to the conduit ecosystem have started removing version bounds (sometimes even lower bounds) for no apparent reason... :-/

Curiously, `bzlib-conduit-0.2.1.4` had a proper upper bound on `conduit`, which I've now restored in
https://hackage.haskell.org/package/bzlib-conduit-0.2.1.5/revisions/

**Comment by andreasabel** [comment]
Issue looks fixed (upstream issue is fixed).  Should anything of interest remain to be done here, please reopen with a TODO list.
