### ISSUE TITLE
generic-deriving 1.5.0 build failure with template-haskell 2.9

### ISSUE THREAD

**Issue by bergmark** [haskell-infra/hackage-trustees#13]
Build status: http://164.138.31.15/matrix/generic-deriving.html

I already published a new revision, so no further action required.

Pinging @dreixel just to inform that I made the change.

**Comment by dreixel** [comment]
I'm sorry but I don't understand this. What exactly broke, and how did you fix it?

**Comment by bergmark** [comment]
@dreixel You can hover the failed build, 1.5.0 on ghc 7.8.3 here http://164.138.31.15/matrix/generic-deriving.html to get the compilation error. The upper bound on TH was too loose. 

I fixed it by publishing a new revision of the cabal file using hackage's edit medatada feature, the change can be seen here: http://hackage.haskell.org/package/generic-deriving-1.5.0/revisions/

**Comment by dreixel** [comment]
Ok, thanks!
