### ISSUE TITLE
Seeking advice on mass-adding upper bounds

### ISSUE THREAD

**Issue by feuerbach** [haskell-infra/hackage-trustees#131]
Hi,

I'm about to release a new major version of tasty, and some of its core revdeps that I maintain (e.g. tasty-quickcheck) are going to be be affected.

This looks like a great use case for upper bounds and cabal file revisions, but there's no way I'm going to update every released version by hand.

Are there any tools I could use to automate this?

**Comment by hvr** [comment]
As a matter of fact, there is; when batch-edits become unavoidable, trustees use https://github.com/hackage-trustees/hackage-cli which allows to fetch a set of `.cabal` files (with an optional version filter) into the current folder; then you can operate on them with whatever text tools you see fit (e.g. like `git init & git add .`, throw `sed` at them; inspect `git diff` output, repeat until you're happy), then invoke `hackage-cli push-cabal --incr-rev *.cabal`; and if the output looks well enough, to push the revisions for real with `hackage-cli push-cabal --incr-rev --publish *.cabal`.

**Comment by feuerbach** [comment]
Thanks Herbert, I'll give it a try.
