### ISSUE TITLE
ghc-8.2.2 missing from Hackage

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-infra/hackage-trustees#134]
Creating an issue here per @hvr's request.

Currently, there is a Hackage entry for [ghc-8.2.1](http://hackage.haskell.org/package/ghc-8.2.1), but not for 8.2.2. Can someone with the necessary powers upload 8.2.2 as well?

**Comment by hvr** [comment]
finally: https://hackage.haskell.org/package/ghc-8.2.2
