### ISSUE TITLE
No way to tell which versions of dependencies are tested against

### ISSUE THREAD

**Issue by snoyberg** [haskell-infra/hackage-trustees#136]
For example, in https://matrix.hackage.haskell.org/package/conduit#GHC-7.10/conduit-1.2.13, it's impossible (at least for me) to see which version of resourcet was picked by the dep solver, making it close to impossible to determine what exactly went wrong here. It seems like it would be very useful for both failing _and_ succeeding builds to see the build plan chosen.

**Comment by hvr** [comment]
That's a great idea, and in fact I've got good news! It's been on the feature roadmap and there's been some work on that in the context of last year's GSOC - Stay tuned!

**Comment by gwils** [comment]
I would also like this.

In particular, when my build fails due to a dependency failing to build, I would like to know which one.

https://matrix.hackage.haskell.org/package/validation#GHC-7.4/validation-0.5.2

**Comment by gwils** [comment]
The backend for this is done. All we need to do is hook it into the matrix builder UI. That work is tracked at https://github.com/haskell-CI/hackage-matrix-builder/issues/52

I'll close this issue in favour of that one.
