### ISSUE TITLE
wl-pprint doesn't build on GHC 7.10

### ISSUE THREAD

**Issue by bergmark** [haskell-infra/hackage-trustees#14]
I've revised all versions to have `base < 4.8`, I tried to e-mail the maintainer but the e-mail address is no longer in use.

**Comment by bergmark** [comment]
Build log before changes: http://164.138.31.15/matrix/wl-pprint.html

I'd like an NMU for this, the fix is just `import Prelude hiding ((<$>))`.

**Comment by hvr** [comment]
@bergmark just take into account that `hiding ((<$>))` requires CPP, which is why I went a different route when fixing `ansi-wl-pprint` (which suffered from the very same issue)

**Comment by bergmark** [comment]
Here's my suggested fix following @hvr's example https://github.com/bergmark/wl-pprint/compare/8be0f38...1.1.0.1

**Comment by bergmark** [comment]
wl-pprint seems to have changed maintainers, 1.2 supports GHC 7.10.

**Comment by hvr** [comment]
https://noamlewis.wordpress.com/2015/04/14/the-wl-pprint-package-maintainer/
