### ISSUE TITLE
Revise haskell-src-meta-0.8.0.2, let it build with ghc 8.4.1

### ISSUE THREAD

**Issue by DanBurton** [haskell-infra/hackage-trustees#143]
There is an open PR for relaxing the bounds: https://github.com/bmillwood/haskell-src-meta/pull/72

Haven't heard from @bmillwood yet but I believe this revision to be fairly benign (tests passed on my machine), and it would be a great help for unblocking a lot more stuff to build on ghc-8.4.1. (My interest in this is the `persistent-*` packages in particular.)

**Comment by bergmark** [comment]
Filed a revision, see https://github.com/bmillwood/haskell-src-meta/pull/72
