### ISSUE TITLE
tasty 0.11 and 0.12 broken with GHC 8.4.1

### ISSUE THREAD

**Issue by merijn** [haskell-infra/hackage-trustees#145]
See https://github.com/feuerbach/tasty/issues/214#event-1531833321

**Comment by phadej** [comment]
@gwils please mention in #135 how many versions were affected, it's an interesting statistic!

**Comment by gwils** [comment]
I've made all the necessary revisions so that tasty is now fully green on the matrix builder and with GHC 8.4.1

**Comment by Merjin** [comment]
random tag typo is random.
