### ISSUE TITLE
Revise YAML 0.8.29 to avoid failing on GHC 7.4

### ISSUE THREAD

**Issue by ndmitchell** [haskell-infra/hackage-trustees#147]
https://matrix.hackage.haskell.org/package/yaml shows that YAML 0.8.29 generates a bogus install plan on GHC 7.4. I note that a revision was made to 0.8.28 which fixes the issue by @hvr  - if the revision could be applied to 0.8.29 as well that would be useful.

I've submitted the suitable revision upstream so 0.8.30 will have the correct value from the start.

**Comment by gwils** [comment]
Thanks. I've made the revision as you've asked.
