### ISSUE TITLE
static-canvas version bounds

### ISSUE THREAD

**Issue by vaibhavsagar** [haskell-infra/hackage-trustees#150]
`static-canvas` has overly restrictive bounds on `base` and `free`. The maintainer did not respond to a much earlier PR: https://github.com/jeffreyrosenbluth/static-canvas/pull/4. Would it be possible to relax the bounds with a Hackage revision?

**Comment by phadej** [comment]
Let me see.

**Comment by gwils** [comment]
I've had a look at the code and tried building, and I think this is a good candidate for relaxating bounds, but I haven't done that before so I'd like a second opinion.

**Comment by phadej** [comment]
revised

**Comment by vaibhavsagar** [comment]
Thanks so much @phadej!
