### ISSUE TITLE
relax hsx-jmacro dependency on wl-pprint-text

### ISSUE THREAD

**Issue by clinty** [haskell-infra/hackage-trustees#158]
hsx-jmacro builds just fine with newer wl-pprint-text on GHC >= 8 (and doesn't appear to build with old GHC via jmacro in any case)

https://github.com/Happstack/hsx-jmacro/pull/1

https://github.com/commercialhaskell/stackage/issues/3608

**Comment by phadej** [comment]
Travis is red and doesn't include GHC-8.2 nor 8.4.

**Comment by clinty** [comment]
That's what https://github.com/Happstack/hsx-jmacro/pull/2 is for

**Comment by gbaz** [comment]
This looks like there's a newer version of hsx-jmacro that resolves this, so I'll close.
