### ISSUE TITLE
hastache needs a non-maintainer-upload

### ISSUE THREAD

**Issue by gbaz** [haskell-infra/hackage-trustees#161]
it is deprecated in favor of mustache but still has some deps. It needs an nmu to work since it not only needs bounds on base but also semigroup instances.

**Comment by phadej** [comment]
Can't the deps be adopted to use stache or microstache?

**Comment by gbaz** [comment]
Yeah, probably :-) I guess we don't need to keep deprecated packages working forever. Is there a migration guide for hastache ->  microstache?

(this is for the haskell platform website btw)

**Comment by phadej** [comment]
@gbaz unfortunately no such guide exist.

https://github.com/bos/criterion/commit/df4515c4ba62d444b803d1e80e0f8f96eb4a8d31 might help, seems `hastache` used `MuVar`, where `microstache` relies on `ToJSON` instances (and `Value` values).

As `microstache` is clone of `stache`, https://www.stackbuilders.com/tutorials/haskell/mustache-templates/ should be applicable as well.
