### ISSUE TITLE
text-format SMP

### ISSUE THREAD

**Issue by phadej** [haskell-infra/hackage-trustees#163]
https://github.com/bos/text-format/pull/21

That's not the best patch possible, I'll prepare better one.

**Comment by phadej** [comment]
A made a PR: https://github.com/bos/text-format
Travis build: https://travis-ci.org/phadej/text-format/builds/405767426

**Comment by hvr** [comment]
I contacted Bryan on Jun 27th about `text-format` but didn't get any reply yet; so at this point I think we should go forward w/ the NMU (and I'm confident Bryan is ok with it anyway).

**Comment by gbaz** [comment]
added to maintainers group

**Comment by phadej** [comment]
Uploaded https://hackage.haskell.org/package/text-format-0.3.2
