### ISSUE TITLE
Packages wrongly advertising compatibility w/ containers-0.6

### ISSUE THREAD

**Issue by hvr** [haskell-infra/hackage-trustees#164]
- [x] `regex-tdfa`  (12 revisions performed; upstream: ChrisKuklewicz/regex-tdfa#17)
- [x] `hslogger` (several revisions performed; also needed `time < 1.5` bounds)

**Comment by RyanGlScott** [comment]
Here's some more packages I've uncovered in hvr/head.hackage#68 and hvr/head.hackage#70:

* [ ] `ixset-1.1`
* [ ] `ixset-typed-0.4`
* [ ] `language-c-0.8.1`
* [ ] `multiset-0.3.4`

**Comment by phadej** [comment]
@gwils have revisited language-c it seems.

There are no other packages listed here. if there are some other packages, let's collect htem in #166
