### ISSUE TITLE
diagrams and related

### ISSUE THREAD

**Issue by phadej** [haskell-infra/hackage-trustees#167]
https://matrix.hackage.haskell.org/package/diagrams-lib

From: 

![screenshot from 2018-07-05 19-12-36](https://user-images.githubusercontent.com/51087/42334949-75952d8a-8087-11e8-838f-255eef5c7598.png)

to

![screenshot from 2018-07-05 19-12-45](https://user-images.githubusercontent.com/51087/42334954-7a8ae8ac-8087-11e8-98e0-6e43edc5965c.png)

Also SVGFonts doesn't look good

![screenshot from 2018-07-05 19-12-54](https://user-images.githubusercontent.com/51087/42334967-836437da-8087-11e8-9c69-ad0f3fcdc7ce.png)

----

It isn't obvious for me what causes new breakage.

**Comment by hvr** [comment]
@phadej I can at least explain some of the failures in diagrams-lib: The `diagrams-core` 1.4.1.1 release wasn't backward compatible w/ 1.4.1 as it converted classes into constraintkinds such as e.g.

```diff
--- a/src/Diagrams/Core/Envelope.hs
+++ b/src/Diagrams/Core/Envelope.hs
@@ -1,4 +1,5 @@
 {-# LANGUAGE CPP                        #-}
+{-# LANGUAGE ConstraintKinds            #-}
 {-# LANGUAGE FlexibleContexts           #-}
@@ -255,10 +256,9 @@ this explanation.
 
 -- | When dealing with envelopes we often want scalars to be an
 --   ordered field (i.e. support all four arithmetic operations and be
---   totally ordered) so we introduce this class as a convenient
+--   totally ordered) so we introduce this constraint as a convenient
 --   shorthand.
-class (Floating s, Ord s) => OrderedField s
-instance (Floating s, Ord s) => OrderedField s
+type OrderedField s = (Floating s, Ord s)
```

I've tried adding unconditional `diagrams-core < 1.4.1.1` bounds in some places where it made sense; it probably won't be enough

**Comment by hvr** [comment]
As discussed w/ @byorgey I made a revision at https://hackage.haskell.org/package/diagrams-core-1.4.1.1/revisions/ to reject `diagrams-core1.4.1.1` on GHC 7.6 and older; this had the effect of preventing the solver picking the combinations of GHC < 7.6 && diagrams-core>=1.4.1.1 && diagrams-lib >= 1.4.2.2 which would result in these compile failures as can be seen on https://matrix.hackage.haskell.org/package/diagrams-lib
