### ISSUE TITLE
MaybeT

### ISSUE THREAD

**Issue by bergmark** [haskell-infra/hackage-trustees#17]
Build matrix: http://164.138.31.15/matrix/MaybeT.html

Did 0.1.0 of this package ever build? Should I just restrict the `base` dep to below the lowest I tested with?

**Comment by hvr** [comment]
Yeah, I'd just set `base <4.3` for `0.1.0` (and `base<4.8` for `0.1.1` and `0.1.2`); that would accurately cover all GHC 7.* releases...

**Comment by bergmark** [comment]
Did just that, thanks!

http://hackage.haskell.org/package/MaybeT-0.1.0/revisions/
http://hackage.haskell.org/package/MaybeT-0.1.1/revisions/
http://hackage.haskell.org/package/MaybeT-0.1.2/revisions/
