### ISSUE TITLE
json-builder is broken from GHC-8.4 onwards.

### ISSUE THREAD

**Issue by AndreasPK** [haskell-infra/hackage-trustees#170]
> How and when was the maintainer for the package requiring action contacted?

About 4 Months ago:
https://github.com/lpsmith/json-builder/issues/2

There is also an open pull request with a fix for almost as long.
https://github.com/lpsmith/json-builder/pull/3

Edit: I've also emailed the Author on the 21st of July. Without a response so far.

> If available, a link to the filed issue in the upstream issue tracker

^

> How critical is this, what's the impact of this breakage? E.g. how many dependent packages are affected by this? Which GHC versions are affected?

This breaks all dependent packages using GHC-8.4 or newer. I noticed it because it breaks aesons benchmarks.

**Comment by hvr** [comment]
@AndreasPK are you asking for an NMU?

**Comment by phadej** [comment]
@AndreasPK out of curiosity, where you use `json-builder`, and can't you move to use `aeson`'s `toEncoding`. If not, why?

**Comment by AndreasPK** [comment]
> @AndreasPK out of curiosity, where you use json-builder, and can't you move to use aeson's toEncoding. If not, why?

I use it transitivly be running aeson benchmarks.

Maybe using toEncoding is a valid replacement, maybe it's not. I honestly don't know. 

I'm in the process of benchmarking a change to GHC, and for this I am trying to run benchmarks from various core/popular Haskell packages. 
If there are easy fixes I do try to upstream the changes I make to get benchmarks to run. But rewriting the inner workings of broken benchmarks is just not feasible in terms of time investment.

**Comment by phadej** [comment]
FWIW, PR mentioned breaks package for pre-GHC-8.0 . I'd like to see something like https://github.com/bos/text-format/pull/23/files

**Comment by gwils** [comment]
I have made metadata revisions so that no current version of `json-builder` will try to build on GHC 8.4 or above.

**Comment by phadej** [comment]
I made a PR to `aeson` so `json-builder` benchmarks are not compiled with more recent GHC.
