### ISSUE TITLE
foundation/basement fail with inscrutable error messages for for older ghc versions

### ISSUE THREAD

**Issue by jgm** [haskell-infra/hackage-trustees#171]
See https://github.com/haskell-foundation/foundation/commit/556736e5691ecc270a8a8d310b8772b6f07eabf8#r29694773

I recommend that a lower-bound constraint on base be added, or a constraint `base < 0` conditional on ghc version < 8.0, so that the error message will point in the right direction.

**Comment by phadej** [comment]
Adding bounds doesn't help with this.

`cabal-install-2.2` from HVR's PPA and upcoming `cabal-install-2.4` will handle these (ab)use of `buildable`. If using those isn't possible, ask maintainer to release a version without `buildable: false`, but using `base` bounds (or other-extensions to guide cabal's solver).

See https://github.com/haskell-infra/hackage-trustees/issues/16

**Comment by hvr** [comment]
@phadej btw, we actually can, see http://hackage.haskell.org/package/yaml-0.8.31/revisions/

**Comment by hvr** [comment]
@jgm I've revised `foundation-0.0.21` @ http://hackage.haskell.org/package/foundation-0.0.21/revisions/

can you confirm this works for you (after having `cabal update`d)?

**Comment by jgm** [comment]
Yes, now I get a better error message:

Error:
    Dependency on unbuildable library from basement
    In the stanza 'library'
    In the package 'memory-0.14.16'

Thanks!

Best,
John

Herbert Valerio Riedel <notifications@github.com>
writes:

**Comment by jgm** [comment]
Still, I would have expected cabal new-build to find a viable build
path. After all, when I explicitly insert a constraint
basement < 0.0.8 and foundation < 0.0.21, it builds
with ghc 7.10.3.

For now I'll keep these constraints in my cabal file.

Best,
John

**Comment by phadej** [comment]
@jgm I also revised `basement`: https://hackage.haskell.org/package/basement-0.0.8/revisions/, could you try once again?

**Comment by hvr** [comment]
@jgm ok, that's *very* strange; can you tell us how to reproduce this?

**Comment by jgm** [comment]
Works now, thanks!
