### ISSUE TITLE
inaccurate version bounds in tidal-midi 

### ISSUE THREAD

**Issue by hvr** [haskell-infra/hackage-trustees#172]
migrated from https://github.com/haskell/cabal/issues/5517 (reported originally by @z0it)

## Original situation

![](https://user-images.githubusercontent.com/285533/44003689-2d9ceb92-9e57-11e8-969c-b97124e71f6c.png)

## Current situation (wip)

see https://matrix.hackage.haskell.org/package/tidal-midi

**Comment by hvr** [comment]
@z0it can you `cabal update` and retry?

**Comment by z0it** [comment]
@hvr pretty sure I tried this earlier and it didn't work, however I've just done it now and got tidal-midi installed and working. thanks

**Comment by hvr** [comment]
@z0it well, I performed a couple of metadata revisions to fix the issue; hence why it didn't work when you tried earlier

**Comment by andreasabel** [comment]
Development of `tidal-midi` has stopped.
I anyway made a revision so that I could build it: https://hackage.haskell.org/package/tidal-midi-0.9.10/revisions/
