### ISSUE TITLE
Repair hsdev's install-plans

### ISSUE THREAD

**Issue by hvr** [haskell-infra/hackage-trustees#173]
`hsdev` is in a suboptimal shape and this translates to a poor user experience when trying to install `hsdev` as it's quite easy to hit one of the many bad build plan configurations.

Fixing this involves multiple packages:

 - https://github.com/mvoidex/hformat/issues/2
 - https://github.com/mvoidex/simple-log/issues/4
 - https://github.com/mvoidex/text-region/pull/1
 - ...

## Original Situation

![](https://user-images.githubusercontent.com/285533/44512812-fee02e00-a6bb-11e8-8ed3-a22bbdc83f33.png)

**Comment by gwils** [comment]
The board isn't completely green, but it looks like this is more or less done @hvr ?

**Comment by andreasabel** [comment]
Situation as of today isn't much better except for the latest release (0.3.4.0).
I filed https://github.com/mvoidex/hsdev/issues/107 for the build failure with GHC 8.0.
<img width="748" alt="Screenshot 2021-10-06 at 18 22 33" src="https://user-images.githubusercontent.com/1155218/136244195-57649fb6-c8bd-4bfc-b53d-70e8efcd27fd.png">

**Comment by andreasabel** [comment]
Sadly, we do not have the hackage matrix anymore.
Issue is stale, closing.
