### ISSUE TITLE
Repair `pandoc-citeproc`'s install plans

### ISSUE THREAD

**Issue by hvr** [haskell-infra/hackage-trustees#174]
## Current situation

See https://matrix.hackage.haskell.org/package/pandoc-citeproc

## Original situation

![pandoc-citeproc](https://user-images.githubusercontent.com/285533/44896268-eee9cf00-acf7-11e8-896c-881e8868f869.png)

**Comment by gwils** [comment]
This looks done @hvr . Do you agree?

**Comment by andreasabel** [comment]
Looked good until 0.16.2, but 0.17 seems to have problems again:
<img width="746" alt="Screenshot 2021-10-06 at 18 48 52" src="https://user-images.githubusercontent.com/1155218/136248316-aed67720-8641-4d2e-a80a-05ea25c3ca10.png">

However, `pandoc-citeproc` is deprecated in favor of `citeproc`: https://github.com/jgm/pandoc-citeproc#pandoc-citeproc
