### ISSUE TITLE
Repair git-annex build-plans

### ISSUE THREAD

**Issue by hvr** [haskell-infra/hackage-trustees#178]
The buildplans for https://matrix.hackage.haskell.org/package/git-annex are severely damaged currently:

![git-annex](https://user-images.githubusercontent.com/285533/46242263-e522bc80-c3c6-11e8-9fc0-f890a286c050.png)

**Comment by hvr** [comment]
One major culprit was `persistent` having inaccurate metadata in the persistent-2.7.2 release to a degree which manifested and which propagated into `git-annex`'s build-plans (now fixed up in https://hackage.haskell.org/package/persistent-2.7.2/revisions/). This really stresses how important it is to keep upper bounds accurate at all times even for non-latest releases!

![persistent](https://user-images.githubusercontent.com/285533/46243225-1785e700-c3d2-11e8-9ca1-f7687e78f660.png)

cc @MaxGabriel

**Comment by andreasabel** [comment]
Looks like the build matrix cannot help us here:
<img width="1021" alt="Screenshot 2021-10-06 at 19 00 12" src="https://user-images.githubusercontent.com/1155218/136249980-190fbd6d-0aa8-4347-848c-1d7ea6391f80.png">
There aren't any build reports available.
