### ISSUE TITLE
Bump stm bound for exception-transformers

### ISSUE THREAD

**Issue by athas** [haskell-infra/hackage-trustees#180]
Could a revision be added to http://hackage.haskell.org/package/exception-transformers that bumps the stm bound from <2.5 to <2.6?  I have verified that it builds and    tests pass with 2.5.

**Comment by hvr** [comment]
upstream issue: https://github.com/mainland/exception-transformers/issues/7

**Comment by hvr** [comment]
Done via https://hackage.haskell.org/package/exception-transformers-0.4.0.7/revisions/

What makes this weird is that the `stm` dependency is redundant; the package doesn't use any modules from `stm`.
