### ISSUE TITLE
 Bump base bound for vector-binary-instances

### ISSUE THREAD

**Issue by athas** [haskell-infra/hackage-trustees#181]
Could a revision be added to http://hackage.haskell.org/package/vector-binary-instances-0.2.4 that bumps the base bound from <4.12 to <4.13? I have verified that it builds with 4.12. [Upstream issue](https://github.com/bos/vector-binary-instances/pull/15).

**Comment by RyanGlScott** [comment]
There is now a [`vector-binary-instances-2.5`](http://hackage.haskell.org/package/vector-binary-instances-0.2.5) on Hackage which supports `base-4.12`.

**Comment by athas** [comment]
Yes, thanks for that!  I guess bumping the older versions is redundant now.

**Comment by hvr** [comment]
@bgamari @RyanGlScott next time please be more careful and avoid making unnecessary releases when a revision would have been more appropriate; see http://hdiff.luite.com/cgit/vector-binary-instances/diff?id=0.2.5&id2=0.2.4

**Comment by bgamari** [comment]
This was wholly my fault. I could have sworn there were testsuite changes in that release but it seems there weren't.

However, I do wonder whether there is some way to improve the ergonomics of revisions. `hackage-cli` is a start, but it makes revisions feel very much like a second-class citizen, forcing maintainers to have two completely separate workflows for revisions and releases (e.g., see https://github.com/bgamari/hs-maintainer-tools). As long as this is the case it seems like there will naturally be a gravitation towards the more powerful of the two; afterall, humans are fallible and, at times, lazy.
