### ISSUE TITLE
safecopy needs revision with relaxed upper bounds on template-haskell and containers 

### ISSUE THREAD

**Issue by clinty** [haskell-infra/hackage-trustees#183]
1,2,3.
https://github.com/acid-state/safecopy/issues/68
https://github.com/acid-state/safecopy/issues/69

4. Makes these revdeps unavailable on GHC 8.6: https://packdeps.haskellers.com/reverse/safecopy

**Comment by adamgundry** [comment]
Looks like this has been resolved by the release of `safecopy-0.9.4.2`.

**Comment by phadej** [comment]
@adamgundry thanks for notice, closing
