### ISSUE TITLE
Purescript compiler needs base bump

### ISSUE THREAD

**Issue by vmchale** [haskell-infra/hackage-trustees#188]
The `purescript` library requires `base (>=4.8 && <4.11)` but this can be relaxed to `>= 4.8 && < 4.12`.

**Comment by cartazio** [comment]
maybe i'm being slow today... but i think you meant a different change,
those two bound seem the same to me ...

**Comment by vmchale** [comment]
Oh, whoops. Fixed the original comment.

**Comment by gwils** [comment]
I've tried to build the latest purescript version with `--allow-newer='purescript:base'`. It will require a bound [bump to spdx](https://github.com/phadej/spdx/pull/14). Even then, purescript seems to be missing a `Semigroup` instance for `PSString` that would be required by 8.4, so bumping the base bound on the current version would be unwise.

**Comment by vmchale** [comment]
Ah okay. I believe that has been fixed in the actual repo but not yet in the upload :\
