### ISSUE TITLE
Bumping the containers bound on language-c-quote, mainland-pretty, and symbol

### ISSUE THREAD

**Issue by athas** [haskell-infra/hackage-trustees#189]
The following (closely related) packages have a too tight bound on `containers` (`<0.6`).  The bound should be relaxed to `<0.7`.

* [language-c-quote](http://hackage.haskell.org/package/language-c-quote) ([upstream issue](https://github.com/mainland/language-c-quote/pull/82))
* [mainland-pretty](http://hackage.haskell.org/package/mainland-pretty) ([upstream issue](https://github.com/mainland/mainland-pretty/pull/16))
* [symbol](http://hackage.haskell.org/package/symbol) ([upstream issue](https://github.com/mainland/symbol/pull/4))

**Comment by ckoparkar** [comment]
@athas Perhaps we need to start an email thread again ?

**Comment by gwils** [comment]
I have revised these three.

**Comment by ckoparkar** [comment]
Thanks @gwils.
