### ISSUE TITLE
edit-distance and GHC 7.10

### ISSUE THREAD

**Issue by bergmark** [haskell-infra/hackage-trustees#19]
Matrix build before revisions: http://164.138.31.15/matrix/edit-distance.html
I added upper bounds on base.

A PR was opened 9 days ago to add GHC 7.10 compatibility: https://github.com/batterseapower/edit-distance/pull/3 , The fix is backwards-compatible, enabling `FlexibleContexts` in one module.

Opening this seeing as we did an NMU for another package by @batterseapower and he still shows no github activity.

**Comment by bergmark** [comment]
I sent an e-mail to Max.

**Comment by gbaz** [comment]
ok i think we're ok to do an nmu on this now?

**Comment by bergmark** [comment]
Yes, I forgot to say that I sent another e-mail to Max a week ago saying we'd do an NMU. I'll prepare the fix.

**Comment by bergmark** [comment]
https://github.com/batterseapower/edit-distance/compare/master...hackage-trustees:master

Tested on GHC-7.0 through 7.10.

Trustee review please!

**Comment by hvr** [comment]
LGTM

**Comment by hesselink** [comment]
I've added you as a maintainer, so you can do the upload.

**Comment by bergmark** [comment]
Done!
