### ISSUE TITLE
xmonad-wallpaper revision (newer xmonad, newer random)

### ISSUE THREAD

**Issue by clinty** [haskell-infra/hackage-trustees#191]
Emailed haskell.ye.yan@gmail.com today.

xmonad-wallpaper could use a revision to build with current xmonad and random.

**Comment by gwils** [comment]
I've made a revision. xmonad needed updating, but random was already the latest version.
https://hackage.haskell.org/package/xmonad-wallpaper-0.0.1.4/revisions/
