### ISSUE TITLE
Fix combinat bounds

### ISSUE THREAD

**Issue by vmchale** [haskell-infra/hackage-trustees#193]
The bounds on `combinat` are incorrect; the matrix CI shows some failures: https://matrix.hackage.haskell.org/#/package/combinat

I saw this when trying to compile `combinat-0.2.9.0` with GHC 7.8.4

**Comment by phadej** [comment]
I revised the latest version, so you can compile with 7.8.4; will edit the rest later today

**Comment by phadej** [comment]
matrix is green
