### ISSUE TITLE
haskell-gi-base: old bounds are incorrect

### ISSUE THREAD

**Issue by vmchale** [haskell-infra/hackage-trustees#194]
As can be seen in the matrix CI here: https://matrix.hackage.haskell.org/#/package/haskell-gi-base/

This is causing `termonad` to fail to build.

**Comment by gwils** [comment]
I have started investigating this. One thing affecting termonad was focuslist, which I've now revised and made a pull request.

**Comment by gwils** [comment]
This will be easier to investigate when a new version of `focuslist` is released. It would also help if the old versions of singletons had their bounds restricted (#198)

I'm not convinced that `haskell-gi-base` is responsible for any `termonad` failures, but its build plans should be fixed anyway.

**Comment by hvr** [comment]
@gwils btw, `focuslist-0.1.0.1` was released some time ago

**Comment by andreasabel** [comment]
Fixed `base` bounds for haskell-gi-base-0.25: https://github.com/haskell-gi/haskell-gi/issues/364

The OP is quite old now and there is no clear plan of action, so I am closing this issue.  Welcome to reopen if interest.
