### ISSUE TITLE
Restrict bounds in `singletons`

### ISSUE THREAD

**Issue by gwils** [haskell-infra/hackage-trustees#198]
Many releases of `singletons` give bad install plans nowadays, including on newer GHCs. It would be helpful to restrict their bounds.

**Comment by phadej** [comment]
@gwils you mean *old* ones? https://matrix.hackage.haskell.org/#/package/singletons

Is there some packages without _lower_ bounds on `singletons`?

**Comment by hvr** [comment]
fwiw, if you scroll through the historic reports you'll notice that some failures were introduced somewhere between 2018-08 and 2018-09

**Comment by hvr** [comment]
@RyanGlScott thanks!

As can be seen from the latest report this has been dealt with therefore closing.
