### ISSUE TITLE
lates JuicyPixels fails on GHC < 8.4.4

### ISSUE THREAD

**Issue by vmchale** [haskell-infra/hackage-trustees#201]
See the [build matrix](https://matrix.hackage.haskell.org/#/package/JuicyPixels).

**Comment by hvr** [comment]
Thanks for reporting! I see you filed a PR already at https://github.com/Twinside/Juicy.Pixels/pull/170

I've revised https://hackage.haskell.org/package/JuicyPixels-3.3.3/revisions/ accordingly

cc @Twinside
