### ISSUE TITLE
graphviz still not compatible with GHC 8.6

### ISSUE THREAD

**Issue by clinty** [haskell-infra/hackage-trustees#204]
https://github.com/ivan-m/graphviz/issues/39

https://github.com/ivan-m/graphviz/pull/42

**Comment by hvr** [comment]
pinging @ivan-m

**Comment by clinty** [comment]
no, I have not

**Comment by ivan-m** [comment]
Sorry, life has been busy.  I hadn't made a new release yet as I couldn't figure out why Travis-CI wasn't working; just realised now that the new .travis.yml I had built (as the old one wasn't working with 8.6) had stripped out the explicit install of the Graphviz tools.  Waiting for it to finish and if successful will release.

**Comment by ivan-m** [comment]
Uploaded

**Comment by clinty** [comment]
Looks good.
