### ISSUE TITLE
gtk package should require Cabal <2.5 to allow compilation with GHC 8.6

### ISSUE THREAD

**Issue by vmchale** [haskell-infra/hackage-trustees#208]
The latest [gtk](http://hackage.haskell.org/package/gtk) can be built with the latest version of Cabal without any problems.

**Comment by sjakobi** [comment]
Seems like the build with GHC 8.6 has been fixed: https://matrix.hackage.haskell.org/#/package/gtk

**Comment by gbaz** [comment]
looks good, closing
