### ISSUE TITLE
transformers-0.5.5.0-related issues

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-infra/hackage-trustees#209]
Due to https://ghc.haskell.org/trac/ghc/ticket/16199, the version of `transformers-0.5.5.0` that is bundled with GHC 8.6.1, 8.6.2, and 8.6.3 does not actually correspond to a Hackage release. What's worse, this version of `transformers` features API changes not present in the Hackage release of `0.5.5.0`! In particular, this commit is present in the GHC-bundled version:

* [`80557845cdc0e72bc05cec19cf7a1bf5495e9e69`](https://gitlab.haskell.org/ghc/packages/transformers/commit/80557845cdc0e72bc05cec19cf7a1bf5495e9e69)

As I've come to discover, the presence of this commit is the only reason that the `contravariant-1.5` library compiles on GHC 8.6 or later. That is, if you use GHC 8.6 but reinstall `transformers-0.5.5.0` from Hackage, then `contravariant-1.5` will fail to build! Ack!

This issue serves to track what needs to be done to sort out this situation.

**Comment by hvr** [comment]
My suggested course of action is to

1. blacklist `transformers-0.5.5.0` release on Hackage, to prevent installation of that release from source (as it would result in `transformers-0.5.5` not being a good API identifier)
2. cut a fixup release  `transformers-0.5.5.1` which corresponds to the exposed API from GHC 8.6.3's bundled `transformers-0.5.5.0` release (this would cabal to install the `transformers-0.5.5` from source as well as make sure that `MIN_VERSION_transformers(0,5,5)` has proper semantics again)

**Comment by RyanGlScott** [comment]
Any update on this? Now that GHC 8.6.4 has been released, people are filing bug reports against `contravariant` (ekmett/contravariant#60), so it would be good to come up with a resolution to this issue soon.

**Comment by 23Skidoo** [comment]
+1 on @hvr's suggestions.

**Comment by RyanGlScott** [comment]
Ping?

**Comment by 23Skidoo** [comment]
What needs to be done to move this forward? Do we need to contact Ross Paterson (the maintainer of `transformers`)?

**Comment by cartazio** [comment]
THIS seems to be a problem. How do we fix it?
Marking transformers as prefer / pick installed is a fragile fix on the
user side ...

**Comment by cartazio** [comment]
Has anyone contacted ROSS? If not, let’s get that rolling so we can do an
NMU if need be to keep things working

**Comment by RyanGlScott** [comment]
@christiaanb reports that this issue is also affecting `transformers-compat-0.6.3`.

**Comment by RyanGlScott** [comment]
I've just sent an e-mail to Ross asking if he agrees with the course of action in https://github.com/haskell-infra/hackage-trustees/issues/209#issuecomment-460605656.

**Comment by RyanGlScott** [comment]
There is now a `transformers-0.5.5.2` release on Hackage that matches the version of `transformers` that was shipped with GHCs 8.6.1–8.6.3. Moreover, the Hackage releases of `transformers-0.5.5.0` (and `0.5.5.1`, which contained a couple of API-related mistakes) are now blacklisted, so in theory, `cabal` should never pick them in build plans.

As far as I can tell, this fixes all of the issues that people were having with `transformers-compat-0.6.3` and `contravariant-1.5` (I haven't yet heard back from @23Skidoo on https://github.com/ekmett/contravariant/issues/60, but I can't reproduce the issue locally anymore). In light of this, I'll opt to close this issue.
