### ISSUE TITLE
implicit has no version bounds at alll 

### ISSUE THREAD

**Issue by cartazio** [haskell-infra/hackage-trustees#21]
https://hackage.haskell.org/package/implicit

NONE, and people are trying to build it for whatever reason, we should fix that up

**Comment by bergmark** [comment]
@cartazio here's the build matrix, do you want to fix this? http://164.138.31.15/matrix/stamp/implicit-20150412-0039.html

**Comment by gbaz** [comment]
@cartazio ping?

**Comment by cartazio** [comment]
I'm not the maintainer.... Why are you pinging me?

**Comment by gbaz** [comment]
Because as a trustee you can edit the bounds, which is  what @bergmark suggested you tackle?

**Comment by cartazio** [comment]
Ahhhhh.  I'll take a look tomorrow.

**Comment by bergmark** [comment]
We seem to be having some *cough* technical difficulties w/ the matrix builder, but if it get's fixed there are build errors available there http://matrix.hackage.haskell.org/package/implicit

**Comment by hvr** [comment]
*bump*

**Comment by bergmark** [comment]
![screen shot 2015-10-07 at 15 10 23](https://cloud.githubusercontent.com/assets/100681/10338290/959e49e2-6d05-11e5-86cd-51df669a315a.png)
