### ISSUE TITLE
NMU: bytestring-trie

### ISSUE THREAD

**Issue by gwils** [haskell-infra/hackage-trustees#210]
@tmcgilchrist has been asking for a new upload of [bytestring-trie](https://hackage.haskell.org/package/bytestring-trie) for some time, including publicly on the libraries list since October 2018.

Recently Tim [offered to take over the package](https://mail.haskell.org/pipermail/libraries/2019-February/029353.html). For now though, since it looks like the current maintainer [will return](https://mail.haskell.org/pipermail/libraries/2018-October/029142.html), I think a non-maintainer upload (NMU) is a more appropriate course of action.

The first step in the [NMU process](https://github.com/haskell-infra/hackage-trustees/blob/master/policy.md#policyprocedure-2) is to open an issue or email the maintainer, which was done [here](https://mail.haskell.org/pipermail/libraries/2018-October/029140.html)

**Comment by gwils** [comment]
I've just emailed the maintainer Wren Romano, per step 3 of the process. This begins the countdown.

**Comment by gwils** [comment]
I've sent a second email to Wren per trustee policy. In one week (2019-02-52) we will make a non-maintainer upload.

**Comment by phadej** [comment]
@gwils could you make a fork under a hackage-trustees org with a tag you plan to upload

**Comment by wrengr** [comment]
I just pushed a new version, v0.2.5.0, which compiles cleanly on GHC 7.4.1 through 8.6.2: [Hackage](http://hackage.haskell.org/package/bytestring-trie-0.2.5.0), [GitHub](https://github.com/wrengr/bytestring-trie/commit/a90f48ecfcf5ab523818e0c9c9188276f818cab9), [Travis CI](https://travis-ci.org/wrengr/bytestring-trie/builds/498528730).

**Comment by gwils** [comment]
Thanks @wrengr !
Wren beat me to it (and notified me privately) before I went ahead with the NMU.

**Comment by tmcgilchrist** [comment]
Thanks @gwils and thanks @wrengr
