### ISSUE TITLE
hash package can't build atm with recent ghc / cabal

### ISSUE THREAD

**Issue by cartazio** [haskell-infra/hackage-trustees#211]
https://github.com/ekmett/hash

https://matrix.hackage.haskell.org/ng/#/package/hash

**Comment by cartazio** [comment]
https://github.com/ekmett/hash/issues/2

**Comment by RyanGlScott** [comment]
It looks like you have the necessary GitHub / Hackage bits for `hash`, and there are no red entries for `hash` on the Hackage Matrix. Is there anything else that needs to be done from the `hackage-trustees` side?

**Comment by cartazio** [comment]
nope!

**Comment by cartazio** [comment]
i mean, theres still a bunch to do, with maybe @davean helping drive the direction of things for what i should hack on, but yup, all godo :)
