### ISSUE TITLE
language-python needs restricted bounds

### ISSUE THREAD

**Issue by vmchale** [haskell-infra/hackage-trustees#212]
At the very least, the latest release needs tighter bounds on base; see https://matrix.hackage.haskell.org/#/package/language-python

**Comment by hvr** [comment]
I performed a first round of bounds-tightening, but I've still got two open issues I can't figure out yet:

1.

```
src/Language/Python/Version3/Parser/Lexer.x:0:36:
    The function `symbolToken' is applied to 7 arguments,
    but its type `(SrcLocation -> Token) -> Action' has only four
    In the expression: symbolToken SemiColon 1 3 4 3 4 2
    In an equation for `alex_action_79':
        alex_action_79 = symbolToken SemiColon 1 3 4 3 4 2
```

2. The build of `language-python >= 0.4.1 && < 0.5.5` doesn't seem terminate in a reasonable time for GHC >= 7.10; further investigation necessary whether it could terminate if the versions of `alex`/`happy` are bounded to force older versions of alex/happy

**Comment by vmchale** [comment]
I think maybe the `alex` version must be restricted?

**Comment by hvr** [comment]
For the first issue about the 7-arguments, I'm not sure to what; as constraining to below `alex-2.3.1` excludes any install-plans for GHC 7.0; and it seems a bit odd to me that there would be no install-plans whatsover for GHC 7.0 for any release of `language-python` even though there supposedly where for GHC < 7
