### ISSUE TITLE
wai-extra-3.0.25 has an unnecessary revision restricting its upper version bounds on network

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-infra/hackage-trustees#214]
Currently, `wai-extra-3.0.25` has [this revision](http://hackage.haskell.org/package/wai-extra-3.0.25/revisions/):

> * Changed the library component's library dependency on 'network' from
>   
>   ```
>   >=2.6.1.0
>   ```
>   
>   to
>   
>   ```
>   >=2.6.1.0 && <2.9
>   ```

As far as I can tell, this revision is entirely unnecessary. Judging from yesodweb/wai#724, the `wai-extra-3.0.25` release was specifically made to add support for `network-3.*`. Moreover, it's quite possible to build `wai-extra-3.0.25` with `network-3.0.1.0` on all supported versions of GHC, since the following series of commands works without issue:

```
$ cabal get wai-extra-3.0.25 && cd wai-extra-3.0.25/ && for i in {7.10.3,8.0.2,8.2.2,8.4.4,8.6.3}; do cabal new-build -w /opt/ghc/${i}/bin/ghc --allow-newer=network --constraint="network>=3"; done
```

In light of this, can this (seemingly artificial) upper version bound on `network` be relaxed to something more permissive?

**Comment by hvr** [comment]
Good catch! I had to perform hundreds on revisions on `wai-extra` myself as its maintainer failed to do so in a timely matter. Having to reverse engineer bounds retroactively always bears a risk of mistakes sneaking in and it's the reason why we expect responsible maintainers to not omit version bounds in the first place on Hackage.
