### ISSUE TITLE
HPDF needs upper bounds

### ISSUE THREAD

**Issue by nomeata** [haskell-infra/hackage-trustees#218]
Some users of my `tttool` software, who I previously instructed to use `cabal` to build the software (I am now starting to provide static binaries) fell over HPDF not building with newer versions of GHC (because of [`MonadFail`](https://github.com/alpheccar/HPDF/issues/21) and use of old functions from `containers`). Upstream is dormant, and those [who maintain forks](https://github.com/alpheccar/HPDF/pull/23) so far did not agree to take over the package.

I would appreciate if a trustee could put in upper bounds so that https://matrix.hackage.haskell.org/#/package/HPDF is no longer red.

**Comment by hvr** [comment]
I've mostly fixed it up and it should be all green how; however, there's some corner cases I can't fix up via revisions *yet* ...

It's due to improper CPP conditionals such as

```hs
#if __GLASGOW_HASKELL__ >= 710
import qualified Control.Monad.Except as EXC
#else
import qualified Control.Monad.Error as EXC
#endif
```

(which should have been `#if MIN_VERSION_mtl(2,2,1)` instead) and this is e.g. observable via

```
$ cabal v2-repl -zb HPDF==1.4.10  -w ghc-7.10.3 --constraint 'mtl < 2.2.1'
...
Configuring library for HPDF-1.4.10..
Preprocessing library for HPDF-1.4.10..
Building library for HPDF-1.4.10..

Graphics/PDF/Image.hs:49:18:
    Could not find module ‘Control.Monad.Except’
```

**Comment by nomeata** [comment]
Thanks!

**Comment by hvr** [comment]
@nomeata btw, you should take a look at https://matrix.hackage.haskell.org/package/tttool :-)

**Comment by nomeata** [comment]
Ah, thanks!
