### ISSUE TITLE
Relax bounds for rapid 0.1.4

### ISSUE THREAD

**Issue by f-f** [haskell-infra/hackage-trustees#219]
[Here's a PR for this](https://github.com/esoeylemez/rapid/pull/2) in `rapid`'s repo, but sadly:
> Ertugrul Söylemez died unexpectedly on May 12.

The PR is 6 months old, so I believe the correct bounds today would be (note: [as the matrix shows](https://matrix.hackage.haskell.org/#/package/rapid) the current bounds prevent a build plan for GHC 8.4 and 8.6):
```
async >= 2.1 && < 2.3,
base >= 4.8 && < 4.13,
containers >= 0.5 && < 0.7,
foreign-store == 0.2.*,
stm >= 2.4 && < 2.6
```

**Comment by gwils** [comment]
Thanks for reporting this. I've made the revision.

**Comment by f-f** [comment]
Thanks @gwils!
