### ISSUE TITLE
Relax bounds for async-pool 0.9.0.2

### ISSUE THREAD

**Issue by f-f** [haskell-infra/hackage-trustees#229]
As [the matrix shows](https://matrix.hackage.haskell.org/#/package/async-pool), there's no install plan for GHC 8.6, and that is due to the bound `base < 4.12`.

Upstream has been patched in https://github.com/jwiegley/async-pool/pull/13, and there's also another issue open since some time (https://github.com/jwiegley/async-pool/issues/14) to ask for a new revision/release

**Comment by phadej** [comment]
Will do revisions later today. Found problems with lower-bounds, and I'll fix them too.

**Comment by phadej** [comment]
https://hackage.haskell.org/package/async-pool-0.9.0.2/revisions/ done

**Comment by phadej** [comment]
By the way, there was install plan for GHC-8.6, but for `0.9.0` (i.e. not the latest `0.9.0.2` version). There aren't a changelog, so it was a bit difficult to say, whether the changes were essential (I assume there was some kind of a bug fix, as there are some code changes).

So for the future: trustee might be lazy and IMHO justifiably say "wontfix" without more information.

**Comment by f-f** [comment]
Thank you!
