### ISSUE TITLE
wai-middleware-throttle needs upper bounds

### ISSUE THREAD

**Issue by emilypi** [haskell-infra/hackage-trustees#231]
The [wai-middleware-throttle](https://matrix.hackage.haskell.org/#/package/wai-middleware-throttle) package fails to specify any upper bounds, and consistently breaks as a result. I've raised the issue there, and am preemptively filing an issue here at @hvr's request.

It doesn't seem to have an active maintainership.

**Comment by hvr** [comment]
Upstream ticket: https://github.com/creichert/wai-middleware-throttle/issues/21

Btw, this is yet another instance of #207 ; I've quickly fixed the missing bounds for `network` (as well as two cases of missing bounds for `mtl` which caused trouble). 

previous broken state: https://matrix.hackage.haskell.org/package/wai-middleware-throttle@1556599449

new resulting fixed state: https://matrix.hackage.haskell.org/package/wai-middleware-throttle@1560702168

cc @creichert

**Comment by emilypi** [comment]
Thanks @hvr, you're a champion!

**Comment by creichert** [comment]
Thanks @hvr. I'll follow-up on the ticket and code up whatever is needed.

**Comment by creichert** [comment]
Alright, everything is uploaded. Let me know if I need to make any further changes: http://hackage.haskell.org/package/wai-middleware-throttle-0.3.0.1

**Comment by emilypi** [comment]
Thanks @creichert!

**Comment by hvr** [comment]
closing as this appears to have been resolved already
