### ISSUE TITLE
dwarfadt lens bound needs to be relaxed

### ISSUE THREAD

**Issue by mpickering** [haskell-infra/hackage-trustees#233]
https://hackage.haskell.org/package/dwarfadt

The package builds fine for me locally with the `lens` bound relaxed to `< 4.18`

**Comment by phadej** [comment]
Let's give author some time to react...

**Comment by hvr** [comment]
@mpickering I see you interacted with the author after this ticket was filed over at https://github.com/Peaker/dwarfadt/commits/master -- is this ticket still relevant?

**Comment by Bodigrim** [comment]
@mpickering this is all done now, https://matrix.hackage.haskell.org/#/package/dwarfadt
