### ISSUE TITLE
Possible NMU: vector-th-unbox

### ISSUE THREAD

**Issue by phadej** [haskell-infra/hackage-trustees#236]
I contacted liyang on 2019-09-04.

This starts 2 week countdown as 3rd step in https://github.com/haskell-infra/hackage-trustees/blob/master/policy.md#3-source-changes-simple-patches

EDIT: my PR is at https://github.com/liyang/vector-th-unbox/pull/23 but others have made PRs in May 2019: https://github.com/liyang/vector-th-unbox/pull/20 and https://github.com/liyang/vector-th-unbox/pull/19; therefore direct intention to perform NMU.

**Comment by phadej** [comment]
I sent a message to Liyang mentioning that I plan to make a NMU on Monday 2019-09-23

**Comment by phadej** [comment]
Planned version for upload is at https://github.com/hackage-trustees/vector-th-unbox/compare/master...hackage-trustees:ghc-8.8.1-nmu, the very same as in PR (there version is already bumped there, e.g.)

**Comment by hvr** [comment]
Looks good  to me; let's do the NMU at last.

**Comment by peti** [comment]
:+1:

Please do the NMU. `vector-th-unbox` is blocking many useful packages, not least of which is ` monad-par`.

**Comment by RyanGlScott** [comment]
>  I plan to make a NMU on Monday 2019-09-23

What is the status of this?

**Comment by phadej** [comment]
admins granted me upload rights, so here you go: https://hackage.haskell.org/package/vector-th-unbox-0.2.1.7
