### ISSUE TITLE
Bump base bound on vector-binary-instances

### ISSUE THREAD

**Issue by athas** [haskell-infra/hackage-trustees#237]
`vector-binary-instances` could also do with a bump for `base`.  There is an [upstream pull request](https://github.com/bos/vector-binary-instances/pull/18).

**Comment by phadej** [comment]
I pinged @bgamari on it.

**Comment by RyanGlScott** [comment]
The [upstream pull request](https://github.com/bos/vector-binary-instances/pull/18) was merged (and a [revision](http://hackage.haskell.org/package/vector-binary-instances-0.2.5.1/revisions/) was applied), so I believe this can be closed.
