### ISSUE TITLE
Fix unlambda and brainfock for GHC 7.10

### ISSUE THREAD

**Issue by abbradar** [haskell-infra/hackage-trustees#24]
They have no maintainers and need straightforward patches to fix building with GHC 7.10:

https://github.com/NixOS/nixpkgs/blob/6e9a6e57cb9104491aa8d633e5c15edb80ca4c06/pkgs/development/haskell-modules/brainfuck-fix-ghc710.patch
https://github.com/NixOS/nixpkgs/blob/6e9a6e57cb9104491aa8d633e5c15edb80ca4c06/pkgs/development/haskell-modules/unlambda-fix-ghc710.patch

This (among other fixes) is needed to build lambdabot with 7.10.

**Comment by hvr** [comment]
I've just added respective upper bounds on `base` to keep Cabal from running into compile failures. We still need to handle the NMU part though.

From where do you infer those packages have no maintainer?

**Comment by abbradar** [comment]
Well, `Maintainer` field is `None` for both `unlambda` and `brainfuck`.

**Comment by bergmark** [comment]
That should be evidence enough I think :-)

I see no reason why we can't just do an NMU straight away then (but, sorry for my delayed response!)

We can probably do a takeover immediately too, would you be interested in maintaining any of the packages @abbradar?

**Comment by bergmark** [comment]
Here are suggestions for NMU, both compile on GHC 7.0.4 and 7.10.1

https://github.com/hackage-trustees/unlambda/compare/ca97b02...0.1.4
https://github.com/hackage-trustees/brainfuck/compare/cc461e...0.1.0.1

Can a trustee review please?

**Comment by abbradar** [comment]
@bergmark Well, I wanted to get some experience in Hackage package maintenance, and those two look simple enough, so yes, I'm in if you don't mind a newbie taking over them.

**Comment by bergmark** [comment]
Sounds good to me!

I sent an e-mail to @gwern to check if he is okay with a transfer.

**Comment by gwern** [comment]
If you want to start maintaining them, go ahead.

**Comment by bergmark** [comment]
Thanks for letting us know @gwern!

@abbradar what is your hackage user name?

**Comment by abbradar** [comment]
@bergmark "abbradar"

**Comment by bergmark** [comment]
@gwern Can you please add him as a maintainer on hackage?

* http://hackage.haskell.org/package/unlambda/maintainers/edit
* http://hackage.haskell.org/package/brainfuck/maintainers/edit

**Comment by bergmark** [comment]
I noticed it's done, thank you Gwern!

@abbradar If you would like you can use the repositories we added under the hackage-trustees organization. I invited you to a team so you can transfer the repositories to your account. They contain my suggested patches, feel free to do what you want with them.

**Comment by abbradar** [comment]
@bergmark Thanks, I've transferred repositories to my account -- you can remove the team.

**Comment by abbradar** [comment]
For some reason I've thought that the `Maintainer` field should be updated to indicate that I can now upload new version. Uploaded new versions, thanks for the help!

**Comment by bergmark** [comment]
The maintainer field is just whatever is in the Cabal file, you can see the users allowed to upload e.g. here: http://hackage.haskell.org/package/unlambda/maintainers/
