### ISSUE TITLE
bytestring-trie base bump

### ISSUE THREAD

**Issue by bubba** [haskell-infra/hackage-trustees#244]
1) I've tried sending an email and [pull request](https://github.com/wrengr/bytestring-trie/pull/8) last week
2) https://github.com/wrengr/bytestring-trie/pull/8
3) 
4) This is blocking HaRe, which in turn is blocking haskell-ide-engine. We can work around this for now with allow-newer inside our cabal.project, but it would be nice to have this bumped anyway

**Comment by phadej** [comment]
I'll give a maintainer a fair two-week time to respond.

**Comment by phadej** [comment]
revision made: https://hackage.haskell.org/package/bytestring-trie-0.2.5.0/revisions/
