### ISSUE TITLE
jsonschema-gen needs a base dependency bump

### ISSUE THREAD

**Issue by blamario** [haskell-infra/hackage-trustees#247]
The issue has been open since March with no response:

https://github.com/yuga/jsonschema-gen/issues/8

**Comment by phadej** [comment]
how hi you need the `base` to be bumped?

I don't see any PR (i.e. evidence) that relaxation is safe.

**Comment by blamario** [comment]
A PR would not be accepted, do I need to submit one anyway? I have tested it locally with Stackage lts-12.26, which corresponds to base-4.11.1.0 and covers my immediate needs. That being said, I'm reasonably sure it will work with the latest base just fine.

**Comment by blamario** [comment]
Here's the PR: https://github.com/yuga/jsonschema-gen/pull/9
It passes the test suite.

**Comment by phadej** [comment]
https://hackage.haskell.org/package/jsonschema-gen-0.4.1.0/revisions/
