### ISSUE TITLE
bzlib needs update for GHC 8.8

### ISSUE THREAD

**Issue by clinty** [haskell-infra/hackage-trustees#249]
Attempted to contact dcoutts on IRC on Nov. 26 and Nov. 27.  Emailed a patch to duncan@community.haskell.org on Nov. 28, but this bounced.

(The patch moved fail to a MonadFail instance and changed lower bound on base to 4.9)

The current situation means that 20 immediate reverse dependencies are unbuildable with GHC 8.8.

**Comment by vmchale** [comment]
If they're your packages I am now willing to suggest [bz2](http://hackage.haskell.org/package/bz2) as a replacement.

**Comment by clinty** [comment]
Already switched mine

**Comment by RyanGlScott** [comment]
I believe this has been resolved with [`bzlib-0.5.1.0`](http://hackage.haskell.org/package/bzlib-0.5.1.0)'s upload to Hackage?

**Comment by phadej** [comment]
@RyanGlScott thanks for a ping, closing...
