### ISSUE TITLE
Bump base bound for fused-effects 0.1.2.1

### ISSUE THREAD

**Issue by athas** [haskell-infra/hackage-trustees#250]
I would like to have the `base` <4.13 bound on [fused-effects 0.1.2.1](http://hackage.haskell.org/package/fused-effects-0.1.2.1) bumped to <4.14.  I have verified that `fused-effects` works with this version of `base`. While this version of `fused-effects` is a year old and newer versions don't have this restrictive bound, I'm looking to compile a program ([komposition](https://github.com/owickstrom/komposition)) that does not work with newer versions of `fused-effects`, and where updating is nontrivial.

**Comment by phadej** [comment]
Please contract the maintainers first, AFAIK they are responsive.

**Comment by athas** [comment]
[Handled upstream](https://github.com/fused-effects/fused-effects/issues/336#event-2911314455).
