### ISSUE TITLE
unix-compat needs update to work with ghc-8.8.1 on windows

### ISSUE THREAD

**Issue by jneira** [haskell-infra/hackage-trustees#251]
Hi, 
* `unix-compat`cant be built with ghc-8.8.1 on windows due its bounds over `time` package.
* There is a existing pr which only relax the upper bound over `time`: https://github.com/jacobstanley/unix-compat/pull/42
  * The pr was opened on May 1
* Tha package is widely used, it has 79 dependencies at first level: https://packdeps.haskellers.com/reverse/unix-compat

Thanks in advance

**Comment by jneira** [comment]
Any update on this? does it need more info?

**Comment by gwils** [comment]
closed by https://github.com/jacobstanley/unix-compat/pull/42
