### ISSUE TITLE
bloomfilter-redis needs an update of upper bounds

### ISSUE THREAD

**Issue by Bodigrim** [haskell-infra/hackage-trustees#252]
[`bloomfilter-redis`](http://hackage.haskell.org/package/bloomfilter-redis) cannot be built against latest `base-4.13`, `arithmoi-0.10` and `QuickCheck-2.13` because of tight upper bounds. I've prepared a relevant [PR](https://github.com/hesiod/bloomfilter-redis/pull/2) back in November, but got no response. Nothing urgent however, because there are no dependents on Hackage.

**Comment by phadej** [comment]
The PR has red travis, neither include jobs for newer dependencies. I'm hesitant to relax bounds without better evidence.

**Comment by Bodigrim** [comment]
Understood, fair point. I do not intend to push this further, so closing the issue to get it off the radar
