### ISSUE TITLE
MissingH-1.4.2.0 base bump

### ISSUE THREAD

**Issue by clkamp** [haskell-infra/hackage-trustees#253]
It builds fine on GHC 8.8 with the `base` bound relaxed to `< 4.14` and there is also an open pull request on this since end of november (haskell-hvr/missingh#51)
Could we please have this bound relaxed?

**Comment by phadej** [comment]
That PR doesn't seem to include CI jobs for newer GHC (and maybe at this point it's worth adding GHC-8.10 support and job too).

**Comment by hvr** [comment]
I consider this to have become obsoleted by https://hackage.haskell.org/package/MissingH-1.4.3.0
