### ISSUE TITLE
Update to bounds needed on amazonka package

### ISSUE THREAD

**Issue by newhoggy** [haskell-infra/hackage-trustees#256]
Add an upper bound to `unliftio-core-1.6.1`

```
unliftio-core                  >= 0.1    && < 0.2
```

This is required to avoid this error:

```
src/Control/Monad/Trans/AWS.hs:245:5: error:
    ‘askUnliftIO’ is not a (visible) method of class ‘MonadUnliftIO’
    |
245 |     askUnliftIO = AWST' $ (\(UnliftIO f) -> UnliftIO $ f . unAWST)
    |     ^^^^^^^^^^^
```

**Comment by newhoggy** [comment]
Workaround for downstream projects, but this is not ideal:

https://github.com/haskell-works/cabal-cache/pull/110/files

**Comment by phadej** [comment]
I made a revision https://hackage.haskell.org/package/amazonka-1.6.1/revisions/

Please open a upstream issue in https://github.com/brendanhay/amazonka/issues

**Comment by newhoggy** [comment]
https://github.com/brendanhay/amazonka/issues/568

**Comment by phadej** [comment]
@newhoggy thanks. Commented there.
