### ISSUE TITLE
Bump bound on base for polyparse

### ISSUE THREAD

**Issue by vmchale** [haskell-infra/hackage-trustees#259]
[polyparse](http://hackage.haskell.org/package/polyparse) builds with GHC 8.10.1 and its base bound can be relaxed

Thanks!

**Comment by asr** [comment]
Blocking https://github.com/agda/agda/issues/4242.

**Comment by ndmitchell** [comment]
Blocking https://github.com/ndmitchell/hlint/issues/942.

**Comment by phadej** [comment]
https://hackage.haskell.org/package/polyparse-1.13/revisions/
