### ISSUE TITLE
bed-and-breakfast

### ISSUE THREAD

**Issue by bergmark** [haskell-infra/hackage-trustees#26]
Mike Meyer wants to take over bed-and-breakfast, e-mail to libraries was sent 2015-04-15. Recording it here so it's not forgotten.

https://mail.haskell.org/pipermail/libraries/2015-April/025477.html

**Comment by bergmark** [comment]
I've also restricted versions `>= 0.1.3 && <= 0..4.3` to `base < 4.7`.

**Comment by bergmark** [comment]
@mwm it has been more than 2 weeks now, so please email admin@hackage.org about the takeover.

**Comment by mwm** [comment]
I got a note from julian that he's planning on updating it soon.

**Comment by bergmark** [comment]
Ok, good! I'll close this then, let me know if it should be re-opened.
