### ISSUE TITLE
Bump bounds on base on text-format project

### ISSUE THREAD

**Issue by newhoggy** [haskell-infra/hackage-trustees#264]
The `text-format` repository looks unmaintained.  There are issues from 2018 related to `ghc-8.4` that have not been addressed.  Also confused as to why there is a `text-format-0.3.2` that does not exist in the Github repository.

https://github.com/bos/text-format

In any case, I've confirmed that `text-format-0.3.2` will build with a bump on the bounds on `base`.  Can that be arranged?

This is required to build `ede` and transitively `amazonka`.

**Comment by phadej** [comment]
Will do. But better longer term solution would be migrate to https://hackage.haskell.org/package/fmt or https://hackage.haskell.org/package/formatting which seems to be maintained

**Comment by phadej** [comment]
Done

**Comment by newhoggy** [comment]
Thanks!
