### ISSUE TITLE
primitive-0.7.1–related build failures

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-infra/hackage-trustees#269]
These Hackage libraries fail to build against `primitive-0.7.1`:

* `scheduler-1.4.2.2`:

  ```
  [4 of 4] Compiling Control.Scheduler ( src/Control/Scheduler.hs, dist/build/Control/Scheduler.o, dist/build/Control/Scheduler.dyn_o )
  
  src/Control/Scheduler.hs:103:30: error:
      Ambiguous occurrence ‘arrayFromListN’
      It could refer to
         either ‘Data.Primitive.Array.arrayFromListN’,
                imported from ‘Data.Primitive.Array’ at src/Control/Scheduler.hs:78:1-27
             or ‘Control.Scheduler.arrayFromListN’,
                defined at src/Control/Scheduler.hs:109:1
      |
  103 |       , _workerStatesArray = arrayFromListN nWorkers workerStates
      |                              ^^^^^^^^^^^^^^
  ```
  
  See also lehins/haskell-scheduler#9.

* `streamly-0.7.2`:

  ```
  [56 of 71] Compiling Streamly.Internal.Data.Array ( src/Streamly/Internal/Data/Array.hs, dist/build/Streamly/Internal/Data/Array.o, dist/build/Streamly/Internal/Data/Array.dyn_o )
  
  src/Streamly/Internal/Data/Array.hs:163:10: error:
      Duplicate instance declarations:
        instance NFData a => NFData (Array a)
          -- Defined at src/Streamly/Internal/Data/Array.hs:163:10
        instance NFData a => NFData (Array a)
          -- Defined in ‘Data.Primitive.Array’
      |
  163 | instance NFData a => NFData (Array a) where
      |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
  
  See also composewell/streamly#562.

**Comment by RyanGlScott** [comment]
It looks like:

* [`scheduler-1.4.0`](http://hackage.haskell.org/package/scheduler-1.4.0/revisions/)
* [`scheduler-1.4.1`](http://hackage.haskell.org/package/scheduler-1.4.1/revisions/)
* [`scheduler-1.4.2`](http://hackage.haskell.org/package/scheduler-1.4.2/revisions/)
* [`scheduler-1.4.2.1`](http://hackage.haskell.org/package/scheduler-1.4.2.1/revisions/)
* [`scheduler-1.4.2.2`](http://hackage.haskell.org/package/scheduler-1.4.2.2/revisions/)
* [`streamly-0.7.1`](http://hackage.haskell.org/package/streamly-0.7.1/revisions/)
* [`streamly-0.7.2`](http://hackage.haskell.org/package/streamly-0.7.2/revisions/)

Have been revised accordingly. I have not checked to see if other Hackage releases are affected.

**Comment by lehins** [comment]
@RyanGlScott other releases of `scheduler` aren't affected since they don't depend on `primitive`. I am preparing a fixed version of scheduler and will upload in on Hackage shortly.

**Comment by pranaysashank** [comment]
Same is the case with `streamly`, other releases don't depend on `primitive`.

**Comment by RyanGlScott** [comment]
Thanks all! I think this issue can be closed, then. If there are other libraries affected by `primitive-0.7.1` that I missed, feel free to re-open this.

**Comment by phadej** [comment]
@lehins and @pranaysashank thanks for making revisions!
