### ISSUE TITLE
Relax base bounds on data-tree-print

### ISSUE THREAD

**Issue by bubba** [haskell-infra/hackage-trustees#274]
It builds fine with ghc-8.10.1 (base 4.15) https://hackage.haskell.org/package/data-tree-print

**Comment by bubba** [comment]
PR for update https://github.com/lspitzner/data-tree-print/pull/2

**Comment by LightAndLight** [comment]
bump

**Comment by endgame** [comment]
This is done, but I don't have the permission to close issues.

**Comment by gbaz** [comment]
ok
