### ISSUE TITLE
Missing GHC 8.10.2 libraries

### ISSUE THREAD

**Issue by tfausak** [haskell-infra/hackage-trustees#276]
https://www.haskell.org/ghc/download_ghc_8_10_2.html

- [x] [Cabal-3.2.0.0](https://hackage.haskell.org/package/Cabal-3.2.0.0)
- [x] [array-0.5.4.0](https://hackage.haskell.org/package/array-0.5.4.0)
- [x] [base-4.14.1.0](https://hackage.haskell.org/package/base-4.14.1.0)
- [x] [ghc-8.10.2](https://hackage.haskell.org/package/ghc-8.10.2)
- [ ] [ghc-boot-8.10.2](https://hackage.haskell.org/package/ghc-boot-8.10.2)
- [x] [ghc-boot-th-8.10.2](https://hackage.haskell.org/package/ghc-boot-th-8.10.2)
- [x] [ghci-8.10.2](https://hackage.haskell.org/package/ghci-8.10.2)
- [x] [haskeline-0.8.0.1](https://hackage.haskell.org/package/haskeline-0.8.0.1)
- [ ] [hpc-0.6.1.0](https://hackage.haskell.org/package/hpc-0.6.1.0)

#240, #203, #192, #179, #160, #153, #141

**Comment by rikvdkleij** [comment]
Any prediction when missing libraries are on Hackage?

**Comment by expipiplus1** [comment]
@tfausak looks like base has been updated.

**Comment by andreasabel** [comment]
Why doesn't the GHC team upload these when they release GHC?

**Comment by Bodigrim** [comment]
@tfausak could you possibly elaborate why this is raised in Hackage Trustees issue tracker instead of respective trackers of `ghc-boot` and `hpc`?

**Comment by tfausak** [comment]
https://github.com/haskell-infra/hackage-trustees/issues/141#issuecomment-371896767

**Comment by Bodigrim** [comment]
@tfausak please raise these issues at GHC bug tracker, I don't think this bug tracker is relevant for them any longer.

**Comment by tfausak** [comment]
Noted. However you'll notice that the latest `ghc` library on Hackage is 8.10.2. I haven't checked all the other included libraries, but I suspect many of them are missing. I gave up on reporting these because it seemed to happen every time, nothing was done about it, and help wasn't accepted.

**Comment by Bodigrim** [comment]
I understand your frustration, but unfortunately there is little I can help with here. My understanding is that some libraries are now uploaded automatically (see https://gitlab.haskell.org/ghc/ghc/-/issues/19632 and https://gitlab.haskell.org/bgamari/ghc-utils/-/blob/master/rel-eng/upload_ghc_libs.py), not sure why `ghc` itself is not on the list.

**Comment by sjakobi** [comment]
https://gitlab.haskell.org/ghc/ghc/-/issues/20236 is related.
