### ISSUE TITLE
HaXml Duration output is invalid

### ISSUE THREAD

**Issue by dten** [haskell-infra/hackage-trustees#278]
https://hackage.haskell.org/package/HaXml-1.25.5/docs/src/Text.XML.HaXml.Schema.PrimitiveTypes.html#line-140

it's parsing the duration `PT30M` and outputting `0Y0M0DT0H30M0.0S` which whilst being full of extra 0's is also invalid because it's missing the `P` which signifies it is a Period not a DateTime

**Comment by phadej** [comment]
Thanks for a report.

`HaXml` is not maintained, it is on a life-support. I'm hesitant to even review any functionality changing patches, and thus making Hackage Trustees de-facto maintainers of HaXml. If you are using `HaXml` and want to see it maintained, please take it over.

**Comment by dten** [comment]
Understandable.

The most interesting thing for me is generating the parser/serialiser from a xsl, which doesn't seem to be a thing that exists elsewhere.

By the way I think the fix is just add `"P"++`  before `show y`

It's definitely a bug also

I have thought about doing some PRs but am also reluctant to take on maintenance 😓

**Comment by Bodigrim** [comment]
@dten I very much suggest people to migrate away from `HaXml`, unless they are willing to take on maintenance. The package has been essentially abandoned 4 years ago, that's enough time to switch to something else. Hackage Trustees cannot support it forever. Doing NMUs for `HaXml` encourages people to use it further, which is quite an opposite direction to what I wish to happen.

**Comment by Bodigrim** [comment]
@dten please raise an issue at https://github.com/HaXml/HaXml
