### ISSUE TITLE
pred-trie needs base >= 4.8

### ISSUE THREAD

**Issue by bergmark** [haskell-infra/hackage-trustees#28]
![screen shot 2015-04-25 at 17 10 25](https://cloud.githubusercontent.com/assets/100681/7333378/15cdeef2-eb6e-11e4-99d9-b5a633637e68.png)

**Comment by bergmark** [comment]
![screen shot 2015-04-25 at 17 16 55](https://cloud.githubusercontent.com/assets/100681/7333398/e849dba2-eb6e-11e4-9468-a3fc4abe5476.png)

**Comment by bergmark** [comment]
@athanclark I've restricted all versions to require `base >= 4.8` with new revisions on hackage. I recommend you add that constraint in the repository or work on backwards compatibility. The errors were because `<$>` and others were not in `Prelude` before GHC 7.10.

**Comment by athanclark** [comment]
Thank you @bergmark. The package still isn't quite finished, still in development phase - as soon as v1 comes around I'll try to push compiler compatibility, too.

**Comment by bergmark** [comment]
You're welcome! Hack on
