### ISSUE TITLE
polyparse doesn't install with ghc 9.0 unless you use --allow-new

### ISSUE THREAD

**Issue by GeorgeCo** [haskell-infra/hackage-trustees#281]
Hi

I know this is just 9.0 alpha but polyparse does't compile unless you add --allow-new. Can you release a new version that will install with ghc 9.0? A lot of packages depend on polyparse, Cabal in particular.

Thanks
George

**Comment by GeorgeCo** [comment]
ghc 9.0.1 is released. polyparse doesn't install. Can this be fixed asap?

**Comment by sjakobi** [comment]
@phadej took care of the `base` bounds: http://hackage.haskell.org/package/polyparse-1.13/revisions/

**Comment by andreasabel** [comment]
I think this issue can be closed, see https://github.com/hackage-trustees/malcolm-wallace-universe/issues/7.

**Comment by gbaz** [comment]
closing as per discussion
