### ISSUE TITLE
PRs to the text library are ignored

### ISSUE THREAD

**Issue by ethercrow** [haskell-infra/hackage-trustees#283]
Dear hackage trustees

I made some PRs to the text library that make encoding and decoding utf8 faster on x86_64 hardware. I think that it would be useful to many people running Haskell services in production.

However, these PRs don't get feedback for more than a month already. Since `text` lives in the github.com/haskell organization there is no clear single owner person. Please advise.

PR links:
https://github.com/haskell/text/pull/300
https://github.com/haskell/text/pull/298
https://github.com/haskell/text/pull/297

cc @phadej @hvr

**Comment by sjakobi** [comment]
Indeed it would be good if `text` had more active maintainers. @chessai recently brought this up in [this email](https://mail.haskell.org/pipermail/libraries/2020-November/030934.html) on the libraries mailing list.

**Comment by ethercrow** [comment]
Monthly bump

**Comment by Bodigrim** [comment]
@ethercrow while I can understand the frustration, stalled PRs seem to be [out of scope](https://github.com/haskell-infra/hackage-trustees/blob/master/policy.md) of Hackage Trustees. It could be more productive to raise this matter on [the libraries maillist](https://mail.haskell.org/cgi-bin/mailman/listinfo/libraries).

**Comment by Bodigrim** [comment]
PRs in question has been merged, this can be closed now.
