### ISSUE TITLE
basement does not build under GHC 9.0, PRs with fixes are ignored

### ISSUE THREAD

**Issue by ethercrow** [haskell-infra/hackage-trustees#284]
`basement` and `foundation` libraries have quite many reverse dependencies, e.g. via `cryptonite` and `http-client-tls` or `gauge`. However, they seem abandoned, there was only one commit in 2020, PRs and issues are ignored.

PRs with fixes for GHC 9.0:
https://github.com/haskell-foundation/foundation/pull/540 by @utdemir
https://github.com/haskell-foundation/foundation/pull/537 by @sgraf812
https://github.com/haskell-foundation/foundation/pull/535 by @andrewthad

**Comment by sgraf812** [comment]
Summoning the owner @vincenthz to be part of the discussion

**Comment by phadej** [comment]
Is GHC-9.0 released already?

**Comment by expipiplus1** [comment]
Might be worth pinging all the people on this page https://github.com/haskell-foundation

**Comment by expipiplus1** [comment]
I emailed @vincenthz about this about a week ago and didn't get a reply.

**Comment by Bodigrim** [comment]
(Could this be a lesson to learn about custom preludes?..)

**Comment by vincenthz** [comment]
PR and issues on unreleased ghc is not my concerns anymore, this will wait until I can get 9.0 on my system (apparently 9.0 release today ..).

@Bodigrim what about a lesson for ghc in not breaking core APIs gratuitously (even "internal APIs") ?

**Comment by bergmark** [comment]
I think it's fair if maintainers want to wait with releases until a new GHC ships. Since this requires actual code changes I don't think it would be appropriate for us trustees to go against the maintainers wishes and perform a non-maintainer upload.

**Comment by bergmark** [comment]
I'm cleaning up the issue tracker a bit so I'll close this nothing that GHC 9 is out now, and hoping this will get sorted without trustee involvement.

**Comment by mightybyte** [comment]
FWIW, I agree with @vincenthz.  It's unreasonable to expect maintainers to make changes to their packages to accommodate unreleased GHC versions and not something that trustees should deal with.  If you want to live on the bleeding edge, you're gonna have to put in some work to do so.

**Comment by ethercrow** [comment]
> FWIW, I agree with @vincenthz. It's unreasonable to expect maintainers to make changes to their packages to accommodate unreleased GHC versions and not something that trustees should deal with. If you want to live on the bleeding edge, you're gonna have to put in some work to do so.

I created this issue because the bleeding edge people have already done most of the work in those PRs and there was not even an acknowledgement. Contrast it with the situation in hashable: https://github.com/haskell-unordered-containers/hashable/pull/189#issuecomment-675891453. A maintainer said that he'll look at it when GHC 9.0 is closer to release, it was completely fine.

**Comment by bergmark** [comment]
@ethercrow I don't think it's fair to expect a maintainer to respond to every issue filed, what you should expect is what is available at https://github.com/haskell-foundation/foundation/blob/master/LICENSE, everything else is gravy.

This probably sounds rude, but that's not my intention! Vincent has done tons of work for the community and anyone using his libraries ought to be thankful. At least that's what I think.

if we turn complaints into cheers I think we will have a much better outcome.
