### ISSUE TITLE
Help me abandon cryptsy-api

### ISSUE THREAD

**Issue by stephen-smith** [haskell-infra/hackage-trustees#286]
I no longer want cryptsy-api on my personal RSS feed: http://packdeps.haskellers.com/feed/bss@iguanasuicide.net

I'm listed as a maintainer on the package metadata, but I am forbidden from making changes to the package, even after logging in to Hackage.

Honestly, this package can be safely removed -- it connects to a propietary API for a company that hasn't existed for many years.  But, if it can't / won't be removed, it should have all the deprecated / abandoned / do-not-use bits that hackage has set on it.

https://www.reddit.com/r/haskellquestions/comments/k36g2x/how_to_abandon_a_package_on_hackage/

https://www.reddit.com/r/haskell/comments/k3rl4r/how_to_abandon_a_package_on_hackage/

**Comment by endgame** [comment]
From the reddit thread, it sounds like you removed yourself from the maintainer group on Hackage, and now can't get back in. I don't have the permissions to fix that; you might need to ask a Hackage admin. I do have permissions to set the "deprecated" flag on the `cryptsy-api` package, however, and have done so.

Hopefully one of the other trustees will be able to put you in touch with someone who can restore your maintainer access.

**Comment by gbaz** [comment]
i've edited the maintainer in the cabal metadata of the latest version to [none]. hopefully that suffices?

**Comment by stephen-smith** [comment]
Yes.  Worked great.  Thank you very much.
