### ISSUE TITLE
Bump `bytestring` bound on package `hashable`

### ISSUE THREAD

**Issue by chessai** [haskell-infra/hackage-trustees#287]
`bytestring` release hit 0.11.x, so the bound needs to be bumped from `< 0.11` to `< 0.12`

Maintainer was contacted on this issue: https://github.com/tibbe/hashable/pull/191 (October 11th)

A lot of packages depend on `hashable`, so anybody wanting to use the new bytestring will have to override hashable (either via cabal.project or stack or nix). `hashable` has 892 _direct_ reverse dependencies on hackage, bytestring has 5922. They are both probably depended on in almost every production codebase out there. Because of that, I think it would be best to make a revision now instead of waiting.

**Comment by gbaz** [comment]
done.
