### ISSUE TITLE
Bump bytestring bound in parsec

### ISSUE THREAD

**Issue by Bodigrim** [haskell-infra/hackage-trustees#288]
Maintainer was contacted on this issue: https://github.com/haskell/parsec/pull/116 (September 10th), and reminded about it 10 days ago.

Similar to #287, there are [almost 1000 packages](https://packdeps.haskellers.com/reverse/parsec), depending on `parsec`, so almost anybody wanting to use `bytestring-0.11` will have to throw `--allow-newer`. Besides this, `parsec` is a boot package. I think it's desirable to fix this matter with a revision instead of waiting for a new release.

CC @gbaz @chessai

**Comment by chessai** [comment]
@Bodigrim I merged the PR out of convenience to users/maintainers (nonsensical to leave it open) but CLC does not own parsec, so I can't do anything else/more complicated

**Comment by gbaz** [comment]
I made a revision to bump the upper bounds.

**Comment by Bodigrim** [comment]
Thanks @gbaz @chessai!
