### ISSUE TITLE
Bump base bound in cryptohash-sha512

### ISSUE THREAD

**Issue by sjakobi** [haskell-infra/hackage-trustees#289]
https://github.com/haskell-hvr/cryptohash-sha512/pull/5 has been open since 2020-05-27. hvr, the maintainer, was pinged multiple times in the comments.

`cryptohash-sha512` is used in the `hnix` ecosystem via [`hnix-store-core`](https://packdeps.haskellers.com/reverse/hnix-store-core). I'm affected via `dhall-nix` and `dhall-nixpkgs`.

**Comment by endgame** [comment]
Are the other `cryptohash-*` packages similarly affected, and similarly fixed by a revision? If you can prepare PRs for the others, I'll do them in a batch. I'll do `cryptohash-sha512` now.

**Comment by endgame** [comment]
Revision has been published. I'd be grateful if you can check up on the other cryptohash packages if you get a chance.

**Comment by sjakobi** [comment]
@endgame Many thanks for the quick revision! :)

According to https://packdeps.haskellers.com/feed?needle=cryptohash multiple `cryptohash-*` packages are incompatible with the latest `bytestring` and `base16-bytestring` releases. These issues are less pressing for me though, so I'll wait and see whether the maintainers take care of them themselves.

**Comment by phadej** [comment]
`bytestring-0.11` (and iirc `base16-`) need code changes.

**Comment by endgame** [comment]
Thanks @sjakobi @phadej . I was hoping they'd be easy and I could do them all while I was in the area. Alas not.
