### ISSUE TITLE
QuickCheck-2.14.1 needs revision.

### ISSUE THREAD

**Issue by phadej** [haskell-infra/hackage-trustees#290]
See upstream issue https://github.com/nick8325/quickcheck/issues/326

**Comment by phadej** [comment]
GHC-9.0 is now released, so the "red cell" materialized.

**Comment by endgame** [comment]
To clarify: you want the upper bounds on the PR applied to v2.14.1 on Hackage?

**Comment by phadej** [comment]
```
                   9.0.1  8.10.3  8.8.4  8.6.5  8.4.4  8.2.2  8.0.2  7.10.3  7.8.4  7.6.3  7.4.2  7.2.2  7.0.4
QuickCheck-2.14.2  OK     OK      OK     OK     OK     OK     OK     OK      OK     OK     OK     OK     OK   
QuickCheck-2.14.1  FAIL   OK      OK     OK     OK     OK     OK     OK      OK     OK     OK     OK     OK   
QuickCheck-2.14    NO-IP  OK      OK     OK     OK     OK     OK     OK      OK     OK     OK     OK     OK   
QuickCheck-2.13.2  NO-IP  OK      OK     OK     OK     OK     OK     OK      OK     OK     OK     OK     OK   
QuickCheck-2.13.1  NO-IP  NO-IP   NO-IP  OK     OK     OK     OK     OK      OK     OK     OK     OK     OK   
```

**Comment by endgame** [comment]
I'm going to take that as a "yes, only revise 2.14.1". Correct me if I'm wrong.

I'm not trying to be dense here, but most of my trustee work so far has been onboarding new uploaders, not helping with bounds.

**Comment by phadej** [comment]
Someone should onboard new trustees it seems :)

**Comment by phadej** [comment]
But yes, I think making a revision for 2.14.1 is enough. However, don't trust me. I should trust you, you are a trustee ;)

**Comment by endgame** [comment]
Appreciate the assistance. The revision has been published.
