### ISSUE TITLE
Bytestring-trie needs a bumped upper bound on base.

### ISSUE THREAD

**Issue by tmcgilchrist** [haskell-infra/hackage-trustees#291]
I've tried a few times to contact the maintainer, PR fixing bounds with 8.10 build https://github.com/wrengr/bytestring-trie/pull/11

Could I get a meta-data bump on base inline with the PR. Cheers!

**Comment by phadej** [comment]
It cannot be relaxed, it will break older GHC builds.

```
% cabal build -w ghc-7.10.3 --allow-newer=bytestring --constraint='bytestring >=0.11'

...

Preprocessing library for bytestring-trie-0.2.5.0..
Building library for bytestring-trie-0.2.5.0..
[1 of 6] Compiling Data.Trie.ByteStringInternal ( src/Data/Trie/ByteStringInternal.hs, /codetmp/bytestring-trie-0.2.5.0/dist-newstyle/build/x86_64-linux/ghc-7.10.3/bytestring-trie-0.2.5.0/build/Data/Trie/ByteStringInternal.o )

src/Data/Trie/ByteStringInternal.hs:21:34:
    Module ‘Data.ByteString.Internal’ does not export ‘ByteString(PS)’
```

**Comment by tmcgilchrist** [comment]
Right, sounds like a need a new release then. 
Is there an option for doing that? I've had the original issue open for some time without a response from the maintainer. @phadej

**Comment by phadej** [comment]
https://github.com/haskell-infra/hackage-trustees/blob/master/policy.md#3-source-changes-simple-patches

**Comment by tmcgilchrist** [comment]
Thanks @phadej I'll start that process.

**Comment by Bodigrim** [comment]
> It cannot be relaxed, it will break older GHC builds.

https://github.com/wrengr/bytestring-trie/pull/11 relaxes `base` bound only, while `bytestring` remains `< 0.11`.

**Comment by gbaz** [comment]
revision published.
