### ISSUE TITLE
HaXml bounds for random

### ISSUE THREAD

**Issue by lehins** [haskell-infra/hackage-trustees#292]
I was hoping I could ping hackage trustees in order to get some attention to this issue: hackage-trustees/malcolm-wallace-universe#6 

All HaXml needs is a revision.

It is one of the blockers for getting random on stackage: commercialhaskell/stackage#5474

**Comment by sjakobi** [comment]
@phadej has addressed this: http://hackage.haskell.org/package/HaXml-1.25.5/revisions/

This issue can be closed now.

**Comment by phadej** [comment]
@sjakobi I invited you to this repository. Maybe someone with more bits could invite you to the org, but for now this repo should be sufficient, I hope.

**Comment by sjakobi** [comment]
Thanks for the invitation @phadej! I've received the email but I somehow can't accept it. GitHub says:

> Sorry, we couldn't find that repository invitation. It is possible that the invitation was revoked or that you are not logged into the invited account.

**Comment by gbaz** [comment]
Based on above I think this can be closed? Reopen if I misunderstood...
