### ISSUE TITLE
windns requres bounds revision.

### ISSUE THREAD

**Issue by AndreasPK** [haskell-infra/hackage-trustees#293]
windns currently doesn't build with ghc-8.10. As a consequence neither does cabal.

I've opened an issue here over a year ago : https://github.com/haskell-hvr/windns/issues/1

Here is the corresponding cabal ticket: https://github.com/haskell/cabal/issues/7003

Bounds should be at least `base       >= 4.5.1.0 && < 4.15`

It does also seem to work fine with the ghc-9 release candidate. So bumping to `base       >= 4.5.1.0 && < 4.17` probably makes more sense.

**Comment by phadej** [comment]
4.17 or 4.16?

**Comment by AndreasPK** [comment]
4.16, for some reason I had assumed 9.0 would use 4.16 but it's 4.15.

So <4.16 should make it work for ghc-9.0 as well.

**Comment by phadej** [comment]
@hvr added me as co-maintainer, I'll take a look at my PR once GHC-9.0 and cabal-install-3.4 are available in chocolatey. (I.e. hopefully soon enough).

**Comment by gbaz** [comment]
bump?

**Comment by endgame** [comment]
Since haskell-hvr/windns#2 revises bounds for both `base` and `bytestring` without changing any code, I have used trustee powers to do the same to `windns-0.1.0.1`.
