### ISSUE TITLE
test-framework and test-framework-quickcheck2 need revisions

### ISSUE THREAD

**Issue by sjakobi** [haskell-infra/hackage-trustees#294]
The following bounds need to be bumped:

* `test-framework`:
  * `ansi-terminal`: https://github.com/haskell/test-framework/pull/54
  * `QuickCheck`: https://github.com/haskell/test-framework/pull/52
  * `random`: https://github.com/haskell/test-framework/pull/53
  * `time`: https://github.com/haskell/test-framework/pull/57
* `test-framework-quickcheck2`:
  * `random`: https://github.com/haskell/test-framework/pull/53

@hvr, who made the latest uploads, apparently intended (https://github.com/haskell/test-framework/pull/53#event-3744066298) to address the `random` incompatibility but didn't follow up.

**Comment by bergmark** [comment]
test-framework: http://hackage.haskell.org/package/test-framework-0.8.2.0/revisions/
test-framework-quickcheck2: http://hackage.haskell.org/package/test-framework-quickcheck2-0.3.0.5/revisions/

**Comment by sjakobi** [comment]
Thanks a lot, @bergmark! :)
