### ISSUE TITLE
asn1-encoding needs bump on bytestring bound

### ISSUE THREAD

**Issue by sjakobi** [haskell-infra/hackage-trustees#295]
See https://github.com/vincenthz/hs-asn1/issues/42.

`asn1-encoding` is used by many packages via `http-client-tls` and `tls`.

**Comment by bergmark** [comment]
I'll echo my response on that issue. I wasn't able to find any information of why this upper bound was introduced so I reverted it.

**Comment by sjakobi** [comment]
Thank you, @bergmark! :)
