### ISSUE TITLE
A number of HVR's packages need NMU's

### ISSUE THREAD

**Issue by emilypi** [haskell-infra/hackage-trustees#297]
Hi all, the following packages need to be bumped to unblock a large number of packages. We've been trying to reach HVR for over 3 months and it seems life has taken over and he has been somewhat responsive (e.g. with cryptohash-sha256), but not been as responsive as we need in order to move things along. 

We need to coordinate some NMU's. The following packages need help: 

- `regex-posix` has had an open PR and multiple pings over months here: https://github.com/haskell-hvr/regex-posix/pull/8. HVR has not responded when prompted about this. 
- `regex-tdfa` has the same deal, PR outstanding here: https://github.com/haskell-hvr/regex-tdfa/pull/17
- `regex-base` has the same here: https://github.com/haskell-hvr/regex-base/pull/8 and here: https://github.com/haskell-hvr/regex-base/pull/10, with relevant issues here: https://github.com/haskell-hvr/regex-base/issues/7 and here: https://github.com/haskell-hvr/regex-base/issues/9
- `text-short` has been out of date for close to 4 months. I logged an issue here: https://github.com/emilypi/base64/issues/30, and submitted the fix to HVR here: https://github.com/haskell-hvr/text-short/pull/19, and asked for + was granted co-maintenance via email. However, he has not granted Hackage maintainership priveleges yet. 
- `uuid` and `uuid-types` are roughly 3 years behind on their releases: https://github.com/haskell-hvr/uuid/issues/46, and @bodigrim + @lehins have done the work to bring the package up to date with no visible response. 

There may be more on to this list, but I'd like to get started planning and tracking for these ASAP per the NMU policy. 

-----

# Progress: 

### Maintenance 

- [x] `regex-posix` - maintainers added
- [x] `regex-base` - maintainers added
- [x] `regex-tdfa` - maintainers added
- [x] `text-short` - co-maintainer added
- [x] `uuid` - taken over by @phadej 
- [x] `uuid-types` - taken over by @phadej 
- [x] `zlib` - co-maintainers added
- [x] `tar` - co-maintainers added 

### Needed Revisions/Releases: 

- [x] `regex-posix` 
- [x] `regex-base`
- [x] `regex-tdfa` 
- [x] `text-short` - @hvr has revised bounds 
- [x] `uuid`  - @phadej has done a release
- [x] `uuid-types` - @phadej has done a release
- [x]  `zlib` - @emilypi has done a release

**Comment by angerman** [comment]
package | ghc-9.0.1 | hackage latest as of today
---- | ---- | ----
ghc | 9.0.1 |  8.10.2
base | 4.15.0.0 | 4.14.1.0
ghc-boot-th | 9.0.1 | 8.10.2
ghc-boot | 9.0.1 | 8.8.3
ghc-prim | 0.7.0 | 0.6.1
ghci | 9.0.1 | 8.10.2
hpc | 0.6.1.0 | 0.6.0.3
integer-gmp | 1.1 | 1.0.3.0
libiserv | 9.0.1 | -
template-haskell | 2.17.0.0 | 2.16.0.0

**Comment by bergmark** [comment]
I saw that Oleg asked to take over maintainership of uuid*, so i'd say we should let that play out. Perhaps hackage admins can expedite it?
Would it be possible to find maintainers for the regex packages as well?

I have been toying with the proposal of revising/dropping NMUs as a trustee thing as it requires a lot more effort than other things we do. i.e. it would at least feel like less work for me to personally take over maintainership and do the uploads.

**Comment by emilypi** [comment]
Great news on `uuid`, `uuid-types`, and `hashable`, thanks @phadej! HVR poked his head out this morning to mention that he updated the bounds on `text-short`, so that one is solved for now. We'll continue discussing plans to co-maintain in private. This leaves us with the regex libraries. Personally i'm fine if @bergmark  or some combination of @bergmark + others here take on co-maintenance. I'm happy to help move things along as well.

**Comment by sjakobi** [comment]
> This leaves us with the regex libraries. Personally i'm fine if @bergmark or some combination of @bergmark + others here take on co-maintenance.

@andreasabel offered to help as a co-maintainer in https://github.com/haskell-hvr/regex-base/issues/9.

**Comment by emilypi** [comment]
Ah! right, yes @andreasabel as well.

**Comment by Bodigrim** [comment]
Couple more: 
* `hslogger` needs a revision for `bytestring-0.11`. PR https://github.com/haskell-hvr/hslogger/pull/60 is open for two months, multiple pings, no reaction.
* `cassava` needs a revision for `bytestring-0.11`. https://github.com/haskell-hvr/cassava/pull/190 is open for a month. 

@bergmark could you possibly make revisions for these?

**Comment by emilypi** [comment]
Good news: 

HVR popped up and made @phadej, @andreasabel and I are now maintainers of regex-*, and @phadej in particular a maintainer of `uuid` and `uuid-types`. We'll have things unblocked shortly, and then we can address any lingering revisions.

**Comment by andreasabel** [comment]
I get to work on regex-*; @hvr invited me into the team.

**Comment by bergmark** [comment]
Great stuff. I think we can close this then?

**Comment by andreasabel** [comment]
Er, I also need upload permissions on hackage for the regex-* family.

**Comment by andreasabel** [comment]
@bergmark Please keep this open until the hackage permissions have also been granted.

**Comment by bergmark** [comment]
@Bodigrim sorry i missed your request for hslogger & cassava! I've revised hslogger. For cassava, i may be a bit outdated on how cabal-install deals with flags now but I'm not able to get it compiling, getting
```
error: **INVARIANT BROKEN** Detected invalid combination of `text-short` and `bytestring` versions. Please verify the `pre-bytestring-0.10-4` flag-logic in the .cabal file wasn't elided.
```
It works with stack, but I'm afraid adding the revision could cause compilation issues for cabal-install.

**Comment by Bodigrim** [comment]
> For cassava, i may be a bit outdated on how cabal-install deals with flags now but I'm not able to get it compiling

I think your package index is outdated and does not include recently revised [`text-short-0.1.3`](https://hackage.haskell.org/package/text-short-0.1.3). 

```cabal
  if flag(bytestring--LT-0_10_4)
    build-depends: bytestring <  0.10.4
                 , bytestring-builder >= 0.10.8 && < 0.11
  else
    build-depends: bytestring >= 0.10.4
                 , text-short == 0.1.*
```

I presume you've been running something like `cabal build --constraint 'bytestring >= 0.11' --allow-newer 'cassava:bytestring'`. If there is no `text-short` available to satisfy `bytestring-0.11` (which was the case before `text-short-0.1.3` got revised), in order to find a build plan `cabal` is forced to enable `bytestring--LT-0_10_4` - with catastrophic consequences. 

@bergmark could you please `cabal update` and give it one more go?

**Comment by bergmark** [comment]
That wasn't it, still not exactly sure what is going on but i managed to solve it by using local versions of regex-base and regex-posix with patched bytestring upper bounds! So it will be fine once they are updated as well. http://hackage.haskell.org/package/cassava-0.5.2.0/revisions/

**Comment by emilypi** [comment]
@bergmark good to hear. 

Just an update: @Bodigrim and I have been granted co-maintainership of `Cabal`, `cabal-install`, `zlib`, and `tar` as of today. An RC is out for `zlib`, and we'll have one out shortly for `regex-*` as needed, once HVR approves of the PR prep.

**Comment by andreasabel** [comment]
I released [regex-base-0.94.0.1](https://hackage.haskell.org/package/regex-base-0.94.0.1).  Getting to work on regex-posix.

**Comment by andreasabel** [comment]
`regex-posix` got its revision: https://hackage.haskell.org/package/regex-posix-0.96.0.0/revisions/

**Comment by emilypi** [comment]
If we don't see a review from @phadej on the existing [zlib-0.6.2.3-rc](https://github.com/haskell/zlib/releases/tag/0.6.2.3-rc) in the next 2-3 days, I'll just do a release if everyone's okay with that.

**Comment by andreasabel** [comment]
`regex-tdfa` has also been revised

**Comment by emilypi** [comment]
`zlib-0.6.2.3` is now live! 

We did it!  Thank you for the hustle everyone. Hopefully we are now in a place where this doesn't happen again because support maintainers are now in place for the relevant packages. Thank you to everyone who helped us get things moving again!

**Comment by bergmark** [comment]
great!

**Comment by phadej** [comment]
Can `cassava`'s `base` bound be relaxed as well?

**Comment by bergmark** [comment]
@phadej i did http://hackage.haskell.org/package/cassava-0.5.2.0/revisions/ previously, did i miss something?

**Comment by phadej** [comment]
I don't see `base` in your revision. only `bytestring` and `QuickCheck`.

**Comment by phadej** [comment]
I made revision for  `cassava-0.5.2.0` allowing `base-4.15`: https://hackage.haskell.org/package/cassava-0.5.2.0/revisions/
