### ISSUE TITLE
Relax random upper bound on arithmoi

### ISSUE THREAD

**Issue by snoyberg** [haskell-infra/hackage-trustees#3]
* Originally reported: https://github.com/fpco/stackage/issues/291 (September 2014)
* Pull request sent in Bitbucket https://bitbucket.org/dafis/arithmoi/pull-request/6/allow-random-11/diff (December 2014)
* Requested change: modify the `random` upper bound to allow 1.1

This is currently preventing upgrade to random 1.1 for any packages depending on arithmoi

**Comment by hvr** [comment]
(and then there's also this: https://bitbucket.org/dafis/arithmoi/issue/15/fails-to-compile-with-ghc-784-due-to-fllvm ...)

**Comment by snoyberg** [comment]
I'm fully in favor of patching arithmoi for that issue too, I just wasn't going to push my luck ;). For now, the random upper bound is causing me the most pain, and the fix there seems incredibly non-controversial.

**Comment by bergmark** [comment]
To push my luck, +1 on both, though an admin would have to change the flag i suppose?

To dig further, shouldn't that flag be manual?

**Comment by hvr** [comment]
> To dig further, shouldn't that flag be manual?

Yes! :-)

**Comment by hvr** [comment]
@mietek didn't you try to contact the arithmoi author as well? didn't we talk about taking over that package back in January?

**Comment by hvr** [comment]
I just stumbled over http://comments.gmane.org/gmane.comp.lang.haskell.libraries/21399

**Comment by cartazio** [comment]
by the same token, gloss-raster forces `-fllvm` to be set as well. 

I feel like the right solution would to be allow .cabal files to have a way to express "prefer the llvm backend, if its available", or perhaps in the setup.hs file

**Comment by mietek** [comment]
A PR relaxing the `random` upper bound was opened in September 2014, by Ryan Scott:
https://bitbucket.org/dafis/arithmoi/pull-request/5/

I’ve forked the package in December, and disabled using the LLVM backend by default:
https://github.com/mietek/arithmoi

The package has at least one major (segfaulting) bug, even with LLVM off:
https://github.com/mietek/arithmoi/issues/1

**Comment by bergmark** [comment]
I went ahead and published a new revision allowing `time < 1.2`, I hope I am not getting ahead of myself since we are still working on formalizing the procedure.

This is also all that I can do with my trustee permissions.

* Comment on the issue in the source repo: https://bitbucket.org/dafis/arithmoi/pull-request/6/allow-random-11/diff#comment-5585641
* Hackage revision info: http://hackage.haskell.org/package/arithmoi-0.4.1.1/revisions/

**Comment by cartazio** [comment]
ok, @hvr  points out that http://comments.gmane.org/gmane.comp.lang.haskell.libraries/21399 may constitute authoriztion for me to be added to the maintainers list for arithmoi (which is something i'm happy to help with). (nb, if thats acceptable to others, note that i'll be happy to at least be a centralized point for patch merging, i'm still navigating intellectual property madness at current employer, so i'd be limited to just doing code review/merging/release engineering for the next 1-2 months.)

**Comment by snoyberg** [comment]
Thanks guys, I can finally move Stackage up to random-1.1. I'd consider this issue closed; since there still seems to be some discussion, I won't close it myself, but don't hold it open on my account.

**Comment by hvr** [comment]
let's continue the NMU-issue in #7
