### ISSUE TITLE
Base bounds needed for HList

### ISSUE THREAD

**Issue by bergmark** [haskell-infra/hackage-trustees#30]
I'm tired of editing cabal files for today :-) So if anyone else feels like it go ahead!

![screen shot 2015-04-25 at 23 14 04](https://cloud.githubusercontent.com/assets/100681/7334876/152e4d42-eba1-11e4-9f69-abcc606ac57b.png)

**Comment by bergmark** [comment]
`poly-arity` is also breaking because of this.

**Comment by cartazio** [comment]
paging @aavogt

**Comment by bergmark** [comment]
Fixed. @aavogt please update the source repo to have a `base >= 4.6 && < 4.8` constraint.

![screen shot 2015-04-26 at 18 15 51](https://cloud.githubusercontent.com/assets/100681/7338077/57619d64-ec40-11e4-9751-72424d2343b6.png)
