### ISSUE TITLE
Relax base bounds in setlocale

### ISSUE THREAD

**Issue by liskin** [haskell-infra/hackage-trustees#301]
https://hackage.haskell.org/package/setlocale-1.0.0.9 doesn't build with ghc 9.0.1, therefore xmonad doesn't build either.

There's currently `base (>=4.6 && <4.15)`, needs at least `base (>=4.6 && <4.16)`.

I tried pinging the package maintainer here: https://gitlab.com/Kritzefitz/haskell-setlocale/-/merge_requests/1 but as the previous bump has been sitting there for 10 months, I'm not very optimistic about this ping going any better. :-/

**Comment by sjakobi** [comment]
I have created a revision: http://hackage.haskell.org/package/setlocale-1.0.0.9/revisions/

**Comment by sjakobi** [comment]
(I can't close this issue, since I don't have the necessary permissions yet.)

**Comment by liskin** [comment]
Thanks!

(Apologies for opening this before giving Kritzefitz a second chance; on the other hand I'm delighted I can proceed to adding GHC 9 to xmonad CI without being blocked for a few more days. :-))
