### ISSUE TITLE
Tighten Version Bounds for envy 

### ISSUE THREAD

**Issue by IamfromSpace** [haskell-infra/hackage-trustees#302]
Hello, this I have a simple case of version bounds being too loose for the package envy https://hackage.haskell.org/package/envy in its recent releases 2.0.0.0 and 2.1.0.0.  There's already a PR merged to address this within the source repo itself.

This is a simple case where the bounds on `base` are >=4.7, but it depends on `System.Environment.Blank`, which first appears in 4.11 (https://hackage.haskell.org/package/base-4.11.0.0/docs/System-Environment-Blank.html).

Currently, this puts another package in a position where it can't be as compatible as it should be, as it can't drop a bound that it technically shouldn't need.

Hopefully this is an easy one and help would be appreciated, thanks!

**Comment by endgame** [comment]
Done.
