### ISSUE TITLE
Relaxing the base64-bytestring bounds postgresql-simple-migration

### ISSUE THREAD

**Issue by tchoutri** [haskell-infra/hackage-trustees#303]
[postgresql-simple-migration](https://hackage.haskell.org/package/postgresql-simple-migration) is compatible with the newest (1.2) version of `base64-bytestring`.

**Comment by endgame** [comment]
Related PR: https://github.com/ameingast/postgresql-simple-migration/pull/39
Related Issue: https://github.com/ameingast/postgresql-simple-migration/issues/37

**Comment by endgame** [comment]
This has been done.
