### ISSUE TITLE
MissingH needs base bump to work on GHC 9

### ISSUE THREAD

**Issue by ysangkok** [haskell-infra/hackage-trustees#306]
I have tested locally that it builds for on GHC 9 with Base 4.15. So I request that a Hackage revision is made, with the bumped base version. This library is maintained by hvr.

**Comment by Bodigrim** [comment]
We can kick this can down the road a little bit further, but I'm curious: which important packages still depend on `MissingH`? Could they migrate to a better maintained alternative?

**Comment by ysangkok** [comment]
I don't think there are any public packages that could be considered important. Here is a [list of reverse dependencies](https://packdeps.haskellers.com/reverse/MissingH). I recognize only *hpaste*. I'll try to see if I can get this proprietary codebase off of MissingH and ftphs (which also depends on MissingH).

**Comment by gbaz** [comment]
Revision bump done. I do recommend people continuing to migrate off MissingH in general...
