### ISSUE TITLE
hslogger needs base bump to work on GHC 9

### ISSUE THREAD

**Issue by ysangkok** [haskell-infra/hackage-trustees#307]
hslogger is a dependency of many packages like nvim-hs, lambdabot-core, dhall-lsp-server, happstack-server.

I tried locally bumping the base bounds such that it builds with base 4.15, and I didn't have any problems. So I think the trustees can simply publish a revision with bumped bounds. Thanks in advance.

**Comment by sjakobi** [comment]
Related: https://github.com/haskell-hvr/hslogger/issues/61

**Comment by ysangkok** [comment]
This was bumped by @Bodigrim, closing. Thanks!
