### ISSUE TITLE
network-bsd needs network bump

### ISSUE THREAD

**Issue by ysangkok** [haskell-infra/hackage-trustees#308]
Stackage Nightly has `network` 3.1.2.2. But the highest version accepted by `network-bsd` is 3.1.2. I would appreciate bumped bounds such that the popular package `happstack-server` could be used with the latest Stackage Nightly.

I can make another PR with the bumped bounds if you like, but are already a few open PRs, like e.g. https://github.com/haskell/network-bsd/pull/7 . Seems like none of the maintainers are active. I was told on IRC that the CLC is responsible for this package, I don't know if this is the best place to contact them.

**Comment by gbaz** [comment]
Not the best place to contact the clc (perhaps the libraries@ mailing list?). In the meantime I've performed a revision that should fix this, after testing that the new bounds build. Let me know if there are further issues.
