### ISSUE TITLE
edit-distance and lattices

### ISSUE THREAD

**Issue by phadej** [haskell-infra/hackage-trustees#31]
Oleg Grenrus (= me, @phadej) wants to take over edit-distance and lattices. e-mail to libraries sent on 2015-04-26: https://mail.haskell.org/pipermail/libraries/2015-April/025553.html

Related issue: https://github.com/haskell-infra/hackage-trustees/issues/19

**Comment by phadej** [comment]
Ping @batterseapower

**Comment by hesselink** [comment]
I've just added you as maintainer to both packages. I think the relatively short time frame is warranted in this case, since we know Max isn't active in the community anymore.

It seems I can't close this issue, btw. Could someone close it for me?

**Comment by phadej** [comment]
Thanks!
