### ISSUE TITLE
Revise upper bounds for deepseq-generics to build with GHC 9.0

### ISSUE THREAD

**Issue by andreasabel** [haskell-infra/hackage-trustees#311]
deepseq-generics can build with GHC 9.0 if some upper bounds are relaxed.
A corresponding PR is at https://github.com/haskell-hvr/deepseq-generics/pull/11.

See similar previous revisions: https://hackage.haskell.org/package/deepseq-generics-0.2.0.0/revisions/

**Comment by endgame** [comment]
As a Hackage Trustee, I have published these revisions.
