### ISSUE TITLE
Revise upper bound on base for cryptohash-sha1 to build with GHC 9.0

### ISSUE THREAD

**Issue by andreasabel** [haskell-infra/hackage-trustees#313]
`cryptohash-sha1` can build with GHC 9.0 if the upper bound of base is relaxed. (https://github.com/haskell-hvr/cryptohash-sha1/issues/10, February 2021.)
A corresponding PR is at https://github.com/haskell-hvr/cryptohash-sha1/pull/11 (April 2021).

See similar previous revisions: https://hackage.haskell.org/package/cryptohash-sha1-0.11.100.1/revisions/

**Comment by Bodigrim** [comment]
@andreasabel what exactly needs to be relaxed? The latest revision (June 2021) already allows `base-4.15`.

**Comment by andreasabel** [comment]
@Bodigrim: Ah sorry, my mistake.
