### ISSUE TITLE
aeson-2.0.0.0 issues.

### ISSUE THREAD

**Issue by phadej** [haskell-infra/hackage-trustees#318]
FYI, when you make revisions, for packages not compatible with `aeson-2.0.0.0`, the proper upper bound is `<1.6` (that is what should been there to begin with), not `<2`. It's possible that the `aeson-1.6.0.0` will exist (though unluckily).

**Comment by andreasabel** [comment]
Well...
I think there are two modes in which upper bounds are assigned:
1. Pessimistic: The upper bounds determine a version set for which there is _evidence of successful build_.  Restriction of upper bounds is not needed in the pessimistic flavor, but relaxation can occur when there is evidence of success.
2. Optimistic: The upper bounds determine a version set for which there is _no evidence of build failure_.  Restriction of upper bounds is necessary once a build failure is documented.  (Relaxation is never needed.)

I would argue that if a package does not have an upper bound on `aeson` at all, it belongs into the _optimistic_ ballpark.  Thus, the proper restriction is `aeson < 2` when there is evidence of build failure with `aeson-2`.  As there is no `aeson-1.6` yet, there cannot be evidence of build failure.  
Should there be a `aeson-1.6` in the future that produces build failures, further restrictions should be applied.
Switching a package from `aeson < infinity` to `aeson < 1.6` would imo mean to switch a package from _optimistic_ to _pessimistic_; this might not be in the intention of the package author.

**Comment by phadej** [comment]
In my experience Hackage Trustees have no time to be optimistic. If maintainers are quick and do (optimistic) revisions themselves, that's great. But I aim that we don't need to revisit the same package-version twice or more times (for the same dependency!)

In fact, https://hackage.haskell.org/upload read about 

> Package uploaders may choose to exclude individual package uploads from curation, by setting the x-curation: field of the package's cabal file to uncurated. Packages which are uncurated have no expectations on them regarding versioning policy. Trustees or maintainers may adopt uncurated packages into the curated layer through metadata revisions. Metadata revisions must not set the value of the x-curation field to any variant of uncurated.

That implies that once we do revision, *we* curate it to the end of time. If interpret strictly, we should add upper bounds to **all** dependencies when we make a revision, to adhere to the PVP.

**Comment by phadej** [comment]
For example, @sjakobi made revisions for twenty `yaml` package versions with `aeson <2`. If for whatever reason, aeson-1.6 is released which still breaks `yaml`, that's another 20 revisions. However, if the first revision were with `aeson <1.6` bound, then it would be probably enough to make one or two (one per major series) relaxing revisions. In total less work.

As there are plenty of responsive Hackage Trustees, you Andreas, the delay caused waiting for relaxing revision is a lot less then pain caused by broken builds locally and CIs etc. all over the place.
