### ISSUE TITLE
monad-peel

### ISSUE THREAD

**Issue by l29ah** [haskell-infra/hackage-trustees#32]
Won't compile on GHC 7.8.2 and newer. I've sent mails to Anders Kaseorg <andersk@mit.edu> at 7/21/14 and 11/17/14. I maintain a package that uses it: Network-NineP. I have a dumb patch for it that keeps me going: https://dump.bitcheese.net/files/ofawana/monad-peel-ghc-7.8.2.patch

**Comment by bergmark** [comment]
Maintenance of the cgi package was transferred from Anders a while ago, he seems to not be active anymore.

@l29ah would you like to take over maintenance of monad-peel? If so, please send an e-mail stating this to haskell-café or libraries with Anders cc'd.

**Comment by l29ah** [comment]
I'd like to take the maintenance of monad-peel as it's currently broken
and Anders seems unavailable.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by l29ah** [comment]
I'm in favor of this move. But a question for you: what's the use case for
which you're using monad-peel? Most of the cases I've had (and I've seen
others have) now use monad-control instead.

**Comment by bergmark** [comment]
Confusing with the reply-all ;-)

Anyway, here's the takeover request: https://mail.haskell.org/pipermail/libraries/2015-April/025572.html

**Comment by bergmark** [comment]
@l29ah Have you sent an e-mail to admin@hackage.org?

**Comment by l29ah** [comment]
On Fri, Jun 12, 2015 at 02:11:13AM -0700, Adam Bergmark wrote:
> @l29ah Have you sent an e-mail to admin@hackage.org?

no

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by hesselink** [comment]
I've added SergeyAlirzaev to the maintainers of monad-peel.

**Comment by l29ah** [comment]
Thanks.
