### ISSUE TITLE
bump newtype version bounds

### ISSUE THREAD

**Issue by andremarianiello** [haskell-infra/hackage-trustees#324]
`newtype` builds with base-4.16, so it should have the upper bound bumped. I would make the PR myself but I don't know where the latest code lives. The [newtype](https://github.com/haskell-hvr/newtype) repo appears to have have the latest version.

**Comment by andreasabel** [comment]
Done: https://hackage.haskell.org/package/newtype-0.2.2.0/revisions/

**Comment by andremarianiello** [comment]
Thank you!
