### ISSUE TITLE
Bump bmp version bounds

### ISSUE THREAD

**Issue by athas** [haskell-infra/hackage-trustees#326]
[bmp](https://hackage.haskell.org/package/bmp) should have its bound on `bytestring` loosened to also allow 0.11.

[Upstream pull request](https://github.com/benl23x5/bmp/pull/3)

**Comment by endgame** [comment]
Normally I'd be inclined to wait and give the maintainer a chance to respond, but the README for that repo reads:

> If you just want to bump a dependency version then get a Hackage trustee to edit the package information directly on Hackage. You don't need to raise a pull request here.

I have revised `bmp-1.2.6.3`; reopen and let me know if I should do any others.
