### ISSUE TITLE
cautious-file should allow filepath-1.4

### ISSUE THREAD

**Issue by bergey** [haskell-infra/hackage-trustees#33]
[cautious-file](http://hackage.haskell.org/package/cautious-file) builds locally with `filepath-1.4` if I just change the .cabal file.  I help maintain [diagrams-haddock]( http://hackage.haskell.org/package/diagrams-haddock) which depends on `cautious-file`.

I emailed a patch to the author on 2015-04-15, and have not heard back.

(The Hackage page makes it look like there are no bounds on the dependencies. [The .cabal file](http://hackage.haskell.org/package/cautious-file-1.0.2/cautious-file.cabal) has bounds, though.)

**Comment by bergmark** [comment]
The package only uses filepath in one place, calling `splitFileName` so it looks ok to me, i'll update.

**Comment by bergmark** [comment]
http://hackage.haskell.org/package/cautious-file-1.0.2/revisions/

Also sent an e-mail to robin.

**Comment by bergey** [comment]
That was fast.  Thanks!
