### ISSUE TITLE
Restrict bounds of `datadog` to disallow aeson-2

### ISSUE THREAD

**Issue by ysangkok** [haskell-infra/hackage-trustees#332]
Per https://github.com/iand675/datadog/issues/40 , datadog doesn't compile with aeson-2. The maintainer is generally unresponsive, as you can see [the PR to add aeson-2 compatibility](https://github.com/iand675/datadog/pull/41) was also ignored. I request that the trustees mark existing releases as `aeson < 2`. Thank you.

**Comment by phadej** [comment]
There seems to be some other missing bounds as well. I'll make revisions after I figure them out.

**Comment by phadej** [comment]
Done.

**Comment by andreasabel** [comment]
For reference: https://hackage.haskell.org/package/datadog-0.2.5.0/revisions/
