### ISSUE TITLE
Base bounds on `generic-arbitrary` are too loose

### ISSUE THREAD

**Issue by ysangkok** [haskell-infra/hackage-trustees#333]
See https://github.com/typeable/generic-arbitrary/pull/13#issuecomment-1061305512

Since a week has passed since the comment, I am asking the trustees to adjust the bounds of both versions to exclude GHC 9.2.

**Comment by andreasabel** [comment]
Done at: https://hackage.haskell.org/package/generic-arbitrary-0.2.0/revisions/

**Comment by phadej** [comment]
generic-arbitrary-0.1.0 needs a revision too.

**Comment by andreasabel** [comment]
Ok, good point: https://hackage.haskell.org/package/generic-arbitrary-0.1.0/revisions/
