### ISSUE TITLE
ACME package needs tighter base bound

### ISSUE THREAD

**Issue by treeowl** [haskell-infra/hackage-trustees#334]
The [`ACME`](https://hackage.haskell.org/package/ACME) package is definitely incompatible with `base >= 4.8` due to AMP. I have not checked for the most recent compatible `base` version, but 4.7 seems a pretty good bet.

I attempted to file a ticket on the listed website, but it is down and was last crawled by the Internet Archive in 2016. The email address at the same domain similarly does not work. A whois lookup suggests domain registration has lapsed. I do not have any other contact info for James Candy.

As the `ACME` package is part of the `acme` namespace, and therefore one of the most important jumping-off points for Haskell programming, it is critical to fix this problem immediately, or sooner using the `tardis`.

**Comment by andreasabel** [comment]
I could build ACME-0.0.0.0/1 with GHC 7.8 but not with 7.10.  So @treeowl's bet seem correct.
Revised both versions: 
- https://hackage.haskell.org/package/ACME-0.0.0.0/revisions/
- https://hackage.haskell.org/package/ACME-0.0.0.1/revisions/
