### ISSUE TITLE
Documentation on how Hackage Trustees formed

### ISSUE THREAD

**Issue by ulysses4ever** [haskell-infra/hackage-trustees#336]
I fail to find a description of how the Hackage Trustees get added, rotated, etc. It looks very mysterious for an outsider, which feels like a bad thing these days. Would it be possible to add some clarification about this? If it's a community role, the community should have an idea how this role operates.

**Comment by andreasabel** [comment]
This is the current information:
1. https://wiki.haskell.org/Hackage_trustees
2. https://github.com/haskell-infra/hackage-trustees
3. https://github.com/haskell-infra/hackage-trustees/blob/master/policy.md

From 1.:
> The server has a special user group called "trustees", so the current list of trustees is always available at https://hackage.haskell.org/packages/trustees/
> The whole trustee system, and metadata editing feature is still somewhat in its infancy. The initial trustees were appointed by the hackage admins based on their previous volunteer work in this area. There is currently no formal process for becoming a trustee.

From the last sentence I concluded I could send an email to the current trustees with my resume and application to become a trustee.

In practice, being a trustee amounts to do volunteer work for Hackage in service of the Haskell community.

**Comment by ulysses4ever** [comment]
Beautiful, thank you! Couple points:

- I always fear to believe the Wiki because generally speaking it has tons of outdated materials.
- Therefore, I'd suggest to add all essential things about the Trustees institute to this repository.
- There is some distance between what the Wiki currently says and your conclusions. Maybe something closer to the latter may be added somewhere  (preferably to this repo, for the reason mentioned in the first point).

I did get the answer to my question, so I'm fine with closing this ticket if you think it's okay. Above are just suggestions that don't have to be implemented necessarily.

**Comment by ulysses4ever** [comment]
I'm also not sure what email you used. This may be good to specify too.

**Comment by gbaz** [comment]
I agree the documentation is incomplete on these points. As we really want more trustees as a general proposition (there's always more work to be done) it would be good to cleanup the documentation and make a bunch of stuff explicit and all in one place.

**Comment by andreasabel** [comment]
> I'm also not sure what email you used. This may be good to specify somewhere too.

We are using <hackage-trustees@haskell.org>.  This one is mentioned in
4. https://hackage.haskell.org/users/register-request

There is one in source 2., not sure if this is a working alias:
> The trustees can also be contacted at [trustees@hackage.haskell.org](mailto:trustees@hackage.haskell.org)

**Comment by gbaz** [comment]
That alias usually works but not always, because of reasons involving proxies, A, C and MX dns records. As such, we deprecated it some time ago. I've now updated source 2 to the newer alias.

**Comment by ulysses4ever** [comment]
All right, if you think this works fine, I'm happy to close. Thanks for replies!
