### ISSUE TITLE
`misfortune` needs fixing

### ISSUE THREAD

**Issue by ncfavier** [haskell-infra/hackage-trustees#337]
The `misfortune` package needs a patch (https://github.com/mokus0/misfortune/pull/5) in order to build with GHC 9, but the maintainer hasn't touched the repository in 7 years and hasn't responded to the PR or to my email (sent 2022-03-27). See also https://mail.haskell.org/pipermail/libraries/2022-June/031614.html

**Comment by endgame** [comment]
If you want to take over maintenance of the package yourself, the takeover process is here: https://wiki.haskell.org/Taking_over_a_package

**Comment by ncfavier** [comment]
That's why I sent https://mail.haskell.org/pipermail/libraries/2022-June/031614.html, but someone pointed out that simple changes didn't require a full takeover so I'm also doing this (I'm assuming it will take less time).

**Comment by Bodigrim** [comment]
@ncfavier NMUs are reserved for critical, high-impact cases. Please carry on with the take over instead.

**Comment by ncfavier** [comment]
OK, thanks!
