### ISSUE TITLE
socket needs bytestring constraint relaxed to work with GHC 9.2

### ISSUE THREAD

**Issue by sternenseemann** [haskell-infra/hackage-trustees#338]
This change was proposed to upstream [three months ago](https://github.com/lpeterse/haskell-socket/pull/70), but it has been unresponsive (actually a while longer, as you can gather from the open pull requests). The package works fine with bytestring 0.11 which is bundled with GHC 9.2.

A package of mine depends on it (spacecookie) and is not possible to be built using  GHC 9.2 (dropping out of stackage nightly as a result). I'll may want to migrate to network, but relaxing the constraint gives me more time to consider this change.

Edit: see also <https://github.com/commercialhaskell/stackage/issues/6486>.

**Comment by Bodigrim** [comment]
Done in https://hackage.haskell.org/package/socket-0.8.3.0/revisions/

**Comment by sternenseemann** [comment]
Thanks, that works as expected!
