### ISSUE TITLE
revise resolv to allow base-4.17

### ISSUE THREAD

**Issue by juhp** [haskell-infra/hackage-trustees#341]
Can the Hackage Trustees please revise [resolv](https://hackage.haskell.org/package/resolv-0.1.2.0)
to allow building with base-4.17 (ghc-9.4)? (I have tested it locally with ghc-9.4.1 and it seems to build fine.)

(I didn't open an upstream issue in hvr/resolv because the package is not actively maintained:
the current revisions in Hackage are not in the git repo yet.)

This may allow getting cabal-install-3.8 to build with ghc-9.4 eventually...

**Comment by andreasabel** [comment]
@juhp Ok, I bumped the base on hackage: https://hackage.haskell.org/package/resolv-0.1.2.0/revisions/

However, I fail to build it locally from the repo:
```
$ ./configure
...
configure: creating ./config.status
config.status: creating resolv.buildinfo
config.status: error: cannot find input file: `cbits/hs_resolv_config.h.in'
```
Likewise, CI fails in the `sdist` step: https://github.com/haskell-hvr/resolv/runs/7805633124?check_suite_focus=true 
- https://github.com/haskell-hvr/resolv/pull/15

Is there a trick I am missing?

**Comment by juhp** [comment]
(I hit the same problem, but see that you managed.)

Thank you very much!!

**Comment by andreasabel** [comment]
Indeed, I was missing a `autoheader` (which seems to be subsumed by `autoreconf`).
