### ISSUE TITLE
graphviz.cabal revision needed for bytestring-0.11

### ISSUE THREAD

**Issue by juhp** [haskell-infra/hackage-trustees#343]
See ivan-m/graphviz#53 opened at the end of 2021.

This prevents [graphviz-2999.20.1.0](https://hackage.haskell.org/package/graphviz-2999.20.1.0) going into Stackage Nightly (ie building with ghc-9.2).

Thanks!

**Comment by Bodigrim** [comment]
Done in https://hackage.haskell.org/package/graphviz-2999.20.1.0/revisions/
