### ISSUE TITLE
Bump `base` for `utf8-light`

### ISSUE THREAD

**Issue by ffaf1** [haskell-infra/hackage-trustees#347]
package I was trying to build: [venzone](https://hackage.haskell.org/package/venzone)
offending package: [utf8-light](https://hackage.haskell.org/package/utf8-light)

- I contacted the maintainer on Oct 2 (10 days ago) via email
- there is no repository (link on hackage is 404)
- reproduce: check below
- this is not critical, as [there are only five packages depending on it](https://packdeps.haskellers.com/reverse/utf8-light)

```
f@mkiii:~/francesco/progetti/progr/venzone$ cabal build --minimize-conflict-set
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] trying: venzone-1.1.0.1 (user goal)
[__1] trying: utf8-light-0.4.2 (dependency of venzone)
[__2] next goal: base (dependency of venzone)
[__2] rejecting: base-4.16.0.0/installed-4.16.0.0 (conflict: utf8-light =>
base<4.16)
[__2] skipping: base-4.17.0.0, base-4.16.3.0, base-4.16.2.0, base-4.16.1.0,
base-4.16.0.0 (has the same characteristics that caused the previous version
to fail: excluded by constraint '<4.16' from 'utf8-light')
[__2] rejecting: base-4.15.1.0, base-4.15.0.0, base-4.14.3.0, base-4.14.2.0,
base-4.14.1.0, base-4.14.0.0, base-4.13.0.0, base-4.12.0.0, base-4.11.1.0,
base-4.11.0.0, base-4.10.1.0, base-4.10.0.0, base-4.9.1.0, base-4.9.0.0,
base-4.8.2.0, base-4.8.1.0, base-4.8.0.0, base-4.7.0.2, base-4.7.0.1,
base-4.7.0.0, base-4.6.0.1, base-4.6.0.0, base-4.5.1.0, base-4.5.0.0,
base-4.4.1.0, base-4.4.0.0, base-4.3.1.0, base-4.3.0.0, base-4.2.0.2,
base-4.2.0.1, base-4.2.0.0, base-4.1.0.0, base-4.0.0.0, base-3.0.3.2,
base-3.0.3.1 (constraint from non-upgradeable package requires installed
instance)
[__2] fail (backjumping, conflict set: base, utf8-light, venzone)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, utf8-light, venzone
```

**Comment by sjakobi** [comment]
Do you have a patch? The current bound `base < 4.16` was added for a reason.

Maybe you could consider [taking over the package](https://wiki.haskell.org/Taking_over_a_package)? We haven't really been doing non-maintainer uploads for a while.

**Comment by sjakobi** [comment]
FWIW, I've tightened the bounds on `utf8-light` v0.3, v0.4 and v0.4.0.1 after finding some bad build plans. I've notified Matt Morrow, the maintainer, via email about this.

**Comment by andreasabel** [comment]
Looks like the real maintainer for `utf8-light` is [Patrick Palka](https://hackage.haskell.org/user/PatrickPalka): He uploaded the latest versions.  Matt Morrow's last upload was in 2008.

However, I don't know the identity of Patrick Palka nor how to contact him.  Maybe the takeover request should be handled via the Haskell mailing lists (with CC to the formal maintainer Matt Morrow).

**Comment by ffaf1** [comment]
So be it, I will pen a takeover request.

**Comment by ulysses4ever** [comment]
The takeover was initiated more than a month ago, and it's been silent since. Could the trustees, please, act on it?

**Comment by ffaf1** [comment]
Sorry, I forgot to write here that the takeover was granted and now I am a maintainer of utf8-light. Write to me for any request!

**Comment by ulysses4ever** [comment]
@ffaf1 nice, thanks!

**Comment by ulysses4ever** [comment]
@ffaf1 actually, could you

1.  comment on https://github.com/NixOS/nixpkgs/pull/202022#issuecomment-1327896594
2. Update the Source Repo field in the package description to point to your fork? So that people have a clear picture of the current state of things.

**Comment by ulysses4ever** [comment]
Updating the Maintainer field of the description is also a good idea!

**Comment by ffaf1** [comment]
done, repo here: https://gitlab.com/fffaaa/utf8-light/
