### ISSUE TITLE
Requesting bump of transformers for ftp-client

### ISSUE THREAD

**Issue by ysangkok** [haskell-infra/hackage-trustees#348]
See https://github.com/mr/ftp-client/issues/25 . I have successfully compiled and tested the revised package 0.5.1.4 with transformers 0.6, and it seems to work fine.

**Comment by andreasabel** [comment]
Done: https://hackage.haskell.org/package/ftp-client-0.5.1.4/revisions/
I also successfully ran: `cabal build -c 'transformers == 0.6.*' --allow-newer='*:transformers'`
