### ISSUE TITLE
deepseq and safe haskell

### ISSUE THREAD

**Issue by bergmark** [haskell-infra/hackage-trustees#35]
Can someone help me understand this this build failure http://matrix.hackage.haskell.org/package/palette#GHC-7.2/palette-0.1.0.2 ?

deepseq fails to install with `ghc-prim:GHC.Generics can't be safely imported! The module itself isn't safe.` but deepseq doesn't fail by itself: http://matrix.hackage.haskell.org/package/deepseq

**Comment by hvr** [comment]
@bergmark it's because `palette` forces installing a newer `array` version, whereas the vanilla `deepseq` install-plan picks the `array` version already coming w/ GHC 7.2

**Comment by bergmark** [comment]
Oh this is awkward https://github.com/haskell/deepseq/pull/7 :-(

Thanks!
