### ISSUE TITLE
Revision request for `mongoDB`

### ISSUE THREAD

**Issue by parsonsmatt** [haskell-infra/hackage-trustees#351]
The [`mongoDB`](https://hackage.haskell.org/package/mongoDB) package version 2.7.1.2 assumes an import of `MonadFail` from `Prelude`, and does not build with GHC < 8.8.

To fix this, a revision for `base < 5` to `base >= 4.13 && < 5` would work for this version.

I have made [an upstream issue](https://github.com/mongodb-haskell/mongodb/issues/139) and [a PR to fix the problem](https://github.com/mongodb-haskell/mongodb/pull/140).

**Comment by Bodigrim** [comment]
Done in https://hackage.haskell.org/package/mongoDB-2.7.1.2/revisions/
