### ISSUE TITLE
Request to take over `xmlbf` and `xmlbf-xeno`

### ISSUE THREAD

**Issue by parsonsmatt** [haskell-infra/hackage-trustees#353]
Upstream issue, creatd 4 weeks ago: https://gitlab.com/k0001/xmlbf/-/issues/33

[The test suite is broken on GHC 9.4](https://gitlab.com/k0001/xmlbf/-/issues/32), reported 10 months ago with no response

[The `git` repo has a new version with no release](https://gitlab.com/k0001/xmlbf/-/issues/31). Release requested May '21, no response

A [prior release request in Jan '20 was ignored](https://gitlab.com/k0001/xmlbf/-/issues/30)

Tagging @k0001 just in case.

I haven't seen any activity from Renzo online for quite some time. I hope he's doing well. :(

**Comment by k0001** [comment]
I'm doing well, thank you. Just busy with other things. I'll try to attend to those issues this weekend. No need to take over.

**Comment by andreasabel** [comment]
If I remember correctly, the takeover process requires trying to contact the current maintainer by email. See https://wiki.haskell.org/Taking_over_a_package

The current maintainer and original author is Renzo Carbonara.
Checking the hackage releases, e.g. https://hackage.haskell.org/package/xmlbf , no maintainer email is given here.
The author could be identical with the author of this web page: https://atypeofprogramming.com/ 
This contact email is given there: [hola@atypeofprogramming.com](mailto:hola@atypeofprogramming.com)
It might be worth trying to reach the author there.

If the author is unreachable, the takeover process requires you to state the takeover intent in a public, frequented Haskell forum ("we recommend the haskell-cafe and/or libraries list").

Note that to facilitate the takeover, the Hackage Admins need to be involved.  If I am not mistaken, the Hackage Trustees are not concerned with takeovers.  (Certainly, they lack the powers to facilitate such a takeover on Hackage.)

**Comment by andreasabel** [comment]
Ah, ok, just now the author responded.  I guess I can close this then...

**Comment by Bodigrim** [comment]
> Note that to facilitate the takeover, the Hackage Admins need to be involved. If I am not mistaken, the Hackage Trustees are not concerned with takeovers. 

Precisely.
