### ISSUE TITLE
Requesting Cabal bump for servant-openapi3

### ISSUE THREAD

**Issue by ysangkok** [haskell-infra/hackage-trustees#354]
Upstream issue: https://github.com/biocad/servant-openapi3/issues/34

A [PR adding GHC 9.4 support](https://github.com/biocad/servant-openapi3/pull/33) to servant-openapi3 was already merged, but sadly that patch forgot allowing Cabal 3.8, which is needed to actually use GHC 9.4 according to the [GHC release notes](https://www.haskell.org/ghc/download_ghc_9_4_3.html).

I have tested that this project builds fine on Cabal 3.8, and I have sent [a PR](https://github.com/biocad/servant-openapi3/pull/35) and pinged the maintainer, but I haven't received a response since originally reporting this on December 6th.

So I am requesting that a trustee relaxes this Cabal bound to permit Cabal 3.8 or removes it entirely.

**Comment by andreasabel** [comment]
I relaxed the `Cabal` bound to `<3.9`: https://hackage.haskell.org/package/servant-openapi3-2.0.1.5/revisions/
