### ISSUE TITLE
grow-vector builds with newer base

### ISSUE THREAD

**Issue by shlevy** [haskell-infra/hackage-trustees#357]
I've successfully built grow-vector with base-4.16. I haven't tried anything newer.

**Comment by andreasabel** [comment]
Please ask the maintainer for a revision or re-release:
- https://github.com/NCrashed/grow-vector/pull/1

**Comment by andreasabel** [comment]
Determined correct bounds and revised accordingly.
Package fixed in:
- https://github.com/NCrashed/grow-vector/pull/2
