### ISSUE TITLE
Loosen bounds of `libsystemd-journal-1.4.5`

### ISSUE THREAD

**Issue by michaelpj** [haskell-infra/hackage-trustees#360]
Maintainer is unlikely to take action: https://github.com/ocharles/libsystemd-journal/pull/27#issuecomment-1488536165

Proposed relaxations:
```
base < 5
text < 2.1
vector < 0.14
semigroups < 0.21
```
The base relaxation may be too big: I've only built with GHC 9.2 (`base-4.16`). But it's a single module with <500 lines, so I think it'll probably be fine with higher base versions.

**Comment by michaelpj** [comment]
Severity: minor. I don't think many people are using this package.

**Comment by andreasabel** [comment]
As the maintainer has responded and offered to pass on or share maintenance, it would be preferable to not involve the Hackage Trustees, I'd say.

**Comment by andreasabel** [comment]
I had a look into this now, but since I do not have access to a Linux system I cannot help here really.  (Meaning I cannot test the new bounds because I cannot build the package.)

**Comment by andreasabel** [comment]
@sjakobi : Can you help with this issue?

**Comment by Bodigrim** [comment]
This seems to be fixed as of https://hackage.haskell.org/package/libsystemd-journal-1.4.5.1.

**Comment by andreasabel** [comment]
Resolution seems to be: @erikd is Hackage (co-)maintainer now.
