### ISSUE TITLE
Increment the `text` dependency bound of `ca-province-codes`

### ISSUE THREAD

**Issue by blamario** [haskell-infra/hackage-trustees#361]
The `ca-province-codes` library depends on `text >=1 && <2`. That prevents it from building with GHC 9.4.

https://github.com/prikhi/ca-province-codes/issues/1

**Comment by andreasabel** [comment]
Done: https://hackage.haskell.org/package/ca-province-codes-1.0.0.0/revisions/
I followed the bounds style of this package (major-major upper bounds only).
