### ISSUE TITLE
Increment the `text` dependency bound of `hexpat`

### ISSUE THREAD

**Issue by prikhi** [haskell-infra/hackage-trustees#363]
`hexpat` fails to build with `text` v2+ & I haven't seen any activity from the author for a while. I have a PR up but would be nice to have a revision bump:

https://github.com/the-real-blackh/hexpat/issues/12
https://github.com/the-real-blackh/hexpat/pull/13

**Comment by andreasabel** [comment]
I fixed the upper bound on hackage in revision 1: https://hackage.haskell.org/package/hexpat-0.20.13/revisions/
