### ISSUE TITLE
Loosen bounds on protolude

### ISSUE THREAD

**Issue by erikd** [haskell-infra/hackage-trustees#364]
https://github.com/protolude/protolude/pull/143

**Comment by andreasabel** [comment]
@erikd This package seems to me maintained, by @adamwespiser, so I think we should give him some time to respond to your PR; 3 days is a bit short...

**Comment by erikd** [comment]
I should have raised this issue when I first ran into it 4 weeks ago :smile:

**Comment by andreasabel** [comment]
Fixed in https://hackage.haskell.org/package/protolude-0.3.3/revisions/
