### ISSUE TITLE
Relax bounds on `int-cast-0.2.0.0`

### ISSUE THREAD

**Issue by lierdakil** [haskell-infra/hackage-trustees#366]
The pull request has been sitting there for a while with zero feedback https://github.com/haskell-hvr/int-cast/pull/7

The PR in question also hides a redundant import behind CPP, but that's non-essential.

Proposed new constraints:

```
base >=4.7 && <4.19
```

**Comment by andreasabel** [comment]
Fixed by revision 5: https://hackage.haskell.org/package/int-cast-0.2.0.0/revisions/
