### ISSUE TITLE
Relax bounds on `th-extras-0.0.0.6`

### ISSUE THREAD

**Issue by lierdakil** [haskell-infra/hackage-trustees#367]
The pull request has been sitting there for a while with no feedback: https://github.com/mokus0/th-extras/pull/21

Proposed new constraints:

```
template-haskell < 2.21
th-abstraction >= 0.4 && < 0.6
```

**Comment by phadej** [comment]
ping @Ericson2314 @RyanTrinkle @ali-abrar

**Comment by Bodigrim** [comment]
Fixed in https://hackage.haskell.org/package/th-extras-0.0.0.6/revisions/
