### ISSUE TITLE
prometheus: bump upper bound of text dependency

### ISSUE THREAD

**Issue by erikd** [haskell-infra/hackage-trustees#368]
All that is required is a hackage metadata edit.
https://github.com/bitnomial/prometheus/issues/47

**Comment by andreasabel** [comment]
@wraithm : Will you take care of this revision?

**Comment by wraithm** [comment]
Yup, I'll get around to this today.

**Comment by wraithm** [comment]
https://hackage.haskell.org/package/prometheus-2.2.4

**Comment by wraithm** [comment]
Just out of curiosity, @erikd, why did you make an issue here? We respond pretty quickly to any issues on our repos.
