### ISSUE TITLE
Loosen bounds of several Kowainik packages

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell-infra/hackage-trustees#369]
Several packages from the Kowainik ecosystem need their `base` bounds bumped. Issues about updating the bounds have been filed but received no response. Specifically, all the following can have `base` bumped to `< 4.19`:

* `validation-selective-0.2.0.0`
* `trial`, `trial-optparse-applicative` and `trial-tomland` all of version `0.0.0.0`
* `colourista-0.1.0.1`

----

Relevant open issues

* https://github.com/kowainik/tomland/issues/424
* https://github.com/kowainik/tomland/issues/427
* https://github.com/kowainik/validation-selective/issues/76
* https://github.com/kowainik/validation-selective/issues/78
* https://github.com/kowainik/trial/issues/70

**Comment by andreasabel** [comment]
@tomjaguarpaw Can't you use your CLC connections to @chshersh to get things rolling?  https://github.com/haskell/core-libraries-committee

**Comment by tomjaguarpaw** [comment]
`chshersh` is no longer part of Kowainik:

* https://discourse.haskell.org/t/maintaining-haskell-programs/7166/15
* https://kowainik.github.io/ (see section "Creators")

**Comment by andreasabel** [comment]
OK, I made the requested revisions, see:
- https://github.com/kowainik/validation-selective/issues/76#issuecomment-1667964075
- https://github.com/kowainik/tomland/issues/427#issuecomment-1668041658
- https://github.com/kowainik/colourista/issues/99
- https://github.com/kowainik/trial/issues/70#issuecomment-1668073276

**Comment by tomjaguarpaw** [comment]
Thank you! This has unblocked [my work on `stan`](https://github.com/kowainik/stan/issues/423#issuecomment-1668089066).

What's the etiquette of this repo? Do you close the issue or shall I?

**Comment by andreasabel** [comment]
Since you are happy, I can also close it.
