### ISSUE TITLE
protocol-buffers

### ISSUE THREAD

**Issue by bergmark** [haskell-infra/hackage-trustees#37]
Email sent 2015-05-27 https://mail.haskell.org/pipermail/haskell-cafe/2015-May/119810.html

**Comment by ghorn** [comment]
I also contacted that guy with patches twice, months apart. He never responded to me

**Comment by k-bx** [comment]
(I'm the author of that message)

**Comment by k-bx** [comment]
My hackage id is `k_bx`

**Comment by hvr** [comment]
Oh well... that package needs quite a bit of attention to fixup: http://matrix.hackage.haskell.org/package/protocol-buffers :-/

**Comment by bergmark** [comment]
My eyes >_<

**Comment by bergmark** [comment]
@k-bx two weeks have passed so you can send an e-mail to admin@hackage.org referencing this ticket.

**Comment by k-bx** [comment]
@bergmark getting an error from mail delivery system:

```
Delivery to the following recipient failed permanently:

     admin@hackage.org

Technical details of permanent failure:
DNS Error: Address resolution of hackage.org. failed: DNS server returned answer with no data
...
```

Can you check that admin@ is still working for you please?

**Comment by gbaz** [comment]
should be admin@hackage.haskell.org

**Comment by k-bx** [comment]
@gbaz obvious mistake, thank you!

**Comment by bergmark** [comment]
Oopsie

**Comment by hesselink** [comment]
I've added @k-bx as a maintainer of protocol-buffers.

**Comment by bergmark** [comment]
Thanks all! Happy hacking @k-bx

**Comment by hesselink** [comment]
@k-bx asked me to also add him to `protocol-buffers-descriptor` and `hprotoc`, since they are part of the same source repository. That seemed reasonable (and the maintainer is also the same) so I added him there as well.
