### ISSUE TITLE
Loosen bounds of snap-templates

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell-infra/hackage-trustees#372]
[`snap-templates`](https://hackage.haskell.org/package/snap-templates) has too restrictive upper bounds that stop it compiling on anything >= GHC 8.6, but `--allow-newer` seems to work fine. This succeeds:

    cabal install snap-templates --with-ghc ghc-9.6 --allow-newer

This has caused [a problem in real life](
https://old.reddit.com/r/haskell/comments/16weuto/how_to_install_snap/). At least `template-haskell` needs to be bumped. I didn't check others.

**Comment by andreasabel** [comment]
There is an issue in the project's bug tracker from 2020, apparently the maintainers have lost interest:
- https://github.com/snapframework/snap-templates/issues/22

**Comment by andreasabel** [comment]
This is my suggestion for a revision that will at least not be too restrictive for the next couple of years:
  
 * Changed the executable &#39;snap&#39; component&#39;s library dependency on &#39;bytestring&#39;
                          from `>=0.9.1 && <0.11`
                          to `>=0.9.1 && <1`

 * Changed the executable &#39;snap&#39; component&#39;s library dependency on &#39;containers&#39;
                          from `>=0.3 && <0.7`
                          to `>=0.3 && <1`

 * Changed the executable &#39;snap&#39; component&#39;s library dependency on &#39;hashable&#39;
                          from `>=1.1 && <1.2 || >=1.2.0.6 && <1.3`
                          to `>=1.1 && <2`

 * Changed the executable &#39;snap&#39; component&#39;s library dependency on &#39;template-haskell&#39;
                          from `>=2.2 && <2.15`
                          to `>=2.2 && <3`

 * Changed the executable &#39;snap&#39; component&#39;s library dependency on &#39;text&#39;
                          from `>=0.11 && <1.3`
                          to `>=0.11 && <3`

**Comment by tomjaguarpaw** [comment]
Thank you @andreasabel. I'm not a user of this package myself (I'm just reporting the breakage reported in the Reddit post) so I don't have an opinion on the risks due to too-loose upper bounds. Please take whatever action you deem most appropriate.

**Comment by andreasabel** [comment]
If there is no material interest in a package, we shouldn't waste our time in bumping bounds for maintainers in sleeping pill mode.
There are 15.000 packages on Hackage of which likely 10.000 are trash.  Can spend an eternity on this trash.

I wish Hackage had a coloring scheme that would alert users clearly that they are looking at trash.  Currently you have to have close look at the list of dependencies, know current versions of these by heart and then don't be fooled by the lack of hackage to properly interpret conditionals when displaying dependencies.

**Comment by andreasabel** [comment]
Published these bumps to major-major upper bounds.

**Comment by tomjaguarpaw** [comment]
Thanks, I appreciate it.
