### ISSUE TITLE
Loosen bounds of slist

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell-infra/hackage-trustees#373]
`slist` currently has `base >= 4.10.1.0 && < 4.18` but I confirmed it works with GHC up to 9.8, so should be loosened to `< 4.20`.

https://hackage.haskell.org/package/slist-0.2.1.0

This change is needed to unblock `stan` for GHC 9.6 and 9.8.

**Comment by andreasabel** [comment]
I revised all upper bounds to major-major ones: https://hackage.haskell.org/package/slist-0.2.1.0/revisions/
