### ISSUE TITLE
 warp needs upper bound http2 < 4.2

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell-infra/hackage-trustees#377]
Currently the bound is too loose at `< 5`. See https://github.com/yesodweb/wai/issues/951 for details. This needs to be applied to all versions `3.3.22` to `3.3.28`.

A user has hit this in practice: https://old.reddit.com/r/haskell/comments/17dr5gb/trying_to_install_hoogle_via_cabal_fails_on/

**Comment by phadej** [comment]
```
             9.8.1  9.6.2  9.4.6  9.2.8  9.0.2  8.10.7  8.8.4  8.6.5  8.4.4  8.2.2  8.0.2
warp-3.3.29  NO-IP  OK     OK     OK     OK     OK      OK     OK     NO-IP  NO-IP  NO-IP
warp-3.3.28  NO-IP  FAIL   FAIL   FAIL   FAIL   FAIL    FAIL   FAIL   NO-IP  NO-IP  NO-IP
warp-3.3.27  NO-IP  FAIL   FAIL   FAIL   FAIL   FAIL    FAIL   FAIL   NO-IP  NO-IP  NO-IP
warp-3.3.26  NO-IP  FAIL   FAIL   FAIL   FAIL   FAIL    FAIL   FAIL   NO-IP  NO-IP  NO-IP
warp-3.3.25  NO-IP  FAIL   FAIL   FAIL   FAIL   FAIL    FAIL   FAIL   NO-IP  NO-IP  NO-IP
warp-3.3.24  NO-IP  NO-IP  FAIL   FAIL   FAIL   FAIL    FAIL   FAIL   NO-IP  NO-IP  NO-IP
warp-3.3.23  NO-IP  NO-IP  FAIL   FAIL   FAIL   FAIL    FAIL   FAIL   NO-IP  NO-IP  NO-IP
warp-3.3.22  NO-IP  NO-IP  FAIL   FAIL   FAIL   FAIL    FAIL   FAIL   NO-IP  NO-IP  NO-IP
warp-3.3.21  NO-IP  NO-IP  OK     OK     OK     OK      OK     OK     NO-IP  NO-IP  NO-IP
warp-3.3.20  NO-IP  NO-IP  FAIL   OK     OK     OK      OK     OK     NO-IP  NO-IP  NO-IP
warp-3.3.19  NO-IP  NO-IP  FAIL   OK     OK     OK      OK     OK     NO-IP  NO-IP  NO-IP
warp-3.3.18  NO-IP  NO-IP  FAIL   OK     OK     OK      OK     OK     NO-IP  NO-IP  NO-IP
warp-3.3.17  NO-IP  NO-IP  NO-IP  NO-IP  OK     OK      OK     OK     NO-IP  NO-IP  NO-IP
```

FWIW, the 3.3.18, 3.3.19, 3.3.20 also fail to compiler with GHC-9.4 . warp-3.3.21 changelog says 

> Support GHC 9.4 [#889](https://github.com/yesodweb/wai/pull/889)

So the package maintainers acknowledge that the prior package versions are "broken" (have incorrect metadata)

---

I'm not sure what we can do with maintainers who don't care to do revisions for prior versions (I don't think Kazu is unaware of revisions, but maybe they indeed aren't), even they know there are issues. Especially if they don't learn from their mistakes and start using tight upper bounds. The warp-3.3.29 still has `http2 (>=3.0 && <5),` bound, so eventually may break as well. (EDIT: yet `warp` has some proper bounds, e.g on `wai`, I'm puzzled why such inconsistency).

---

Please try to persuade package maintainer(s) to do the revisions first. Let's wait few weeks, until November 2023.

**Comment by tomjaguarpaw** [comment]
OK. I've made a more specific request at https://github.com/yesodweb/wai/issues/951#issuecomment-1774157753.

**Comment by tomjaguarpaw** [comment]
These revisions have been performed by the maintainer.

**Comment by tomjaguarpaw** [comment]
Tangential question, @phadej, how did you generate the matrix in https://github.com/haskell-infra/hackage-trustees/issues/377#issuecomment-1774156888?

**Comment by andreasabel** [comment]
Using the `phadej/trustee` tool.
