### ISSUE TITLE
Bump bounds for th-extra

### ISSUE THREAD

**Issue by erikd** [haskell-infra/hackage-trustees#379]
I raised a PR in May this year to support `ghc-9.6` and then updated it to support `ghc-9.8`:

https://github.com/mokus0/th-extras/pull/21

**Comment by andreasabel** [comment]
I sent an email to Ryan Trinkle @ryantrinkle concerning this issue.

**Comment by ryantrinkle** [comment]
@andreasabel Thank you for reaching out by email!  It would be great to have more help maintaining this package.

**Comment by erikd** [comment]
@ryantrinkle I would be happy to help maintain this.

I am also **REALLY** keen to see an update on Hackage.

**Comment by andreasabel** [comment]
@erikd : @ryantrinkle has added you to the hackage maintainers.  He is currently asking the repo owner for adding you there as well.

**Comment by andreasabel** [comment]
ATTN: @mokus0

**Comment by erikd** [comment]
I supposedly have the powers to updated this on Hackage (have not tested this yet), but to change the version number in the cabal file, I need GH access. Unless of course I was just to raise a PR to bump the version number (`9.8` support requires a very minor code changes as well as just a dependency bump).

**Comment by andreasabel** [comment]
I am closing this issue now because what Hackage concerns, `th-extra` got an additional maintainer (thanks @erikd) able to make revisions and releases.  Anything remaining is about the github repo.
