### ISSUE TITLE
pqueue

### ISSUE THREAD

**Issue by bergmark** [haskell-infra/hackage-trustees#38]
Email sent 2015-05-27: https://mail.haskell.org/pipermail/haskell-cafe/2015-May/119813.html

**Comment by lspitzner** [comment]
The current maintainer replied and there is hope for a regular transfer of maintainership in the near future (without need for admin intervention).

**Comment by bergmark** [comment]
@lspitzner What's the status? I don't see a new release :(

**Comment by lspitzner** [comment]
@lowasser Ping? It would be cool if you could provide the old repository; the fixing can be done by the new maintainer :-)

@bergmark no further contact from Louis Wasserman, unfortunately. As Louis reported that if at all he would have time at a weekend, it might be worth waiting two more days.

**Comment by cartazio** [comment]
well, @hvr did dig up an old repo copy, heres a copy of that copy http://www.wellposed.com.s3.amazonaws.com/grab-bag/containers-pqueue.tar.xz

it dates from 2010, i dont know how that matches up with the releases on hackage mind you

**Comment by lowasser** [comment]
I would not assume that I still have a copy of the old repository, and I'm
not sure how worthwhile it would be to try to reconstruct it instead of
starting a new repository containing the latest version of pqueue.

**Comment by cartazio** [comment]
@lowasser i just linked a copy :)

**Comment by lspitzner** [comment]
@lowasser i have said so in my initial mail on the mailing list, but you have not replied explicitly, so just to be clear: i would be willing to take over routine maintenance. i'd need you to give me the corresponding rights on hackage (username same as here). i promise to keep the author-tags intact :-)

**Comment by bergmark** [comment]
@lowasser How would you like to proceed? Do you want to stay on as maintainer or split/give maintenance to @lspitzner?

**Comment by lowasser** [comment]
I would be happy to split or give over maintenance, though I have a weak
preference for splitting.

**Comment by bergmark** [comment]
@lowasser cool! easiest  is for you to add @lspitzner at http://hackage.haskell.org/package/pqueue/maintainers/edit , @lspitzner you are lspitzner on hackage too i suppose?

**Comment by lspitzner** [comment]
@lowasser sure, i have no problem with splitting. username is same as here.

**Comment by lowasser** [comment]
Done.

**Comment by lspitzner** [comment]
great! I'll put up a repo on github and make a new release in the next days.

**Comment by bergmark** [comment]
Great, thanks for sorting it out. I'll close this issue.
