### ISSUE TITLE
canonical-json needs a bounds update

### ISSUE THREAD

**Issue by erikd** [haskell-infra/hackage-trustees#384]
In order to build with `ghc-9.8` this package needs some bounds updates.

The PR doing this (https://github.com/well-typed/canonical-json/pull/11) but Hackage still needs an upate (this can be fixed just by bumping the dependencies as per that PR).

**Comment by phadej** [comment]
Please ask maintainers first.

**Comment by erikd** [comment]
I work with Duncan (part of Well Typed). I asked for this over a week ago in (company internal) Slack.

**Comment by dcoutts** [comment]
Done. https://hackage.haskell.org/package/canonical-json-0.6.0.1/revisions/
