### ISSUE TITLE
wl-pprint-annotated news dependency update

### ISSUE THREAD

**Issue by erikd** [haskell-infra/hackage-trustees#385]
To build with `ghc-9.8` this package needs some upper dependency bounds bumped.

A PR has been raised: https://github.com/minad/wl-pprint-annotated/pull/11

Since the only fixes required are dependency bumps, this could be achieved with a Hackage metadata edit.

**Comment by andreasabel** [comment]
Stackage has both `annotated-wl-pprint` and `wl-pprint-annotated`.  Maybe it is good if one of them dies out... 😆

**Comment by erikd** [comment]
I only use Hackage so what Stackage has is irrelevant.

If one of these package is supposed to die, then it should be marked as deprecated.

**Comment by phadej** [comment]
> If one of these package is supposed to die

Both. Use `prettyprinter`. It's annotated Wadler-Leijen prettyprinter.

**Comment by Bodigrim** [comment]
Presumably fixed in https://hackage.haskell.org/package/wl-pprint-annotated-0.1.0.1/revisions/
