### ISSUE TITLE
generic-monoid needs an update to build with ghc-9.8

### ISSUE THREAD

**Issue by erikd** [haskell-infra/hackage-trustees#387]
https://hackage.haskell.org/package/generic-monoid

There is no GH (or similar) repo and no contact email address.

**Comment by gbaz** [comment]
there's a maintainer email address on that page?

**Comment by erikd** [comment]
Sorry, you are correct. Sending email now.

**Comment by endgame** [comment]
Also, now that [`Generically`](https://hackage.haskell.org/package/base-4.19.0.0/docs/GHC-Generics.html#t:Generically) exists and has a [`generically` compat package](https://hackage.haskell.org/package/generically-0.1.1/docs/GHC-Generics-Generically.html), it might be possible to move people away from the `generic-monoid` dependency and have one less thing to maintain?

**Comment by erikd** [comment]
In the code base I work on,it was only being used for the `Monoid` and `Semigroup` instances for a single two element sum type where both elements already had instances. It was easier to just hand write the instances and drop the dependency.

**Comment by erikd** [comment]
This has been fixed on Hackage.
