### ISSUE TITLE
config-ini needs a containers dependency update

### ISSUE THREAD

**Issue by erikd** [haskell-infra/hackage-trustees#389]
PR is https://github.com/aisamanra/config-ini/pull/50

Only a metadata edit needed.

**Comment by andreasabel** [comment]
Is `containers-0.7` already a thing?
This bump does not feel urgent, a priori.

**Comment by erikd** [comment]
The current version of `containers` is `0.7`:  https://hackage.haskell.org/package/containers

**Comment by andreasabel** [comment]
Yes, but there are thousands of packages that don't allow it yet, e.g. `aeson`: https://packdeps.haskellers.com/reverse/containers

**Comment by erikd** [comment]
I currently have:
```
allow-newer:
    aeson:containers
```
in my cabal file.

The way I see it is that the upgrade has to start somewhere. I suspect the widely used packages like `aeson` will be updated at some point, but the less commonly used packages like this one may require some encouragement.

**Comment by phadej** [comment]
This is my personal opinion (i.e. not as a Hackage Trustee):

> The way I see it is that the upgrade has to start somewhere.

With GHC. Currently even GHC `master` is not updated to use `containers-0.7`, so it's possible that GHC-9.10 won't bundle it. Why support `containers-0.7` where a lot of more complex setups (say, the one using `inspection-testing`) won't be able to use that library version anyway?

So far it was GHC which (for example recently) forced adoption of `text-2.0/2.1`, `bytestring-0.11,0.12`, `deepseq-1.5` etc, and that worked out alright, and as `ghc` package depends on `containers` it's really should be one of the first ones adopting the new major version.

**Comment by Bodigrim** [comment]
Fixed in https://hackage.haskell.org/package/config-ini-0.2.7.0/revisions/ (and tested with GHC 9.10 alpha 1).
