### ISSUE TITLE
`monoid-subclasses` needs tighter `base`-bounds

### ISSUE THREAD

**Issue by hvr** [haskell-infra/hackage-trustees#39]
The errors seem to be mostly about incompatible `import`s with `base` and missing a language-extension for recent GHCs, both of which just need more tighter bounds on `base` declared:

![untitled](https://cloud.githubusercontent.com/assets/285533/7901110/1f0c858e-0778-11e5-9c84-291dd079c292.png)

/cc @blamario

**Comment by bergmark** [comment]
Döne
![screen shot 2015-06-30 at 01 38 21](https://cloud.githubusercontent.com/assets/100681/8420946/c00babc4-1ec8-11e5-9bd4-c79de6b57541.png)
