### ISSUE TITLE
Make instance declaration of package AC-Vector compatible with base>=4.9

### ISSUE THREAD

**Issue by jrochel** [haskell-infra/hackage-trustees#391]
https://hackage.haskell.org/package/AC-Vector

I have already submitted a patch to the package maintainer weeks ago, but he has not responded since.
Here's a patch that makes instance declarations compatible with the class structure of base>=4.9.

[AC-Vector-patch.txt](https://github.com/haskell-infra/hackage-trustees/files/13659502/AC-Vector-patch.txt)

Thanks in advance!
Jan

**Comment by andreasabel** [comment]
@jrochel `AC-Vector` looks abandoned.  I think your best bet is a [package takeover](https://wiki.haskell.org/Taking_over_a_package).

**Comment by endgame** [comment]
If you just need the vectors, another alternative would be to write your code against the similar types in [package `linear`](https://hackage.haskell.org/package/linear).

**Comment by Bodigrim** [comment]
I assume it's fixed now in https://hackage.haskell.org/package/AC-Vector-2.4.0.

**Comment by andreasabel** [comment]
@jrochel has taken this package.
