### ISSUE TITLE
commutative-semigroups needs a base dependency bump

### ISSUE THREAD

**Issue by blamario** [haskell-infra/hackage-trustees#392]
https://hackage.haskell.org/package/commutative-semigroups

The issue has been raised a month and half ago: https://github.com/obsidiansystems/commutative-semigroups/issues/13

**Comment by phadej** [comment]
See e.g. https://github.com/haskell-infra/hackage-trustees/issues/379#issuecomment-1784726763

It seems you'll have a lot better luck reaching Obsidian folks by email than via GitHub.

**Comment by ryantrinkle** [comment]
@blamario Thanks for reaching out; we're looking into it.  Also, if you would like to be a maintainer of this package, either on github or Hackage, we would appreciate the help!

**Comment by blamario** [comment]
Sure, I can do that. This package is tiny so I can't see it becoming too much of a burden, and it's one of my packages' dependencies. You can add me to the maintainer list. I suspect @jonathanknowles would be available as well.

**Comment by jonathanknowles** [comment]
@ryantrinkle if you still need an extra hand, I would be happy to help out. ([`commutative-semigroups`](https://hackage.haskell.org/package/commutative-semigroups) is also a dependency of my packages.) Thanks again!

**Comment by andreasabel** [comment]
@blamario is the new maintainer.
