### ISSUE TITLE
unix-bytestring needs a Hackage metadata edit to build with ghc-9.8

### ISSUE THREAD

**Issue by erikd** [haskell-infra/hackage-trustees#393]
PR is https://github.com/wrengr/unix-bytestring/pull/46

Would have sent an email but the commits are all attributed to an `@users.noreply.github.com>` email address.

**Comment by erikd** [comment]
I emailed @wrengr at the cpan.org email address I found on Hackage.

**Comment by andreasabel** [comment]
I made the revision.
