### ISSUE TITLE
Bump Bounds on `hexpat`

### ISSUE THREAD

**Issue by prikhi** [haskell-infra/hackage-trustees#394]
`hexpat` fails to build with `deepseq==1.5.0.0`. I have a PR up that is a continuation of my previous trustee request #363:

https://github.com/the-real-blackh/hexpat/pull/14, specifically https://github.com/the-real-blackh/hexpat/pull/14/commits/c21e7908a061ebb949e5c04f94298e10c9080c0e

Note the test-suite is a separate sub-package & requires code changes / a non-maintainer upload if we want to keep it compiling with GHC 9.8(it continues to compile for GHC 9.6 with no deepseq 1.5 contraint).

**Comment by prikhi** [comment]
Can we also get a bump to allow `text-2.1`  instead of `>= 2 && < 2.1`. My tests were performed w/ `text-2.1`.

**Comment by andreasabel** [comment]
@prikhi  I checked the repo and the last commit was 7 years ago.  The package looks unmaintained.  Maybe you want to take over the package? https://wiki.haskell.org/Taking_over_a_package

**Comment by prikhi** [comment]
Heya, I can look into taking over for basic maintenance, I've tried emailing the author but can't find a valid address.

It would be nice to at least get the text & deepseq bumps in, as it's blocking a few things from GHC 9.8 & stackage nightly, but up to y'all.

**Comment by andreasabel** [comment]
@prikhi : Great that you are considering a take over!  If there is no email address to be found, you could simply post your take over intention to the haskell-cafe mailing list.

If it is urgent, I can do revisions one more time, but I would like to see the takeover process kicked off first so it is clear we can reach a sustainable solution...

**Comment by prikhi** [comment]
https://mail.haskell.org/pipermail/haskell-cafe/2024-February/136607.html

**Comment by andreasabel** [comment]
I revised the bounds to latest.  Thanks for taking over this package, @prikhi!

**Comment by prikhi** [comment]
Thanks! I fired off an email to hackage-admin so hopefully that's the last revision y'all need to do for me :sweat_smile:

**Comment by prikhi** [comment]
Thank you! Transfer process is complete so we can safely close this now.
