### ISSUE TITLE
Can the latest `filepath` revise for `base-4.20` (GHC 9.10)?

### ISSUE THREAD

**Issue by ulysses4ever** [haskell-infra/hackage-trustees#397]
Over in the Cabal project we're stuck with this when trying to move our CI/testsuite to GHC 9.10. Our setup is complicated, and we can't use `allow-newer: filepath:base`.

- https://github.com/haskell/cabal/pull/9914#issuecomment-2078058419
- https://github.com/haskell/filepath/issues/230

**Comment by hasufell** [comment]
Metadata changes are handled by the maintainers, unless said maintainers are unresponsive: https://github.com/haskell-infra/hackage-trustees/blob/master/policy.md#policyprocedure-1

> In the first instance they should get maintainers to make changes. If maintainers are not available then they should use their judgement and consult with each other when in doubt.
