### ISSUE TITLE
uvector does not compile with ghc-9.10.1

### ISSUE THREAD

**Issue by erikd** [haskell-infra/hackage-trustees#398]
Getting the following compile errror:
```
Configuring uvector-0.1.1.1...
Preprocessing library for uvector-0.1.1.1..
Building library for uvector-0.1.1.1..
on the commandline: warning: [GHC-53692] [-Wdeprecated-flags]
    -fvia-C is deprecated: The -fvia-C flag does nothing; it will be removed in a future GHC release

on the commandline: warning: [GHC-53692] [-Wdeprecated-flags]
    -fglasgow-exts is deprecated: Use individual extensions instead

ghc: unrecognised flag: -fno-method-sharing

Usage: For basic information, try the `--help' option.
```
The package https://hackage.haskell.org/package/uvector was last updated (by HVR) in December on 2014. 

The homepage linked in the cabal file no longer exists.

There is no code repo listed in the cabal file.

The maintainer email address is no longer valid.

**Comment by gbaz** [comment]
uvector is deprecated in favor of vector, but it does not say so in the metadata just the description text. I will add the deprecation to the main package metatdata as well

**Comment by Bodigrim** [comment]
@erikd is there anything else to do here? Unless you want to take over `uvector`, I'd suggest to close.

**Comment by erikd** [comment]
Yes, closing this is the best idea.
