### ISSUE TITLE
Emergency ansi-wl-pprint NMU for GHC 7.10.1 compat

### ISSUE THREAD

**Issue by hvr** [haskell-infra/hackage-trustees#4]
See also https://github.com/batterseapower/ansi-wl-pprint/pull/11

**Comment by ekmett** [comment]
We reached out to @batterseapower ~9 days ago in advance of the release candidate, both through github and through email.

We already have a precedent of adopting one of his packages: https://github.com/haskell/test-framework

The package is in very wide use, especially when you consider transitive dependencies: http://packdeps.haskellers.com/reverse/ansi-wl-pprint

I say we should pull the trigger and do this.

**Comment by cartazio** [comment]
I think given the scope of impact, and the lack of response in reaching him
for lower impact things the past few months, its appropriate to upload a
bug fix release as long as several CLC/trustee folks sign off before we
upload

**Comment by tibbe** [comment]
I think we should go ahead. Where do we put the patches so they can be pushed upstream eventually? Shall we put the repo under the haskell GitHub org? We should also email @batterseapower and let him know what we did.

**Comment by ekmett** [comment]
Pulling a (possibly temporary) fork into the haskell github org seems like the right direction.

**Comment by dcoutts** [comment]
So the trustee's tentative policy (in @bergmark's initial proposal) is to give authors two weeks in this situation. I worry that's a little low even (or that other authors will think it's a little low). So I suggest we prepare but don't actually upload until that two weeks has passed, which if I'm counting correctly is this coming Sunday.

**Comment by tibbe** [comment]
We should also try to assess the author's general presence in the community (i.e. has he/she been absent for a while.) I definitely take longer than 2 week vacations and I'd hate if someone hijacked my packages while I was lying on the beach.

**Comment by ekmett** [comment]
In general I agree. In this particular case, @batterseapower has been MIA for over a year. If you check his github history, he hasn't touched a single Haskell project in that entire time. 

We can delay if you want, but it means that we basically burn another 4-5 days of effective testing with RC3, which already had a vanishingly small release cycle, during which nobody can build any of the testing or benchmarking tools, as both `test-framework` and `criterion` depend on `ansi-wl-pprint`.

**Comment by tibbe** [comment]
Please don't delay. What I meant it's just that. We know he is mia.

**Comment by cartazio** [comment]
yes, in general the process should be 1+ (or even 2-6+ months) for things, but we know he's been mia for a year, and many folks have made a best effort attempt to reach him at various points in the past 6 months with no responses, so in that case, we have a strong consensus that 

1) the maintainer has not only been inactive for a long period of time, but more *importantly*
2) has been impossible to reach for over 6 (perhaps even 12 months)

it is those two *combined* that I think allow exceptional usage of trustee/admin powers, PLUS multiple CLC/Trustees being in clear agreement. (so i think we're actually erring on the conservative side )

**Comment by cartazio** [comment]
point being: lets do this, and i'm willing to take the blame if its a bad call :)

**Comment by 23Skidoo** [comment]
+1 on not delaying.

**Comment by ndmitchell** [comment]
I know Max, he's a nice guy (although I've not been able to raise him in the last week) - he's not going to object to an obviously correct fix. Again, I'd also be willing to take the blame, and I think in future when there is no one who thinks its the wrong thing to do, we should probably be more keen to take action much quicker. If I'm on a beach without internet for two weeks and one of my packages requires a one-character fix I'd like the community to just go ahead, and if I really care I'll revert it on my return. A simple fix is not the same as taking a package over permanently.

**Comment by hvr** [comment]
As over 2w have passed without reaction from @batterseapower I've gone ahead an uploaded http://hackage.haskell.org/package/ansi-wl-pprint-0.6.7.2

While at it, I also edited the `.cabal` files for previous releases to tighten upper bounds where needed

**Comment by ekmett** [comment]
Looks like we delayed anyways.

**Comment by hvr** [comment]
for the record, @ekmett initiated package-takeover via https://mail.haskell.org/pipermail/libraries/2015-March/025352.html
