### ISSUE TITLE
regex-tdfa-text doesn't build on GHC 7.10

### ISSUE THREAD

**Issue by bergmark** [haskell-infra/hackage-trustees#40]
Issue reported May 3: http://hub.darcs.net/shelarcy/regex-tdfa-text/issue/1
Reverse dependencies: http://packdeps.haskellers.com/reverse/regex-tdfa-text

For now let's not add an upper bound since @hamishmack has recommended users to install the package by passing -XFlexibleContexts to cabal-install.

To fix, we only need to add a type signature or enable FlexibleContexts.

Ping @hamishmack

**Comment by bergmark** [comment]
I sent the initial e-mail about doing an NMU to the maintainer.

**Comment by bergmark** [comment]
I sent the second email to the maintainer.

**Comment by bergmark** [comment]
Can a trustee review this please?
https://github.com/hackage-trustees/regex-tdfa-text/commit/bf524850e3d89bf75362783185f5342ace1e7d6e

**Comment by bergmark** [comment]
Bump!

**Comment by hvr** [comment]
@bergmark LGTM

**Comment by bergmark** [comment]
Thanks hvr. I sent an e-mail to the admins.

**Comment by hesselink** [comment]
I've added you to the maintainers for regex-tdfa-text.

**Comment by bergmark** [comment]
Uploaded http://hackage.haskell.org/package/regex-tdfa-text-1.0.0.3
