### ISSUE TITLE
cborg: Requires a bump to the base dependency

### ISSUE THREAD

**Issue by erikd** [haskell-infra/hackage-trustees#400]
Git `HEAD` for `cborg` (and `serialize`) has already been fixed. This just needs a Hackage metadata edit.

I have already validated that this works by adding the following to the `cabal.project` file of my project and compiling with `ghc-9.10`:
```
allow-newer:
  , cborg:base
```
 
I raised the PR to fix this and its has been merged, I have messaged @dcoutts about a Hackage metadata edit and he has said he would do it, but must be busy.

As a Hackage Trustee I can do this, but will not do it without approval.

**Comment by andreasabel** [comment]
- https://github.com/well-typed/cborg/pull/336

**Comment by erikd** [comment]
@andreasabel Should I just do the required Hackage metadata edit?

**Comment by andreasabel** [comment]
@erikd Version relaxations are in scope of Hackage trustee work as long as the maintainer does not oppose and is informed about it (e.g. by an issue or comment on an issue or PR).
So, yes, please go ahead!

**Comment by erikd** [comment]
Hackage metadata updated. Will wait until the changes have propagated and then test,

**Comment by erikd** [comment]
Seems to work. Closing this.
