### ISSUE TITLE
tasty-hedgehog: Needs upper bounds bumped

### ISSUE THREAD

**Issue by erikd** [haskell-infra/hackage-trustees#404]
PR has been merged: https://github.com/qfpl/tasty-hedgehog/pull/77

Have DMed maintainer (in Slack channel we are both in).

Has not yet been fixed on Hackage.

**Comment by mbg** [comment]
Updated on Hackage with a [metadata revision](https://hackage.haskell.org/package/tasty-hedgehog-1.4.0.2/revisions/).

**Comment by erikd** [comment]
Confirmed!
