### ISSUE TITLE
haskeline: Needs a bounds upper bounds fix

### ISSUE THREAD

**Issue by erikd** [haskell-infra/hackage-trustees#405]
Have raised a PR: https://github.com/judah/haskeline/pull/188

Have emailed the maintainer.

**Comment by phadej** [comment]
`haskeline` is bundled with GHC. ping @bgamari

**Comment by erikd** [comment]
I was using an SRP for haskeline:
```
source-repository-package
  type: git
  location: https://github.com/erikd/haskeline
  tag: 6758c914603b072aba26d2bc6ed59d0919fbd516
```
But now that is no longer necessary. The package on Hackage has not changed, there is no `allow-newer` stanza mentioning `haskeline`, it is still being used in my project, the GHC has not changed, but everything compiles fine.

I am confused.

**Comment by hsenag** [comment]
@erikd I just double-checked and I definitely still need `allow-newer: haskeline:base` to get a build plan.

**Comment by Bodigrim** [comment]
As much as I can tell, the package has been revised to allow `base-4.20`, thus closing.
