### ISSUE TITLE
dictionary-sharing: Bump upper bounds

### ISSUE THREAD

**Issue by erikd** [haskell-infra/hackage-trustees#406]
PR is https://github.com/JonasDuregard/dictionary-sharing/pull/3

Have sent email to the maintainer.

**Comment by erikd** [comment]
This package is causing CI failure (for `ghc-9.10`) of another package: https://github.com/size-based/size-based/pull/2 .

**Comment by erikd** [comment]
No response from maintainer yet.

**Comment by Bodigrim** [comment]
@erikd I assume you have [enough rights](https://hackage.haskell.org/packages/trustees/) to make a revision yourself?..

**Comment by erikd** [comment]
@Bodigrim I do and I know how to do it. Should I just go ahead and do it?

**Comment by Bodigrim** [comment]
I think you've done more than enough to urge the maintainer, it's fine to go ahead yourself.

**Comment by erikd** [comment]
Hackage metadata edit done.

**Comment by Bodigrim** [comment]
@erikd for packages with inactive maintainers (e. g., no or very occasional GitHub activity), I'd often make a revision shortly after raising a PR.
