### ISSUE TITLE
ixset-typed: minor patch needed to build with current TH

### ISSUE THREAD

**Issue by clinty** [haskell-infra/hackage-trustees#408]
https://github.com/well-typed/ixset-typed/pull/21 is subsumed by https://github.com/well-typed/ixset-typed/pull/23

**Comment by andreasabel** [comment]
@clinty This can't be fixed by a revision, and we'd rather avoid a NMU (non-maintainer upload).
Can you try to get hold of the maintainers by other channels (e.g. email)?
If they are no longer interested to maintain this package, a takeover would be the way forward.

**Comment by clinty** [comment]
@kosmikus merged the patch.  Now a release is needed.
