### ISSUE TITLE
swagger2: Needs many bumps

### ISSUE THREAD

**Issue by ysangkok** [haskell-infra/hackage-trustees#412]
I have this PR that I have tested:

* https://github.com/GetShopTV/swagger2/pull/255

The library doesn't require any source changes, so it would be nice if trustees applied these bumps. I emailed the maintainer a couple of days ago but I have received no reply. And I have pinged multiple times on Github.

**Comment by andreasabel** [comment]
Let's wait a bit to give @swamp-agr time to act.

**Comment by swamp-agr** [comment]
(Copying message here as it might be relevant)

Thank you for pinging me. I have merged PR just now. 

For two more weeks I will have no access to laptop to make a release on Hackage, unfortunately. If it's a blocker for you, please let me know so we can try to find a solution to make a release.

**Comment by ysangkok** [comment]
Solved by the release of v2.8.9, sorry for the disturbance
