### ISSUE TITLE
unordered-containers: Allow hashable-1.5 

### ISSUE THREAD

**Issue by erikd** [haskell-infra/hackage-trustees#414]
Issue has already been open for two weeks: https://github.com/haskell-unordered-containers/unordered-containers/issues/492

**Comment by andreasabel** [comment]
@erikd: I do not think it is in the spirit of @phadej to bypass the maintainers on this...

**Comment by erikd** [comment]
I am just pointing out the packages that are not being updated and causing me dificulty.

The `unordered-containers` issue is blocking https://github.com/haskellari/postgresql-simple/issues/139 which I raised 6 weeks ago. `postgresql-simple` sits very low in the dependency stack of a number of projects I work on,

I am using an `allow-newer` stanza in my `cabal.project` files in these projects but the maintainers would prefer not to merge my PRs (and I agree with them) until the `allow-newer` stanzas are removed.

Getting `unordered-containers` and `postgresql-simple` fixed would enable me to get PRs for a number of other projects pushed through. At the moment they are all in a holding pattern and I am expending time and effort rebasing these projects on a bi-weekly basis..

**Comment by andreasabel** [comment]
I commented there: https://github.com/haskellari/postgresql-simple/issues/139#issuecomment-2238554887

**Comment by phadej** [comment]
> maintainers on this...

@treeowl is a maintainer of e.g. `containers`, so hopefully he'll eventually appear and do stuff on `containers` and `unordered-containers`, their issue lists are not shrinking.

I mean, @andreasabel, you could make a revision, @Bodigrim already did one for template-haskell. BUt I don't think this is a sustainable solution.

**Comment by treeowl** [comment]
I'm here. I've just been very tied up with a family medical issue for the last couple months.

**Comment by phadej** [comment]
@treeowl I'm sorry to hear about that. Take the time you need, I'm not in a hurry to update stuff.

**Comment by erikd** [comment]
This has been fixed on Hackage.
