### ISSUE TITLE
hedgehog-classes bumps

### ISSUE THREAD

**Issue by ysangkok** [haskell-infra/hackage-trustees#418]
I request that the trustees perform the bumps as a revision: https://hackage.haskell.org/package/hedgehog-classes-0.2.5.4/revisions/

The bumps to be performed are from:

* https://github.com/hedgehogqa/haskell-hedgehog-classes/pull/59

This could make us get progress on getting vector-circular back in Stackage. And hgeometry too.

**Comment by erikd** [comment]
You should raise an issue or a PR on the Github repo. If you get no response in a week or so, email the maintainers.

Our processes are detailed [here](https://github.com/haskell-infra/hackage-trustees/blob/master/policy.md).

**Comment by ysangkok** [comment]
All right, thank you!

**Comment by erikd** [comment]
Would be perfectly fine to leave this open until the issue is fixed.

**Comment by andreasabel** [comment]
> You should raise an issue or a PR on the Github repo. If you get no response in a week or so, email the maintainers.

Such revision request exists since 2024-09-04 at https://github.com/hedgehogqa/haskell-hedgehog-classes/pull/59#issuecomment-2329310909

I suppose @chessai will answer it, let's give it a few more days.

**Comment by chessai** [comment]
Done

**Comment by ysangkok** [comment]
@chessai, it seems you only bumped hedgehog and primitive. The linked PR contains bumps to containers and base too. The reason I didn't put them in the cabal invocation in the PR description, is because they are implied by the selection of GHC, since they are boot libraries. I would be so grateful if it would be possible for you to bump those too.

**Comment by chessai** [comment]
> @chessai, it seems you only bumped hedgehog and primitive. The linked PR contains bumps to containers and base too. The reason I didn't put them in the cabal invocation in the PR description, is because they are implied by the selection of GHC, since they are boot libraries. I would be so grateful if it would be possible for you to bump those too.

Done, sorry for the mixup
