### ISSUE TITLE
ChasingBottoms: Needs bump on base dependency

### ISSUE THREAD

**Issue by erikd** [haskell-infra/hackage-trustees#420]
This packages is in the darcs revision control system and has no lssue tracker listed on the Hackage page.

Currently building other packages with:
```
allow-newer:
  , ChasingBottoms:base
```

P.S. (Andreas): Blocked on:
- [x] https://github.com/haskellari/splitmix/issues/89

**Comment by andreasabel** [comment]
`ChasingBottoms` is blocked on `splitmix`:
> [__3] rejecting: splitmix-0.1.0.5 (conflict: base==4.21.0.0/installed-cc73, splitmix => base>=4.3 && <4.21)

**Comment by erikd** [comment]
I got around that with an `allow-newer` for `split-mix`.

**Comment by andreasabel** [comment]
I made a revision to bump the base bound to `< 4.22`.  
So we can close this issue, the remaining one is with `splitmix`.
