### ISSUE TITLE
'temporary' package takeover

### ISSUE THREAD

**Issue by hesselink** [haskell-infra/hackage-trustees#43]
Request by Mateusz Kowalczyk [here](https://mail.haskell.org/pipermail/libraries/2015-July/025990.html). Roman Cheplyaka also asked about takeover [in May 2014](https://mail.haskell.org/pipermail/libraries/2014-May/022958.html). Max Bolingbroke hasn't been active [for a long time](https://mail.haskell.org/pipermail/libraries/2015-April/025570.html) so I think transferring the package on Monday the 27th is reasonable, even though it's before the 2-6 week term listed in [the usual timetable](https://wiki.haskell.org/Taking_over_a_package).

**Comment by bergmark** [comment]
@Fuuzetsu note that @feuerbach has a fork, temporary-rc, perhaps it contains things that can be merged into temporary?

**Comment by Fuuzetsu** [comment]
It does not, they are at this point pretty much the same except one has a maintainer present and one doesn't seem to. The point of the takeover is to give `temporary` a maintainer so we can stop using `temporary-rc` and cause package import problems for any project using `tasty` &c.

See https://github.com/feuerbach/temporary/issues/1

**Comment by bergmark** [comment]
Cool!

**Comment by Fuuzetsu** [comment]
It's now Monday and got only positive feedback on `libraries@`, hopefully we can conclude the takeover today.

**Comment by hesselink** [comment]
Yes, thanks for the reminder. I've added you to the maintainers of `temporary`.
