### ISSUE TITLE
glpk-hs takeover

### ISSUE THREAD

**Issue by bergmark** [haskell-infra/hackage-trustees#44]
Requested by @jyp 2015-07-24: https://mail.haskell.org/pipermail/libraries/2015-July/026023.html

**Comment by bergmark** [comment]
Also pinging @lowasser

**Comment by lowasser** [comment]
I'm pretty sure I approved that request

**Comment by lowasser** [comment]
Oh, wait, that was the pqueue package.  I approve this takeover too.

**Comment by jyp** [comment]
Ok, my username is JeanPhilippeBernardy

**Comment by bergmark** [comment]
Thanks for letting us know @lowasser , can you please add @jyp at http://hackage.haskell.org/package/glpk-hs/maintainers/edit?

**Comment by lowasser** [comment]
Done.

**Comment by bergmark** [comment]
Thanks!
Happy hacking @jyp
