### ISSUE TITLE
erlang takeover

### ISSUE THREAD

**Issue by bergmark** [haskell-infra/hackage-trustees#45]
Requested by Poór Artúr on 2015-07-30 here: https://mail.haskell.org/pipermail/haskell-cafe/2015-July/120592.html

Pinging @esessoms

**Comment by hvr** [comment]
lol... at first I thought this was about taking over https://github.com/erlang =)

**Comment by hvr** [comment]
@bergmark I think at this point we can move forward?

**Comment by gombocarti** [comment]
I am writing an email to the Hackage administrators to grant maintenance rights.

**Comment by hesselink** [comment]
I've added @gombocarti to the maintainers or erlang.
