### ISSUE TITLE
pandoc-citeproc probably works with vector-0.11

### ISSUE THREAD

**Issue by kolmodin** [haskell-infra/hackage-trustees#47]
I tried to install `pandoc` and `hakyll` with this command line: `cabal install pandoc hakyll`.
Cabal resolved the deps, and but the result was not great.
`hakyll` depends on `pandoc-citeproc`. `pandoc-citeproc` requires `vector-0.10.*`.
Cabal ended up choosing `vector-0.11`, and thus could not install `pandoc-citeproc`, and therefore a really old version of `hakyll` that doesn't depend on `pandoc-citeproc`.

If all versions of pandoc-citeproc could be relaxed a bit with regard to vector, I think cabal would find a good install plan without additional `--constraint`s.
How about `vector >= 0.10.* && <= 0.11.*` ?

`pandoc-citeproc` has already updated the git repository to allow vector-0.11, but no new version is yet released.

**Comment by bergmark** [comment]
Sorry for the delay, I now see John released pandoc-citeproc-0.7.3 allowing vector-0.11.
