### ISSUE TITLE
hackage-diff needs less strict "base" version bounds

### ISSUE THREAD

**Issue by svenpanne** [haskell-infra/hackage-trustees#48]
hackage-diff needs less strict version bounds to be compatible with GHC-7.10.2's `base`. As it is, the bounds are `base >=4.7 && < 4.8`, and cabal finds no build plan with 7.10.2. So my proposal is to change this to `base >=4.6 && < 4.9`, as the lower bound can be relaxed, too, see: https://github.com/blitzcode/hackage-diff/issues/3. The project is dormant for a year now, and the author hasn't responded yet.

BTW: Is there a similar, more maintained tool?

**Comment by bergmark** [comment]
I'll take a closer look

**Comment by bergmark** [comment]
Revised: http://hackage.haskell.org/package/hackage-diff-0.1.0.0/revisions/

Waiting for the matrix builder then I'll close this.

**Comment by bergmark** [comment]
![screen shot 2015-08-22 at 20 56 42](https://cloud.githubusercontent.com/assets/100681/9425424/54988d9a-4910-11e5-98ed-f9f481fe0576.png)
