### ISSUE TITLE
tar test suite works well with tasty-0.11

### ISSUE THREAD

**Issue by phadej** [haskell-infra/hackage-trustees#49]
Motivation: https://github.com/fpco/stackage/issues/817

**Comment by gbaz** [comment]
Can you expand on what the issue is. Do you want something changed or bumped or...?

**Comment by phadej** [comment]
Can the `tasty` bound be changed from
```
tasty            == 0.10.*
```
to
```
to `tasty            >= 0.10 && <0.12,
```

**Comment by hvr** [comment]
Please migrate this to https://github.com/haskell/tar/issues

**Comment by phadej** [comment]
Migrated: https://github.com/haskell/tar/pull/4
