### ISSUE TITLE
The dependency bounds for vector-th-unbox needs an adjustment.

### ISSUE THREAD

**Issue by MaiaVictor** [haskell-infra/hackage-trustees#50]
As detailed by `dfeuer` on [this SO question](http://stackoverflow.com/questions/32896516/ghc-7-10-2-warning-when-deriving-unbox-instance-using-data-vector-unboxed-derivi/32896649?noredirect=1#comment53622943_32896649), 

> The vector-th-unboxed package that provides the template you're using has not been updated since basicInitialize was added to the Data.Vector.Generic.Mutable.Base.MVector class.

`vector-th-unbox` needs an adjustment on its dependency bounds. There is a [pull request](https://github.com/liyang/vector-th-unbox/pull/10) to fix this issue, but the maintainer hasn't accepted it yet.

**Comment by treeowl** [comment]
Specifically, it looks like current versions of `vector-th-unbox` need `vector < 0.11`. There's a long-open pull request to fix this, but the maintainer hasn't responded in some time. It might help for a trustee to attempt contact.

**Comment by treeowl** [comment]
I've just sent an email to the maintainer.

**Comment by hvr** [comment]
I take it that *all* released versions require a `vector < 0.11` upper bound?

**Comment by treeowl** [comment]
I imagine so. It provides TH to make instances, and there's a new mandatory
method. I haven't dug through to be sure all versions instantiate the
relevant class (and I don't have the infrastructure to test), but I imagine
so.

**Comment by bergmark** [comment]
Does anyone have a package or example where this causes compilation failure?

**Comment by hvr** [comment]
Looking at the code, failing to define the `MVector(basicInitialize)` method breaks many usages (mostly the "safe" operations) of said `MVector` instances. However, the `Vector` instances seem not affected by this bug.

So restricting the bounds *without* also uploading a patch-level release for the affected major versions is risky (as there may be packages affected that don't use the broken `MVector` operations, and whose install-plan space would be reduced for no good reason).

Btw, the preferred version usage of `vector-th-unbox` seems strange:

 - https://hackage.haskell.org/package/vector-th-unbox/preferred

**Comment by bergmark** [comment]
I sent an e-mail to the maintainer so we can do an NMU in two weeks if necessary.

**Comment by bergmark** [comment]
Sent a second e-mail, I'll prepare the NMU soon.

**Comment by liyang** [comment]
Apologies. I was hiding from the internets for a bit.

Dealing with it now.

**Comment by liyang** [comment]
> Btw, the preferred version usage of vector-th-unbox seems strange:

@hvr Right… I'm not sure how I'm supposed to use that feature. I was playing around with it and decided it might be a good idea to deprecate all the non-latest bugfix versions of each minor version.

**Comment by liyang** [comment]
> I take it that all released versions require a vector < 0.11 upper bound?

I've updated all the preferred versions with the above constraint.

**Comment by bergmark** [comment]
Thanks for fixing this!

> I've updated all the preferred versions with the above constraint. I suspect this is not the easiest way to achieve the desired effect though. Perhaps I should always specify upper version bounds on vector and template-haskell (as I've been reading elsewhere)?

Having upper bounds is what the PVP mandates. I do this for all my dependencies and if something slips through the cracks you can also edit version ranges for existing releases. Preferred versions is only a poke from Cabal, e.g. if all preferred versions would break other local packages it will probably use an undeprecated version.
