### ISSUE TITLE
allow hyperloglog 0.3.4 to build with vector 0.11.*

### ISSUE THREAD

**Issue by cartazio** [haskell-infra/hackage-trustees#56]
we've tested it out at work and it builds fine, and I recall @kmett giving me the ok to do that metadata change when i spoke with him about it a few months ago.

documenting the change action here

**Comment by phadej** [comment]
Matrix agrees, this is ok: http://matrix.hackage.haskell.org/package/hyperloglog.

**Comment by phadej** [comment]
Btw, Edward is `ekmett` (no necessary pinging) on GitHub.

**Comment by cartazio** [comment]
did this a while ago, closing
