### ISSUE TITLE
`amazonka-core` needs upper bounds on `http-types`

### ISSUE THREAD

**Issue by hvr** [haskell-infra/hackage-trustees#57]
See http://matrix.hackage.haskell.org/package/amazonka-core

Releases prior to 1.3.3.1 started getting a nameclash a couple of weeks ago. Most likely an upper bound on `http-types` is missing

```
src/Network/AWS/Sign/V4/Base.hs:98:15:
    Ambiguous occurrence ‘hHost’
    It could refer to either ‘Network.AWS.Data.Headers.hHost’,
                             imported from ‘Network.AWS.Data.Headers’ at src/Network/AWS/Sign/V4/Base.hs:36:1-41
                             (and originally defined at src/Network/AWS/Data/Headers.hs:75:1-5)
                          or ‘Network.HTTP.Types.Header.hHost’,
                             imported from ‘Network.HTTP.Types.Header’ at src/Network/AWS/Sign/V4/Base.hs:44:1-42
xcabal: Error: some packages failed to install:
amazonka-core-1.3.3 failed during the building phase. The exception was:
ExitFailure 1
```

/cc @brendanhay

**Comment by brendanhay** [comment]
Looks like constraining to `http-types < 0.9` is needed.

**Comment by brendanhay** [comment]
I've gone through and added the upper bound to all `< 1.3.3.1` `amazonka-core` package metadata. I'll keep an eye on the build matrix. If someone with auth like poking it so it gets queued so I can verify the changes, that'd be appreciated.

**Comment by hvr** [comment]
@brendanhay will do... I hope you knew about https://github.com/hvr/hackage-cli which makes mass-editing the meta-data a bit more convenient... :-)

**Comment by brendanhay** [comment]
No, I wasn't aware of that - I merely cursed under my breath at the 50 open tabs. :fire:

**Comment by hvr** [comment]
@brendanhay if you look at http://matrix.hackage.haskell.org/package/amazonka-core now, only `0.3.{4,5,6}` have namespace issues left, everything else went back to green! :+1:

**Comment by brendanhay** [comment]
I'm getting `404` errors on all the `http://matrix.hackage.haskell.org/package/*` pages and can't actually see the build error!

**Comment by brendanhay** [comment]
The ghost in the machine(s) have mysteriously decided to cooperate and a `lens < 4.13` upper bound has been added to the `0.3.{4,5,7}` versions' package metadata.

**Comment by hvr** [comment]
the build is just overloaded it seems... I need to find a way to dynamically throttle the parallelism if ram gets tight

**Comment by bergmark** [comment]
Issue cleanup time! Is there anything left to do here @hvr? If not let's close this.
