### ISSUE TITLE
hastache needs version bounds fixup

### ISSUE THREAD

**Issue by hvr** [haskell-infra/hackage-trustees#58]
already filed upstream at https://github.com/lymar/hastache/pull/53 over two weeks ago

@bos pinged me about it as it's blocking criterion, I'm on it

**Comment by hvr** [comment]
I've relaxed the upper bound on `base`, see https://hackage.haskell.org/package/hastache-0.6.1/revisions/

**Comment by bergmark** [comment]
Issue cleanup time! Is there anything left to do here @hvr? If not let's close this.

**Comment by RyanGlScott** [comment]
It might be time to perform another bounds update on `hastache`, since GHC 8.2 is imminent, and it looks like https://github.com/lymar/hastache/pull/56 is going to be merged/released anytime soon.

**Comment by hvr** [comment]
I can take care of it later today; at this point, hastache seems basically to have been abandoned by its author (it's marked deprecated on Hackage too). So Trustees can just take care to perform the occasional meta-data maintainance....

**Comment by hvr** [comment]
done; works w/ GHC 8.2.1 now

**Comment by randen** [comment]
Would it be possible to push the base bounds a bit to support GHC 8.4.3 (maybe <=4.11, rather than <4.11)?  We could switch over the another package for mustache support, but hastache is working perfectly fine for us (and seems to have the most downloads over the years, of all the variants), so it seems like it would be worth it to keep warm.

**Comment by phadej** [comment]
See https://github.com/haskell-infra/hackage-trustees/issues/161, I assume some code-level changes are needed to support SMP, I haven't checked.

If you really care about `hastache` I'd suggest to take over package. My gut feeling however says that switching to `microstache` or `stache` is better long term.
