### ISSUE TITLE
effect-monad needs an upper bound on type-level-sets

### ISSUE THREAD

**Issue by thomie** [haskell-infra/hackage-trustees#59]
`cabal install effect-monad` fails with
```
src/Control/Effect/Reader.hs:33:8:
    Not in scope: type constructor or class ‘Var’
```

The fix is to add an upperbound on `type-level-sets`:
```
type-level-sets >= 0.5 && < 0.6
```

I opened a [pull request](https://github.com/dorchard/effect-monad/pull/5) one month ago, but it has been getting ignored.

It is not critical to fix, `effect-monad` doesn't have any [reverse dependencies](http://packdeps.haskellers.com/reverse/effect-monad) on hackage besides `acme-everything`.

**Comment by bergmark** [comment]
Too slow @phadej ;-) I've added bounds

**Comment by thomie** [comment]
Thanks.
