### ISSUE TITLE
atto-lisp has restrictive blaze-builder upper bounds

### ISSUE THREAD

**Issue by snoyberg** [haskell-infra/hackage-trustees#6]
* Original report: https://github.com/fpco/stackage/issues/442
* Second report: https://github.com/nominolo/atto-lisp/issues/16
* Pull request: https://github.com/nominolo/atto-lisp/pull/17

This is just a straightforward upper bound relaxation, and requires no code change.

**Comment by bergmark** [comment]
Applied, http://hackage.haskell.org/package/atto-lisp-0.2.2/revisions/ .
