### ISSUE TITLE
NMU for vector-th-unbox

### ISSUE THREAD

**Issue by hvr** [haskell-infra/hackage-trustees#60]
@liyang seems unreachable since Jan 11th

 - Last Hackage activity was upload of `true-name-0.1.0.0` on Jan 11th
 - Last public GitHub activity dates back to Jan 11th: https://github.com/liyang?tab=activity
 - https://github.com/liyang/vector-th-unbox/issues/11 filed on Jan 17th by @hvr
 - https://github.com/liyang/vector-th-unbox/pull/12 filed on Feb 1st by @RyanGlScott
 - Tried to reach @liyang via email on Feb 9th

/cc @bergmark

**Comment by hvr** [comment]
NMU release prepared at https://github.com/hackage-trustees/vector-th-unbox/releases/tag/0.2.1.4

**Comment by hvr** [comment]
NMU'ed via http://hackage.haskell.org/package/vector-th-unbox-0.2.1.4

**Comment by bergmark** [comment]
Cool!
