### ISSUE TITLE
esqueleto: Please relax upper bound on base package

### ISSUE THREAD

**Issue by erikd** [haskell-infra/hackage-trustees#65]
GHC 8.0 ships with base 4.9, but `esqueleto` currently requires `base < 4.9`. I have submitted a PR but so far that has gone un-answered : https://github.com/prowdsponsor/esqueleto/pull/135

Esqueleto doesn't have a lot of other packages depending on it, but it really should compile with ghc-8.0 and all that is required is this tiny tweak.

**Comment by erikd** [comment]
I have compiled this with GHC 8.0 rc3 and run all the tests.

Esqueleto doesn't use `template-haskell` directly so there are no TH issues.

**Comment by cartazio** [comment]
tested it on my post iavor ghc8.0 tip build, also works here, i'll bump the bound < 4.10, @erikd  that what you want right? :)

**Comment by erikd** [comment]
Perfect!

**Comment by cartazio** [comment]
bumped, also added it to matrix builder queue just to sanity check, closing for now :)

**Comment by erikd** [comment]
Thanks @cartazio !
