### ISSUE TITLE
possible NMU needed on missingH

### ISSUE THREAD

**Issue by cartazio** [haskell-infra/hackage-trustees#66]
see https://github.com/jgoerzen/missingh/issues/32
cc @davean

**Comment by cartazio** [comment]
On the linked thread The current maintainer has authorized a NMU and further noted he'd like it to be adopted by someone as he currently doesn't have time.  

Cc @davean @hvr @sclv

**Comment by hvr** [comment]
what's the status on this? 3 weeks have passed...

**Comment by cartazio** [comment]
I believe Davean got uploader acls by the current maintainer to do an NMU update with the proposed patch and then the maintainer updated the repo to reflect the changes

**Comment by cartazio** [comment]
But might be good to double check.  I'm afk / away from compiler

**Comment by bergmark** [comment]
John uploaded a new version a few days ago

**Comment by bergmark** [comment]
I also added revisions to the latest versions jgoerzen/missingh#34

**Comment by bergmark** [comment]
This is all done AFAICT.
