### ISSUE TITLE
Install-plans bitrotting due to GNU vs C99 `inline`-semantics

### ISSUE THREAD

**Issue by hvr** [haskell-infra/hackage-trustees#67]
This is a ticket to keep track of packages which suffer directly or indirectly from this effect. In case of indirectly affected packages we can restore install-plans by publishing maintenance releases.
- https://github.com/haskell/network/issues/199 (fixed via `network-2.3.2.1` release)
- https://github.com/tibbe/unordered-containers/pull/129 (fixed via `unordered-containers-0.2.7.1` release)
- ...

**Comment by cartazio** [comment]
So others needn't Google ,

http://stackoverflow.com/questions/216510/extern-inline/216546#216546

Has a good breakdown of what the changes in semantics are between the two
