### ISSUE TITLE
thrift need add proper upper bond

### ISSUE THREAD

**Issue by winterland1989** [haskell-infra/hackage-trustees#68]
I submit an issue to apach issue tracker without respond, here is the problem: in new version of `QuickCheck` and `unordered-containers` package defind instance conflict with thrift's own, make it completely unable to build. so i'd like someone can add version bound on QuickCheck <2.8.2 and unordered-containers <0.2.6 to thrift 0.9.3 on hackage to make it buildable.

**Comment by phadej** [comment]
let's see...

**Comment by phadej** [comment]
Adjusted the bounds... waiting for matrix build http://matrix.hackage.haskell.org/package/thrift

**Comment by phadej** [comment]
`0.9.3` compiles, `0.9.2` non-installable, `0.6.0` I'm not sure, if can work with GHC>=7.6

**Comment by winterland1989** [comment]
Thanks!
