### ISSUE TITLE
http-client-0.5 breaks upper-bound lacking packages

### ISSUE THREAD

**Issue by phadej** [haskell-infra/hackage-trustees#69]
The stackage issue: https://github.com/fpco/stackage/issues/1676 Around 20 packages from Stackage was hold back due bounds.

Let's document packages which are or were broken due missing upper bounds.

I suspect that turn red too (waiting for matrix.h.h.o)
- `gogol-core`
- `wreq`

Also `http-conduit` breaks packages in the same way. let's check based http://packdeps.haskellers.com/reverse/http-conduit on: 
- `git-annex`:
- `hoogle`
- `http-proxy`

---

Broken packages
- [x] servant-client
- [x] amazonka-core
- [x] DAV
- [x] wreq
- [x] kraken
- [x] http-reverse-proxy
- [x] keter
- [x] http-client-tls

**Comment by phadej** [comment]
### servant-client
<img width="680" alt="screen shot 2016-07-05 at 12 24 56" src="https://cloud.githubusercontent.com/assets/51087/16583224/d373b760-42bc-11e6-98c5-d0b90576a6e2.png">

**Comment by phadej** [comment]
### amazonka-core

<img width="691" alt="screen shot 2016-07-05 at 12 33 51" src="https://cloud.githubusercontent.com/assets/51087/16583234/e79ebeec-42bc-11e6-87e3-cd4fbcda044c.png">

**Comment by phadej** [comment]
Reported on Stackage issue, `DAV-1.2`:

```
[2 of 2] Compiling Network.Protocol.HTTP.DAV ( Network/Protocol/HTTP/DAV.hs, dist/build/Network/Protocol/HTTP/DAV.o )

Network/Protocol/HTTP/DAV.hs:160:32: error:
    Not in scope: data constructor `StatusCodeException'
    Perhaps you meant variable `matchStatusCodeException' (line 160)
    Perhaps you want to add `StatusCodeException' to the import list
    in the import of `Network.HTTP.Client'
    (Network/Protocol/HTTP/DAV.hs:77:1-169).
```

**Comment by hvr** [comment]
judging from http://packdeps.haskellers.com/reverse/http-client, there's of packages depending on http-client *directly* whose authors forgot to put upper bounds in place, and sadly this compounds via indirect dependencies :-/

**Comment by phadej** [comment]
I'll add `http-client` tag on `matrix.h.h.o` for packages I queued to check this issue

**Comment by phadej** [comment]
### wreq

before http-client-0.5 released:

![fireshot capture - wreq - package - hackage matrix builder_ - http___matrix hackage haskell org_pa-before](https://cloud.githubusercontent.com/assets/51087/16591302/f79e542a-42e3-11e6-9588-5dd394159a15.png)

after:

![fireshot capture - wreq - package - hackage matrix_ - http___matrix hackage haskell org_package_wreq-with](https://cloud.githubusercontent.com/assets/51087/16591312/005d14e8-42e4-11e6-88ad-5fc2c597093b.png)

I'm correcting bounds atm.

**Comment by phadej** [comment]
Seems that `http-client-0.5` itself fails to build with some configurations https://github.com/snoyberg/http-client/issues/210

**Comment by phadej** [comment]
[kraken](http://matrix.hackage.haskell.org/package/kraken) had two failures as well.

Not sure, seems (luckily!) that upper bounds used by many authors act as vaccination in masses: it helps prevent invalid plans even some packages aren't specifying them.

**Comment by hvr** [comment]
@phadej it's still fragile, because as soon as a 3rd party package relaxes its upper bound because it added support, suddenly install-plans will start to fail...

**Comment by hvr** [comment]
Some additional indirect fallout @ https://github.com/fpco/stackage-curator/issues/22

**Comment by hvr** [comment]
Stumbled over a few other ones:

 - `http-reverse-proxy`
 - `keter`

**Comment by phadej** [comment]
- [ ] `http-client-tls`

**Comment by bergmark** [comment]
For open ended issues like this, we can add comments for new entries but how about collecting everything in a checklist in the top comment (since we all can make edits to it)? That way we know what we need to do, and we can close when everything is done and re-open if new entries pop up.

**Comment by phadej** [comment]
@bergmark edited the first comment. Cannot verify as matrix is unresponsive to me.

**Comment by bergmark** [comment]
I fixed the remaining packages
