### ISSUE TITLE
`arithmoi` fails to compile with GHC 7.8.4 due to `-fllvm` flag

### ISSUE THREAD

**Issue by hvr** [haskell-infra/hackage-trustees#7]
https://bitbucket.org/dafis/arithmoi/issue/15/fails-to-compile-with-ghc-784-due-to-fllvm

This is a continuation of #3 (which was only about relaxing bounds which has been accomplished), see comments there for initial part of the discussion pertaining to the NMU issue at hand

**Comment by cartazio** [comment]
I think I'm now the maintainer at least temporarily, I'll dig into this
next weekend when I have some time.

**Comment by mietek** [comment]
Perhaps the solution is as simple as disabling the `-fflvm` flag by default.
https://github.com/mietek/arithmoi/commit/4326fe575029f50fded52c4c42b84016363eaf98

**Comment by hvr** [comment]
@mietek that's not enough to be a proper fix, it also ought to become a manual flag as it makes no sense to have it an automatic flag in the first place (as it doesn't affect the solver)

**Comment by mietek** [comment]
@hvr: Thanks for pointing that out. I’ve now amended the commit (https://github.com/mietek/arithmoi/commit/f49603f05f24f1c48361ff37f20e32dacc214c3b).

**Comment by cartazio** [comment]
i did a push earlier this evening, please confirm that the new version works fine on non llvm < 7.10 systems :) 

also still left is migrating code to support 7.10 gmp : )

**Comment by hvr** [comment]
I've filed https://github.com/cartazio/arithmoi/issues/1 for the `integer-gmp-1.0` issue, and I can confirm that 0.4.1.2 builds again for `llvm`-incapable GHC installs

**Comment by mietek** [comment]
@cartazio: Thanks for taking over the maintenance.
