### ISSUE TITLE
Tighter base upper bounds on records and type-functions

### ISSUE THREAD

**Issue by sjakobi** [haskell-infra/hackage-trustees#70]
`records-0.1.1.6` compiles with `ghc-7.8.4` but neither with `ghc-7.10.2` nor `ghc-7.10.3`. I'd suggest lowering the upper bounds on `base` to `< 4.8`.

`type-functions-0.2.0.3` compiles with  `ghc-7.10.3` but not with `ghc-8.0.1`.  An upper bound on `base` of `< 4.9` would be nice to have.

**Comment by hvr** [comment]
@sjakobi thanks for reporting this!

 - https://hackage.haskell.org/package/type-functions-0.2.0.3/revisions/
 - https://hackage.haskell.org/package/records-0.1.1.6/revisions/

/cc @phadej

**Comment by phadej** [comment]
I also sent Wolfgang an email about mine `type-functions` edit. He answered:

> Hi,
> 
> thanks for your work and for informing me.
>
> I had not realized that GHC 8.0.1 was already out. I will see that I
> publish an updated version of the type-function package some time soon.

**Comment by sjakobi** [comment]
I realize now that I should have contacted Wolfgang myself.

Thank you for providing this great service!

**Comment by hvr** [comment]
@sjakobi you can still contact him about `records`... I didn't contact him yet :-)

**Comment by sjakobi** [comment]
> @sjakobi you can still contact him about records... I didn't contact him yet :-)

I wrote him an email!

**Comment by bergmark** [comment]
Issue cleanup time! Is there anything left to do here? Otherwise let's close this.

**Comment by phadej** [comment]
Wolfgang made new releases. Let's close
