### ISSUE TITLE
dlist-instances conflicts with new dlist-0.8's native semigroup instance

### ISSUE THREAD

**Issue by hvr** [haskell-infra/hackage-trustees#72]
I've [revised](http://hackage.haskell.org/package/dlist-instances-0.1/revisions/) dlist-instances, and now we need a new dlist-instances release supporting dlist-0.8+ (https://github.com/gregwebs/dlist-instances/pull/2)

See also https://github.com/spl/dlist/issues/25#issuecomment-232141623

**Comment by bergmark** [comment]
According to https://github.com/gregwebs/dlist-instances/pull/2 this is fixed.
