### ISSUE TITLE
haskell-src-exts-1.18 breaks upper-bound lacking packages

### ISSUE THREAD

**Issue by hvr** [haskell-infra/hackage-trustees#73]
HSE 1.18 changed in a non-backward compat way. Even though HSE properly advised this via a major version bump, packages which didn't follow the PVP broke.

It's also noted in https://github.com/fpco/stackage/issues/1734#issuecomment-235968726 that "Essentially all 137 packages are broken by this release, the question is how many also impact stackage."

This ticket is to track which packages need upper bounds retrofitted.

**Comment by phadej** [comment]
I guess we list here packages went red, and fixed by either trustees or package authors themselves?

- [hindent](http://matrix.hackage.haskell.org/package/hindent)
- [hprotoc](http://matrix.hackage.haskell.org/package/hprotoc)

**Comment by phadej** [comment]
- [x] [haskintex](http://matrix.hackage.haskell.org/package/haskintex) 0.5.1-0.6
- [x] [hse-cpp](http://matrix.hackage.haskell.org/package/hse-cpp)

**Comment by hvr** [comment]
- [ ] [hat](http://matrix.hackage.haskell.org/package/hat)

**Comment by bergmark** [comment]
Some of these packages have red cells but the HSE issue is resolved in all.
