### ISSUE TITLE
optparse-applicative-0.13 breaks upper-bound lacking packages

### ISSUE THREAD

**Issue by ezyang** [haskell-infra/hackage-trustees#74]
Upstream: https://github.com/feuerbach/tasty/issues/145

Cabal CI is repro'ing, see https://travis-ci.org/haskell/cabal/jobs/152543984

---

EDIT: Packages known to be affected:
- [x] `tasty` (`0.10.0.1` &mdash; `0.11.0.3`, 11 versions)
- [x] `criterion` `(1.0.2.0`, `1.1.0.0` and `1.1.1.0`)
- [x] `wai-app-static` (`2.0.1` &mdash; `3.1.6`, 20 versions)
- [x] `purescript`
- [x] `tasty-golden` (`2.2.1` &mdash; `2.3.1`, 12 versions)
- [x] `omnifmt` (`0.2.1.0` and `0.2.1.1`)

**Comment by phadej** [comment]
resolved.

**Comment by RyanGlScott** [comment]
`criterion-1.1.1.0` (probably other versions too) also fails to build with `optparse-applicative-0.13.0.0`. See https://github.com/bos/criterion/issues/113

Should a separate issue be opened for this, or should we lump all `optparse-applicative-0.13.0.0`-related build failures into this issue?

**Comment by phadej** [comment]
Triggered matrix build for criterion. Let's see

**Comment by phadej** [comment]
only criterion 1.0.2.0,  1.1.0.0 and  1.1.1.0 were affected.

Let's have this issue open at least until optparse-applicative-0.13.0.0 gets into stackage nightly

**Comment by phadej** [comment]
`wai-app-static` is a way greener now.

**Comment by RyanGlScott** [comment]
`tasty-golden-2.3.1` is known not to build against `optparse-applicative-0.13` (see https://github.com/feuerbach/tasty/issues/145#issuecomment-242058799).

**Comment by hvr** [comment]
@RyanGlScott indeed, 12 releases broken:

![untitled](https://cloud.githubusercontent.com/assets/285533/17959416/90d826be-6aa0-11e6-9a22-9212756b733c.png)

**Comment by HuwCampbell** [comment]
I feel like I broke the world :/

**Comment by hvr** [comment]
@HuwCampbell  Don't feel bad! `optparse-applicative` did the proper thing; it's rather that some packages failed to adhere to proper dependency management standards. This happens occasionally, and that's what Hackage Trustees are here to help with. There would have been breakage sooner or later anyway at some point, and by taking a hit now the technical debt has been cleared while the cost was still manageable.

**Comment by bergmark** [comment]
Looks resolved!
