### ISSUE TITLE
data-lens-2.11.* needs tighter bounds on base

### ISSUE THREAD

**Issue by hvr** [haskell-infra/hackage-trustees#75]
E.g.

```
src/Data/Lens/Partial/Common.hs:11:8:
    Could not find module ‘Data.Functor.Sum’
    It is a member of the hidden package ‘transformers-compat-0.5.1.3’.
    Perhaps you need to add ‘transformers-compat’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
data-lens-2.11 failed during the building phase
```

and

```
src/Data/Lens/Partial/Common.hs:56:18:
    Not in scope: type constructor or class ‘Monoid’
    Perhaps you meant ‘Monad’ (imported from Prelude)

src/Data/Lens/Partial/Common.hs:57:26:
    Not in scope: ‘mempty’
    Perhaps you meant ‘empty’ (imported from Control.Applicative)
xcabal: Error: some packages failed to install:
data-lens-2.11.0.1 failed during the building phase.
```

/cc @roconnor

**Comment by hvr** [comment]
I've fixed up the meta-data:

 - https://hackage.haskell.org/package/data-lens-2.11.0.1/revisions/
 - https://hackage.haskell.org/package/data-lens-2.11/revisions/

TODO: file an upstream PR (against the  "2.9.0" branch!) restoring compat with pre-base-4.8

**Comment by roconnor** [comment]
Data.Functor.Sum is included with the transformers 4.0 lower bound.

I think I know how to fix the     Not in scope: type constructor or class ‘Monoid’
However I haven't been able to reproduce the issue.  What configuration did you use to get this error.

Also, how did you determine the 4.8 as the minimum bound for base?

ty.

**Comment by bergmark** [comment]
@roconnor Probably by looking at http://matrix.hackage.haskell.org/package/data-lens, although now it shows the build status after the new revisions

**Comment by roconnor** [comment]
Okay, I was finally able to coax the error:

nix-build --keep-going --arg hp 'let pkg = (import <nixpkgs> {}); in pkg.haskell.packages.ghc784.override { overrides = self : super : { bifunctors = self.bifunctors_5_2; semigroupoids = self.semigroupoids_5_0_1; transformers = self.transformers_0_4_3_0 ; transformers-compat = self.transformers-compat_0_4_0_4; doctest = null; comonad = pkg.lib.overrideDerivation super.comonad (oldAttrs: { doCheck = false; configureFlags = ["--disable-tests"]; }); distributive = pkg.lib.overrideDerivation super.distributive (oldAttrs: { doCheck = false; configureFlags = ["--disable-tests"]; testHaskellDepends = []; }); contravariant = pkg.lib.overrideDerivation super.contravariant (oldAttrs: { doCheck = false; configureFlags = ["--disable-tests"]; testHaskellDepends = []; }); semigroups = (import <nixpkgs/pkgs/development/haskell-modules/lib.nix> {pkgs = pkg;}).addBuildDepends super.semigroups [self.transformers]; }; }'

There is probably an easier way ;)

I'll make a release that adds

import Data.Monoid (Monoid, mempty)

Which should allow the package to build under old base.

Thanks for bringing this to my attention.  I should be more diligent testing old versions of GHC, but as you can see, getting a set of pacakges to build under older GHCs can be quite difficult.

**Comment by hvr** [comment]
@roconnor as @bergmark already said, I noticed it on matrix.h.h.o, and locally I simply use something like `cabal new-build -w ghc-7.8.4` with a few educatedly guessed  `--constraint ...`s  to figure out where the problem is...

btw, is there a specific reason why the `data-lens` repo has its Issue component disabled?

**Comment by phadej** [comment]
One option is to setup Travis CI using https://github.com/hvr/multi-ghc-travis scripts. It is useful, simple and free

**Comment by roconnor** [comment]
No reason that the issue component was disabled beyond that is the default that github made at the time I forked the repo.  I have enabled it now.

**Comment by roconnor** [comment]
No reason that the issue component was disabled beyond that is the default that github made at the time I forked the repo.  I have enabled it now.

**Comment by roconnor** [comment]
2.11.1 is now released.

**Comment by hvr** [comment]
all looks good now, so I'm closing this one...
