### ISSUE TITLE
hoogle needs network constraint

### ISSUE THREAD

**Issue by glguy** [haskell-infra/hackage-trustees#76]
Related ticket https://github.com/ndmitchell/hoogle/issues/181

Hoogle has a hard dependency on network-uri without a lower bound on network which is causing build failures for people with network < 2.6 already installed.

This has come up a couple times now on IRC with people looking for help.

**Comment by hvr** [comment]
For the record, I've hacked up

  http://hackage.haskell.org/package/network-uri-flag-0.1

And I'll look into making it possible in hackage-server to retrofit `network-uri-flag` dependencies in older releases (like we can with `base` or `base-orphan` right now), at least temporarily...

**Comment by bergmark** [comment]
Seems like @hvr fixed this!
