### ISSUE TITLE
stringsearch fails to compile on 7.10

### ISSUE THREAD

**Issue by davean** [haskell-infra/hackage-trustees#8]
https://bitbucket.org/dafis/stringsearch/issue/1/compilation-errors-using-ghc-head#comment-16980851

BryanOSullivan has given the signoff for a Trustees release to fix this (https://twitter.com/bos31337/status/581674139158609921).

**Comment by cartazio** [comment]
sounds good to me.
lets just runn it through travis CI using https://github.com/hvr/multi-ghc-travis/blob/master/.travis.yml to sanity check that it works on the target supported range and then we can push it

**Comment by cartazio** [comment]
once https://travis-ci.org/haskell-infra/stringsearch is all green, lets push it

**Comment by cartazio** [comment]
looks all green. If someone does the upload tomorrow before i wakeup, awesome, else i'll do it then

**Comment by hvr** [comment]
@cartazio btw, let's rather avoid spamming `haskell-infra` with package-repos until we've decided which GitHub org to use for NMU forks

**Comment by cartazio** [comment]
Davean created that repo :)

**Comment by davean** [comment]
I was just trying to follow the draft as close as possible.

**Comment by hvr** [comment]
changes LGTM :+1:

**Comment by bergmark** [comment]
Can we close this?
