### ISSUE TITLE
word24 takeover

### ISSUE THREAD

**Issue by bergmark** [haskell-infra/hackage-trustees#82]
Requested by @winterland1989 in https://groups.google.com/forum/#!topic/haskell-cafe/IVSlQelwGsU on 2016-09-29, so hackage admins can be contacted 2016-10*-13

**Comment by hvr** [comment]
@bergmark do we need a timemachine? :3

**Comment by bergmark** [comment]
whoopsie

**Comment by winterland1989** [comment]
John has already added  me to the hackage maintainers list after he got the takeover email, so it's not necessary to do so, thanks!

**Comment by bergmark** [comment]
Great!
