### ISSUE TITLE
Absentee Esqueleto maintainer

### ISSUE THREAD

**Issue by bitemyapp** [haskell-infra/hackage-trustees#84]
https://github.com/prowdsponsor/esqueleto/issues/137#issuecomment-256532641

This is first notice for my contact of Prowdsponsor / Lessa.

![screenshot from 2016-11-07 12-35-37](https://cloud.githubusercontent.com/assets/320177/20070618/b3df5314-a4e6-11e6-9d00-62c4891bc2cd.png)

**Comment by bitemyapp** [comment]
Additional note: I use Esqueleto at my day job, which is more than I can say for Bloodhound :)

**Comment by hvr** [comment]
@bitemyapp btw, as per https://wiki.haskell.org/Taking_over_a_package it's recommended to communicate/broadcast your intention to take over a package over a public medium which has a wide reach, such as haskell-cafe or the libraries mailinglist; have you done that already?

**Comment by jdreaver** [comment]
@bitemyapp let me know if you publicly broadcast your intention to take over the package, I'm :+1: on that. 

I also want Felipe to come back too though :(

**Comment by bitemyapp** [comment]
@hvr I'd discussed it on a public Slack (FPChat, has a couple thousand members, several hundred in #haskell), I'll cross-post to the mailing list.

**Comment by bitemyapp** [comment]
@hvr 
![screenshot from 2016-11-18 16-14-46](https://cloud.githubusercontent.com/assets/320177/20448538/24c1d586-adaa-11e6-8f01-d7e577efd3c2.png)
![screenshot from 2016-11-18 16-14-41](https://cloud.githubusercontent.com/assets/320177/20448539/24ce3b3c-adaa-11e6-9f1c-e7bec2b8901b.png)

**Comment by hvr** [comment]
For the record, @meteficha last recorded activity on Hackage was back in february:

```
...
 yesod-mangopay                   | 1.11.5   | FelipeLessa | 2015-09-21 14:21:10+00
 diagrams-qrcode                  | 1.3      | FelipeLessa | 2015-10-02 15:11:49+00
 ig                               | 0.6      | FelipeLessa | 2015-10-02 15:14:12+00
 yesod-auth-account-fork          | 2.0.3    | FelipeLessa | 2015-10-02 15:20:34+00
 skein                            | 1.0.9.4  | FelipeLessa | 2015-12-30 19:46:05+00
 fb                               | 1.0.13   | FelipeLessa | 2015-12-30 19:58:29+00
 fb-persistent                    | 0.3.6    | FelipeLessa | 2015-12-30 20:04:07+00
 serversession-backend-acid-state | 1.0.3    | FelipeLessa | 2015-12-31 13:27:15+00
 serversession-backend-persistent | 1.0.2    | FelipeLessa | 2015-12-31 17:45:39+00
 serversession-backend-redis      | 1.0.1    | FelipeLessa | 2015-12-31 17:46:19+00
 mangopay                         | 1.12     | FelipeLessa | 2015-12-31 17:49:38+00
 yesod-mangopay                   | 1.12     | FelipeLessa | 2015-12-31 17:49:41+00
 esqueleto                        | 2.4.2    | FelipeLessa | 2016-01-14 20:23:23+00
 esqueleto                        | 2.4.3    | FelipeLessa | 2016-02-12 20:48:18+00
```

And GitHub shows the last activity dating back to July 2016.

**Comment by danpalmer** [comment]
Esqueleto is now out-of-date enough that the `yesod-postgres` Stack template isn't compatible with it without some modification. 👍  to more maintainers.

**Comment by hvr** [comment]
Summoning @hesselink

**Comment by thomasjm** [comment]
@bitemyapp posted his intent to take over to haskell-cafe 25 days ago. The policy at https://wiki.haskell.org/Taking_over_a_package says the admins will wait 2-6 weeks before making the change--any chance we could call it soon? :)

(Esqueleto Stackage issues have been ongoing since June 2016--at this point it's the main thing keeping me from upgrading to GHC 8.)

**Comment by jdreaver** [comment]
+1 on moving this along. It's been many weeks now, and Felipe is clearly absentee (as sad as that is). What are the next steps here? Is there someone else that needs to approve?

**Comment by AKurilin** [comment]
+1 - I'd love for Felipe to continue maintaining this but if it's not an option then I'm in support of @bitemyapp taking it over, or perhaps we at Front Row can help out with it.

**Comment by hesselink** [comment]
Turns out @snoyberg is a maintainer for esqueleto on hackage. So I'll leave it up to him to decide how to proceed here. I've sent him an email.

**Comment by snoyberg** [comment]
I had no memory of having that, doh! Yup, I have no problem with giving @bitemyapp access, I'll do that now.

**Comment by bitemyapp** [comment]
I think this is sorted, closing for now.

@jdreaver @AKurilin @danpalmer @thomasjm please file your current needs/concerns at  https://github.com/bitemyapp/esqueleto the current version has some fixes from @pseudonom - like to get a sense of where things are at and what needs catching up on.
