### ISSUE TITLE
Change vector's primitive upper bound 

### ISSUE THREAD

**Issue by winterland1989** [haskell-infra/hackage-trustees#85]
See: https://github.com/haskell/vector/issues/142, please change current upper bound ASAP, This breakage is affecting lots of package building.

**Comment by hvr** [comment]
I'm on it

**Comment by hvr** [comment]
Added `primitive < 0.6.2` bounds:

 - https://hackage.haskell.org/package/vector-0.11.0.0/revisions/
 - https://hackage.haskell.org/package/vector-0.10.12.3/revisions/

**Comment by winterland1989** [comment]
Thanks!
