### ISSUE TITLE
Fix dependencies of double-conversion on Windows

### ISSUE THREAD

**Issue by Mistuke** [haskell-infra/hackage-trustees#87]
The package `double-conversion` currently does not work on Windows due to incomplete dependencies specified in the cabal file.

Unfortunately `double-conversion` hasn't been updated since 2014.

This issue was opened in 2014 with no response from the maintainer https://github.com/bos/double-conversion/issues/7 and a fix was submitted in October 2015 with again no response from maintainer https://github.com/bos/double-conversion/pull/13

Given that the package seems to be reasonably popular, and maintainer hasn't responded in 2 years and update needed is minimal. I hope patched cabal file can be uploaded so Windows users don't have to jump through hoops.

There are multiple people and projects whom have hit this issue. e.g.
https://github.com/ucsd-progsys/liquidhaskell/issues/806
and 
https://github.com/commercialhaskell/stack/issues/754

**Comment by phadej** [comment]
Such edit needs NMU

**Comment by phadej** [comment]
@hvr contacted Bryan via email (He isn't following github actively). Let's wait a bit.

**Comment by Mistuke** [comment]
Alright :) Thanks for the update!

**Comment by hvr** [comment]
@Mistuke A new version of double-conversion was just released by @bos which is supposed to fix all known issues. Is there anything left to do here?

**Comment by Mistuke** [comment]
@hvr No, this fixes the issue. Thanks!
