### ISSUE TITLE
Friday Non-takeover (additional maintainer)

### ISSUE THREAD

**Issue by TomMD** [haskell-infra/hackage-trustees#88]
I'd like to be _added_ to the hackage maintainer list for Friday.  Evidence this is likely already OK with the MIA maintainer (Raphael): I already have commit access to the repository under his github username.

Initiated here: https://github.com/RaphaelJ/friday/pull/27

I could send the note to an ML if you'd like but I haven't had reason to believe Raphael reads MLs.

**Comment by hvr** [comment]
summoning @hesselink

**Comment by hesselink** [comment]
Summoned! This all looks good, @TomMD I've added you as a maintainer.
