### ISSUE TITLE
download-curl depends on tag-soup < 0.13, which fails on ghc 7.10.

### ISSUE THREAD

**Issue by seanhess** [haskell-infra/hackage-trustees#9]
Getting a compile error from changes to Data.List. It's already been fixed in tag-soup 0.13.3, but download-curl's cabal file depends on tag-soup < 0.13.

**Comment by bergmark** [comment]
I've revised tagsup versions `> 0.1 && < 0.13` to have a `base < 4.8` constraint, and `download-curl` `0.0`, `0.1`, and `0.1.1` to require `tagsoup > 0.1 && < 0.13`. You now get a dependency resolution error if trying to install `download-curl` on GHC 7.10.

@seanhess have you contacted the maintainer of download-curl about adding GHC 7.10 support? Please see https://github.com/haskell-infra/hackage-trustees/blob/master/CONTRIBUTING.md

**Comment by seanhess** [comment]
I just emailed him, I don't see another way to do it.

**Comment by seanhess** [comment]
The email listed on the hackage page is down, and it failed to deliver.

**Comment by bergmark** [comment]
I sent him a message on twitter, sorry for the delay. https://twitter.com/adambergmark/status/585888720957616132

This also depends on https://github.com/haskell-infra/hackage-trustees/issues/12 , otherwise you have to use `time < 1.2`.

**Comment by gbaz** [comment]
I believe @soenkehahn may have taken over as maintainer, even if the maintainer field wasn't uploaded? I remember a number of dons' packages were taken over or at least given shared maintainership over the last years as he's gotten more busy elsewhere...

**Comment by soenkehahn** [comment]
No, I haven't. I just uploaded a new version to hackage (with dons' permission).

**Comment by gbaz** [comment]
So I think we have ongoing permission to do a NMU on this, if someone wants to tackle it.

**Comment by hvr** [comment]
*bump*

**Comment by bergmark** [comment]
Turns out doing an NMU is no longer needed (was it ever?). Just added a revision ( http://hackage.haskell.org/package/download-curl-0.1.4/revisions/ ) and will close this once the matrix builder verifies.

**Comment by bergmark** [comment]
![Uploading Screen Shot 2015-10-12 at 21.08.08.png…]()

**Comment by bergmark** [comment]
Whoops I was too quick

<img width="691" alt="screen shot 2015-10-12 at 21 08 08" src="https://cloud.githubusercontent.com/assets/100681/10436246/86eda590-7125-11e5-8e93-9f6facb5da06.png">
