### ISSUE TITLE
aeson build failures

### ISSUE THREAD

**Issue by bergmark** [haskell-infra/hackage-trustees#92]
I've been getting this on a bunch of travis builds: https://travis-ci.org/faylang/fay#L2919

I wasn't able to reproduce it locally, any ideas?

```
Failed to install aeson-1.0.2.1
Last 10 lines of the build log ( /home/travis/.cabal/logs/aeson-1.0.2.1.log ):
       <> LT.foldrChunks (\ x xs -> EB.unquoted x <> xs) (char7 '"') t’
    In the expression:
      Encoding
      $ char7 '"'
        <> LT.foldrChunks (\ x xs -> EB.unquoted x <> xs) (char7 '"') t
    In an equation for ‘lazyText’:
        lazyText t
          = Encoding
            $ char7 '"'
              <> LT.foldrChunks (\ x xs -> EB.unquoted x <> xs) (char7 '"') t
```

**Comment by hvr** [comment]
it's unfortunate that it's truncated... it would be worth a try to use `-j1` to have the full msg outputted; or add some `cat /home/travis/.cabal/logs/*.log` line to the travis log...

**Comment by hvr** [comment]
@bergmark alternatively, try to `cabal freeze` and then `cat` the resulting freeze file to the log output...

**Comment by bergmark** [comment]
Ah here's the issue: https://github.com/lpsmith/bytestring-builder/blob/67fa986eb2946dcf7161f70a461b3ee48a6a3682/src/Data/ByteString/Short/Internal.hs#L137

**Comment by bergmark** [comment]
I'm not sure how this should be solved though, semigroups depends on bytestring-builder which conditionally has a semigroup instance for newer base versions. Should  the instance be defined in semigroups for older ghcs?

**Comment by hvr** [comment]
@bergmark https://github.com/ekmett/semigroups/blob/master/src-ghc7/Data/Semigroup.hs#L933-L937

**Comment by bergmark** [comment]
I think this was just an old cabal-install.

**Comment by bergmark** [comment]
Resurfaced for @23Skidoo with cabal-install 1.24. @23Skidoo are you able to reproduce this?

**Comment by 23Skidoo** [comment]
@bergmark It depends on the contents of the package DB. First I managed to trigger it with an old `cabal-install` and that made `cabal-1.24 install aeson` fail as well. Nuking `~/.ghc` and `~/.cabal` helped.

**Comment by 23Skidoo** [comment]
Yeah, and that was with GHC 7.8.

**Comment by bergmark** [comment]
Ah, thanks, that makes sense. So I guess we should close this again since the fix is to nuke those folders?

**Comment by 23Skidoo** [comment]
Maybe the fix @hvr [linked above](https://github.com/haskell-infra/hackage-trustees/issues/92#issuecomment-271167484) can be applied to `aeson`, but I don't have time to investigate right now.

**Comment by ertyseidohl** [comment]
Just wanted to add that I fixed a similar issue by deleting ~/.ghc, but that also deleting ~/.cabal made cabal throw errors for me.
