### ISSUE TITLE
GHC 8.0.2 build breakages

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-infra/hackage-trustees#93]
This is a ticket to keep track of packages that fail to build with GHC 8.0.2. (Note that I'm excluding #90, since that was reported separately.)

They can be lumped into two categories:

* [GHC Trac #12881](https://ghc.haskell.org/trac/ghc/ticket/12881)
  * [X] [`consul-haskell-0.4`](http://hackage.haskell.org/package/consul-haskell-0.4) (https://github.com/alphaHeavy/consul-haskell/pull/17)
  * [ ] [`hbayes-0.5.2`](http://hackage.haskell.org/package/hbayes-0.5.2) (https://github.com/alpheccar/hbayes/pull/2)
  * [X] [`quickcheck-combinators-0.0.1`](http://hackage.haskell.org/package/quickcheck-combinators-0.0.1) (https://github.com/athanclark/quickcheck-combinators/pull/2)
  * [X] [`rethinkdb-2.2.0.7`](http://hackage.haskell.org/package/rethinkdb-2.2.0.7) (https://github.com/AtnNn/haskell-rethinkdb/pull/68)
* `ImpredicativeTypes` becoming lousier
  * [ ] [`vector-algorithms-0.7.0.1`](http://hackage.haskell.org/package/vector-algorithms-0.7.0.1)'s test suite (http://hub.darcs.net/dolio/vector-algorithms/issue/9)

**Comment by phadej** [comment]
Thanks for the patches!

**Comment by RyanGlScott** [comment]
[`rethinkdb-2.2.0.8`](http://hackage.haskell.org/package/rethinkdb-2.2.0.8) released with GHC 8.0.2 support.

**Comment by RyanGlScott** [comment]
[`consul-haskell-0.4.2`](http://hackage.haskell.org/package/consul-haskell-0.4.2) has been released, which supports GHC 8.0.2.

**Comment by RyanGlScott** [comment]
[`quickcheck-combinators-0.0.2`](http://hackage.haskell.org/package/quickcheck-combinators-0.0.2) has been released, which supports GHC 8.0.2.
