### ISSUE TITLE
transformers-0.5.3.0 no longer compatible with GHC 7.8 and earlier

### ISSUE THREAD

**Issue by ezyang** [haskell-infra/hackage-trustees#94]
Could we get a base bounds bump?

Sample failing builds log: https://travis-ci.org/haskell/cabal/jobs/202820176

Upstream tracking issue: http://hub.darcs.net/ross/transformers/issue/36

**Comment by phadej** [comment]
IMHO it's bug in transformers, and should be fixed there (with baseball bump or proper contexts or use of `liftM`, which is quite simple fix)

**Comment by RyanGlScott** [comment]
A new version of `transformers` has been release which fixes this issue, and moreover, `transformers-0.5.3.0` has been marked as deprecated (and had its version bounds tightened), so is as good as fixed.

**Comment by phadej** [comment]
Thanks for the info. Closing this issue.
