### ISSUE TITLE
cassava: extend upper bound for vector

### ISSUE THREAD

**Issue by sjakobi** [haskell-infra/hackage-trustees#95]
The author [has been notified](https://github.com/hvr/cassava/issues/129) of the issue and [a PR](https://github.com/hvr/cassava/pull/125) has been open for several weeks. Given that it's a simple bounds issue it would be nice if a trustee could fix it.

**Comment by bergmark** [comment]
Done https://hackage.haskell.org/package/cassava-0.4.5.1/revisions/

**Comment by sjakobi** [comment]
Thanks a lot!
