### ISSUE TITLE
dbus takeover

### ISSUE THREAD

**Issue by bergmark** [haskell-infra/hackage-trustees#96]
Requested 2017-03-17 https://mail.haskell.org/pipermail/haskell-cafe/2017-March/126561.html by @rblaze

**Comment by hvr** [comment]
@rblaze states

> It depends on several other packaged with upper bounds too restrictive for the latest versions.

However, the only upper bound that was limiting was the upper bound on `vector` (which I've just relaxed after having convinced myself that the API changes in vector-0.12 don't break `dbus` as well as having run the testsuite). Coincidentally, there were a couple of upper bounds missing which I added.

**Comment by rblaze** [comment]
It is also using chell-quickcheck in tests, which is dependent on QuickCheck <2.9. And I suppose other libraries will start to drop off allowed range soon. My intention is to return dbus to stackage builds, and this may take more updates, see https://github.com/fpco/stackage/pull/2293

**Comment by hvr** [comment]
@rblaze Oh right, yeah... this limitation of Stack/Stackage that even the testsuite compent's deps which are totally irrelevant when you just want to use the library component need to be inside the Stackage snapshot is super annoying (which is actually one of the reasons I don't bother to get my packages included in Stackage) :-(

**Comment by bergmark** [comment]
@hvr you can add your packages with skipped test suites by filing them under Wontfix.

**Comment by hvr** [comment]
@bergmark I see... can't we just use that for `dbus` as well then? :-)

**Comment by bergmark** [comment]
Sure! But both trustees and stackage curators should be happier if there's a designated maintainer with hackage access to take care of issues.

**Comment by bergmark** [comment]
@rblaze it's been > 2 weeks now, has anything happened so far? Next step is to e-mail/ping hackage admins to transfer maintainership

**Comment by rblaze** [comment]
Yep, thanks for reminding, will do right away.

**Comment by hesselink** [comment]
I've added @rblaze to the maintainers of dbus.

**Comment by bergmark** [comment]
Thanks!
