### ISSUE TITLE
quickcheck-instances takeover

### ISSUE THREAD

**Issue by phadej** [haskell-infra/hackage-trustees#97]
Requested at 2017-04-07 https://mail.haskell.org/pipermail/haskell-cafe/2017-April/126726.html

#78 is related. @hvr is a co-maintainer of `uuid` atm.

**Comment by phadej** [comment]
I'll send an email to hackage admins to add me as maintainer in few days; if no-one objects.

**Comment by hvr** [comment]
@phadej I'd suggest sending the email now to avoid any further delays. That way you got the permissions on Hackage in place, but can already start planning the actual upload together with the QC maintainers.

**Comment by hvr** [comment]
@phadej any progress made?

**Comment by phadej** [comment]
@hvr, I sent an email. I totally forgot about this one back then.

**Comment by hesselink** [comment]
I've added @phadej as a maintainer.

**Comment by bergmark** [comment]
Thanks!
