### ISSUE TITLE
store - overeager restriction in revision (was: possible revision bug?)

### ISSUE THREAD

**Issue by bergmark** [haskell-infra/hackage-trustees#98]

**Comment by bergmark** [comment]
Whoops, premature RET...

Looking at https://hackage.haskell.org/package/store-0.2.1.2/revisions/ we can see that an upper bound was added to base64-bytestring. The lower bound was not changed but is `>= 0.1.1`, but somehow stackage lts-7 includes store-0.2.1.2+base64-bytestring-1.0.0.1. Is there something wrong with hackage, or something wrong with the lts build? AFAIK there should be no reason for LTS to allow this combination if the constraints don't allow it...

**Comment by hvr** [comment]
@bergmark you're right! I'll fix it rightaway

**Comment by bergmark** [comment]
Thanks! It's very strange though, looking at https://hackage.haskell.org/package/store-0.2.1.2/src/store.cabal there is no x-revision field there but the lower bound is the same!

**Comment by hvr** [comment]
@bergmark I've fixed the `<0.2`'s... but why is it strange that the 0th revision looks that way? :-)

**Comment by bergmark** [comment]
Ah I think I was jumbling up the version numbers :)

**Comment by bergmark** [comment]
Should be good now, I'll verify tomorrow.

**Comment by hvr** [comment]
@bergmark Btw, avoiding/catching issues like this quicker is why I'm planning for the next-gen matrix to keep track of package collections (starting with LTS snapshots)...

**Comment by bergmark** [comment]
👍
